/* WakeSuite V9.3.11
 * Priority Amazon/Flipkart POC communication contract + Drive-backed suppression POA library.
 * Locked 07 Oct 2026.
 *
 * Communication contract:
 * - Amazon combined POC: consolidated Issue / No. of ASINs / Revenue Impact per Day summary,
 *   separate Live Price Disparity, ASIN Suppression and Buy Box workbooks, plus Buy Box APT.
 * - Amazon individual Live Price Disparity: ASIN count + Excel attachment.
 * - Amazon individual ASIN Suppression: inline Category / ASIN / Rev Impact / POA Link, no Escalated On.
 * - Amazon individual Buy Box: Buy Box report + APT.
 * - Flipkart Live Price Disparity: full inline table in email; download remains on report page.
 * - Revenue-impact presentation is rounded to whole rupees. Internal calculations retain precision.
 *
 * POA contract:
 * - Four bundled category templates; originals never modified.
 * - Existing suppression occurrence POA link is reused.
 * - Missing POA is generated by replacing only the sample ASIN + product title in the category template.
 * - Generated DOCX is stored in the fixed WakeSuite POA Drive category folder and shared read-only to wakefit.co.
 */
(function(){
  'use strict';

  const ISSUE_TYPES={
    amazon:['Live Price Disparity','ASIN Suppression','Buy Box Suppression'],
    flipkart:['Live Price Disparity']
  };

  const POA_CONFIG={
    domain:'wakefit.co',
    driveScope:'https://www.googleapis.com/auth/drive',
    templates:{
      'Mattress':{
        asset:'./assets/poa/Mattress_POA_Master_Template.docx',
        sampleAsin:'B0DP9Z528W',
        sampleTitle:'Wakefit ShapeSense Orthopedic Classic Memory Foam Mattress | 10 Years Warranty | Mattress Single Bed, 6-Inch Bed Mattress, Single Size (70x30x6 Inches, Medium Firm)'
      },
      'Furniture':{
        asset:'./assets/poa/Furniture_POA_Master_Template.docx',
        sampleAsin:'B0BH4TLG26',
        sampleTitle:'Wakefit Bed | 1 Yr Warranty | Bed Queen Size, Storage Box & Foam-Cushioned Upholstery Headboard, Density: 680–750 kg/m³, Termite & Borer Resistant, Fits Mattresses Up to 8 Inches (Orion 78 x 60 - CW)'
      },
      'Accessories':{
        asset:'./assets/poa/Accessories_POA_Master_Template.docx',
        sampleAsin:'B09VT45R9V',
        sampleTitle:'Wakefit Premium Twill Weave 200 TC 100% Cotton Fitted Bedsheet with 2 Pillow Cover | Queen - 78x60 inch | Geometric Printed Soft & Breathable Queen Size Bed Sheet | Maze'
      },
      'Office Chairs':{
        asset:'./assets/poa/Office_Chairs_POA_Master_Template.docx',
        sampleAsin:'B0HCW9117N',
        sampleTitle:'Wakefit Maven Ergonomic Office Chair for Work | 1 Year Warranty | Single Lock and Recline | Soft Foldable Armrest | Strong Nylon Base | 8+ Hours of Comfort | Black & Grey'
      }
    }
  };

  let driveToken='';
  let driveTokenExpires=0;
  const templateBuffers=new Map();
  const folderCache=new Map();
  let driveTokenClient=null;
  let jsZipPromise=null;

  function clean(v){return String(v??'').trim();}
  function esc(v){return typeof escapeHtml==='function'?escapeHtml(v):String(v??'');}
  function marketName(m){return m==='amazon'?'Amazon':'Flipkart';}
  function identifierLabel(m){return m==='amazon'?'ASINs':'FSNs';}
  function roundImpact(v){const n=Number(v);return Number.isFinite(n)?Math.round(n):0;}
  function formatImpact(v){return `₹${roundImpact(v).toLocaleString('en-IN')}`;}
  function safeFilePart(v){return clean(v).replace(/[\\/:*?"<>|]+/g,' ').replace(/\s+/g,' ').trim();}
  function plainNumber(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('en-IN',{maximumFractionDigits:2}):'';}
  function dateText(iso){
    if(!iso)return '';
    try{return new Date(`${iso}T00:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}).replace(/,/g,'');}
    catch(_e){return iso;}
  }
  function rowId(row,market){
    if(market==='amazon')return clean(row?.asin||row?.productId||row?.identifier||row?.ASIN);
    return clean(row?.fsn||row?.productId||row?.identifier||row?.FSN);
  }
  function normalizeRow(row,market){
    const r=row||{},id=rowId(r,market);
    return market==='amazon'
      ? {...r,asin:clean(r.asin)||id,productId:clean(r.productId)||id,identifier:clean(r.identifier)||id,azSku:clean(r.azSku||r.marketSku||r['AZ SKU'])}
      : {...r,fsn:clean(r.fsn)||id,productId:clean(r.productId)||id,identifier:clean(r.identifier)||id,fkSku:clean(r.fkSku||r.marketSku||r['FK SKU'])};
  }
  function uniqueCount(rows,market){return new Set((rows||[]).map(r=>rowId(r,market)).filter(Boolean)).size;}
  function issueRows(kind,market,issueType=''){
    const state=v7CommunicationsState;
    if(!state?.[market])return [];
    const src=(kind==='followup'?(state[market].follow||[]):[...(state[market].newRows||[]),...(state[market].follow||[])]).map(r=>normalizeRow(r,market));
    return issueType?src.filter(r=>r.issueType===issueType):src;
  }
  function issueImpact(row){
    return Number(row?.revenueImpactPerDay??row?.liveDailyRevenueImpact??row?.buyBoxRevenueImpactPerDay??0)||0;
  }
  function issueGroupImpact(rows,type){return (rows||[]).filter(r=>r.issueType===type&&r.revenueAvailable!==false).reduce((a,r)=>a+issueImpact(r),0);}
  function yellowTh(){return 'border:1px solid #c8c8c8;padding:7px;background:#ffe600;text-align:left;font-weight:700';}
  function tdStyle(){return 'border:1px solid #c8c8c8;padding:7px;text-align:left';}

  function loadJsZip(){
    if(window.JSZip)return Promise.resolve(window.JSZip);
    if(jsZipPromise)return jsZipPromise;
    jsZipPromise=new Promise((resolve,reject)=>{
      const s=document.createElement('script');
      s.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';
      s.async=true;
      s.onload=()=>window.JSZip?resolve(window.JSZip):reject(new Error('DOCX engine did not load.'));
      s.onerror=()=>reject(new Error('DOCX engine could not be loaded. Check the network connection.'));
      document.head.appendChild(s);
    });
    return jsZipPromise;
  }

  function xmlEscape(text){
    return String(text??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
  }
  function replaceAllLiteral(source,from,to){return String(source).split(from).join(to);}
  function replaceWordText(xml,replacements){
    const doc=new DOMParser().parseFromString(xml,'application/xml');
    if(doc.getElementsByTagName('parsererror').length)throw new Error('POA template XML is invalid.');
    const ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
    const counts=replacements.map(()=>0);
    // Paragraph boundaries prevent matching unrelated adjacent text; run styles stay in place.
    for(const paragraph of [...doc.getElementsByTagNameNS(ns,'p')]){
      const nodes=[...paragraph.getElementsByTagNameNS(ns,'t')];
      replacements.forEach(([from,to],k)=>{
        const joined=nodes.map(n=>n.textContent).join('');
        const hits=[];let pos=0;while(from&&(pos=joined.indexOf(from,pos))>=0){hits.push(pos);pos+=from.length;}
        for(const begin of hits.reverse()){
          let cursor=0,inserted=false;
          for(const node of nodes){const text=node.textContent,start=cursor,end=cursor+text.length;cursor=end;
            if(end<=begin||start>=begin+from.length)continue;
            const lo=Math.max(0,begin-start),hi=Math.min(text.length,begin+from.length-start);
            node.textContent=text.slice(0,lo)+(inserted?'':to)+text.slice(hi);node.setAttribute('xml:space','preserve');inserted=true;
          }counts[k]++;
        }
      });
    }
    return {xml:new XMLSerializer().serializeToString(doc),counts};
  }


  async function buildPoaDocx(category,asin,title){
    const cfg=POA_CONFIG.templates[category];
    if(!cfg)throw new Error(`No POA master template is configured for category: ${category||'Unmapped'}.`);
    if(!asin)throw new Error('POA cannot be generated without an ASIN.');
    if(!title)throw new Error(`POA cannot be generated for ${asin}: Amazon product title is unavailable.`);
    const JSZip=await loadJsZip();
    if(!templateBuffers.has(cfg.asset)){const response=await fetch(cfg.asset);if(!response.ok)throw new Error(`POA master template could not be loaded for ${category}.`);templateBuffers.set(cfg.asset,await response.arrayBuffer());}
    const zip=await JSZip.loadAsync(templateBuffers.get(cfg.asset).slice(0));
    const sampleTitleXml=xmlEscape(cfg.sampleTitle),newTitleXml=xmlEscape(title);
    const xmlFiles=Object.keys(zip.files).filter(name=>/^word\/.+\.xml$/i.test(name));
    let asinReplacements=0,titleReplacements=0;
    for(const name of xmlFiles){
      const file=zip.file(name); if(!file)continue;
      let xml=await file.async('string');
      const before=xml;
      const result=replaceWordText(xml,[[cfg.sampleAsin,asin],[cfg.sampleTitle,title]]);
      xml=result.xml;asinReplacements+=result.counts[0];titleReplacements+=result.counts[1];
      if(xml!==before)zip.file(name,xml);
    }
    if(!asinReplacements)throw new Error(`POA template validation failed: sample ASIN was not found in the ${category} template.`);
    if(!titleReplacements)throw new Error(`POA template validation failed: sample product title was not found in the ${category} template.`);
    return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',compression:'DEFLATE'});
  }

  function getDriveToken(){
    if(driveToken&&Date.now()<driveTokenExpires)return Promise.resolve(driveToken);
    return new Promise((resolve,reject)=>{
      if(!window.google?.accounts?.oauth2)return reject(new Error('Google Identity Services is not loaded.'));
      // Build a client per request so callbacks cannot retain a settled promise.
      driveTokenClient=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_SHEETS_CLIENT_ID,scope:POA_CONFIG.driveScope,
        callback:r=>{if(r.error)return reject(new Error(r.error));driveToken=r.access_token||'';driveTokenExpires=Date.now()+Math.max(0,Number(r.expires_in||3600)-60)*1000;resolve(driveToken);},
        error_callback:e=>reject(new Error(e.message||e.type||'Drive authorization was cancelled.'))});
      driveTokenClient.requestAccessToken({prompt:''});
    });
  }
  async function driveJson(url,options={}){
    const token=await getDriveToken();
    const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${token}`,...options.headers}});
    const data=await response.json().catch(()=>({}));
    if(!response.ok){if(response.status===401){driveToken='';driveTokenExpires=0;folderCache.clear();}throw new Error(data?.error?.message||`Drive request failed (${response.status}). Enable Drive API and authorize Drive access.`);}
    return data;
  }
  async function ensureDriveFolders(category){
    if(!POA_CONFIG.templates[category])throw new Error('No POA category folder is configured.');
    const about=await driveJson('https://www.googleapis.com/drive/v3/about?fields=user(permissionId,emailAddress)');
    const owner=about.user?.permissionId||about.user?.emailAddress;
    if(!owner)throw new Error('The authorized Drive account could not be identified.');
    if(folderCache.has(`${owner}|${category}`))return folderCache.get(`${owner}|${category}`);
    async function folder(name,parent){
      const quote=v=>String(v).replace(/\\/g,'\\\\').replace(/'/g,"\\'");
      const q=`trashed = false and mimeType = 'application/vnd.google-apps.folder' and name = '${quote(name)}' and 'me' in owners${parent?` and '${quote(parent)}' in parents`:''}`;
      const found=await driveJson(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name)&pageSize=100`);
      if(found.files?.length)return found.files[0].id;
      const made=await driveJson('https://www.googleapis.com/drive/v3/files?fields=id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',...(parent?{parents:[parent]}:{})})});
      if(!made.id)throw new Error(`Drive folder could not be created: ${name}`);return made.id;
    }
    const root=await folder('WakeSuite POA Library');
    for(const name of Object.keys(POA_CONFIG.templates))folderCache.set(`${owner}|${name}`,await folder(name,root));
    return folderCache.get(`${owner}|${category}`);
  }

  async function uploadPoaToDrive(blob,fileName,folderId){
    const token=await getDriveToken();
    const boundary=`WakeSuitePoa_${Date.now()}_${Math.random().toString(36).slice(2)}`;
    const meta={name:fileName,mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',parents:[folderId]};
    const prefix=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document\r\n\r\n`;
    const suffix=`\r\n--${boundary}--`;
    const body=new Blob([prefix,blob,suffix],{type:`multipart/related; boundary=${boundary}`});
    const response=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});
    const data=await response.json().catch(()=>({}));
    if(!response.ok)throw new Error(data?.error?.message||`Drive upload failed (${response.status}).`);
    const share=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(data.id)}/permissions?sendNotificationEmail=false`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({type:'domain',domain:POA_CONFIG.domain,role:'reader',allowFileDiscovery:false})});
    if(!share.ok){
      const err=await share.json().catch(()=>({}));
      throw new Error(err?.error?.message||'POA was uploaded, but WakeSuite could not grant Wakefit link access.');
    }
    return {id:data.id,url:data.webViewLink||`https://drive.google.com/file/d/${data.id}/view`};
  }

  async function amazonTitleMap(reportDate){
    const map=new Map();
    let rows=[];
    try{
      const items=typeof idbGetReportsForDate==='function'?await idbGetReportsForDate(reportDate):[];
      const rec=(items||[]).find(x=>x.configId==='amazon_all_listings')?.record;
      rows=rec?.parsedFile?.rows||[];
    }catch(_e){}
    if(!rows.length)rows=window.wakeSuiteSessionReports?.amazon_all_listings?.parsedFile?.rows||[];
    (rows||[]).forEach(raw=>{
      const asin=clean(getRowValue(raw,'asin1'));
      const title=clean(getRowValue(raw,'item-name'));
      if(asin&&title&&!map.has(asin))map.set(asin,title);
    });
    return map;
  }

  function latestCaseForAsin(cases,asin){
    return (cases||[]).filter(c=>clean(c.asin)===asin).sort((a,b)=>String(b.lastDetected||b.firstDetected||'').localeCompare(String(a.lastDetected||a.firstDetected||'')))[0]||null;
  }

  async function ensurePoaForCase(caseRow,title){
    if(caseRow?.poaDriveUrl)return caseRow;
    if(!v7HasAction('managePoaQc'))throw new Error('POA/QC permission is required to generate and store a POA.');
    if(!caseRow?.id)throw new Error(`Suppression case was not found for ASIN ${caseRow?.asin||''}.`);
    const asin=clean(caseRow.asin),category=clean(caseRow.category);
    const cfg=POA_CONFIG.templates[category];
    if(!cfg)throw new Error(`POA category template is unavailable for ${asin} (${category||'Unmapped'}).`);
    const docx=await buildPoaDocx(category,asin,title);
    const folderId=await ensureDriveFolders(category);
    const uploaded=await uploadPoaToDrive(docx,`${asin}.docx`,folderId);
    const patch={
      poaDriveUrl:uploaded.url,
      poaDriveFileId:uploaded.id,
      poaGeneratedAt:new Date().toISOString(),
      poaGeneratedBy:window.wakeSuiteFirebase?.auth?.currentUser?.email||'',
      poaOccurrenceKey:`${asin}|${caseRow.firstSeen||caseRow.firstDetected||''}`
    };
    if(typeof window.updateSuppressionCase!=='function')throw new Error('Suppression POA storage is unavailable.');
    await window.updateSuppressionCase(caseRow.id,patch);
    const saved=(await window.loadSuppressionCases()).find(c=>c.id===caseRow.id);
    if(saved?.poaDriveFileId!==uploaded.id)throw new Error('POA uploaded but occurrence storage was not confirmed. Check POA permissions before sending.');
    Object.assign(caseRow,patch);
    return caseRow;
  }

  async function ensureSuppressionPoaLinks(rows,reportDate,{generate=true}={}){
    const suppression=(rows||[]).filter(r=>(r.issueType||'ASIN Suppression')==='ASIN Suppression').map(r=>normalizeRow(r,'amazon'));
    if(!suppression.length)return suppression;
    if(typeof window.loadSuppressionCases!=='function')throw new Error('Suppression case storage is unavailable. POA email was not generated.');
    const cases=await window.loadSuppressionCases();
    const titles=generate?await amazonTitleMap(reportDate):new Map();
    const out=[];
    for(const row of suppression){
      const asin=rowId(row,'amazon');
      let c=latestCaseForAsin((cases||[]).filter(c=>{const first=c.firstSeen||c.firstDetected||'';const resolved=c.resolvedOn||c.reactivatedDate||c.reactivatedOn||'';return first<=reportDate&&(!resolved||String(resolved).slice(0,10)>reportDate)&&(!['Closed','Reactivated'].includes(c.status)||!!resolved);}),asin);
      if(!c){if(generate)throw new Error(`Suppression case was not found for ASIN ${asin}; POA email was not generated.`);out.push({...row,poaDriveUrl:''});continue;}
      if(!c.poaDriveUrl&&generate){
        const title=titles.get(asin)||'';
        c=await ensurePoaForCase(c,title);
      }
      out.push({...row,caseId:c.id,poaDriveUrl:c.poaDriveUrl||'',poaDriveFileId:c.poaDriveFileId||''});
    }
    return out;
  }

  async function generateOrOpenPoa(caseId){
    const cases=typeof window.loadSuppressionCases==='function'?await window.loadSuppressionCases():[];
    let c=(cases||[]).find(x=>x.id===caseId);
    if(!c){showWakeSuiteToast?.('Suppression case could not be found.','error');return;}
    if(c.poaDriveUrl){window.open(c.poaDriveUrl,'_blank','noopener');return;}
    try{
      const titles=await amazonTitleMap(c.lastDetected||c.firstDetected||todayIso());
      c=await ensurePoaForCase(c,titles.get(clean(c.asin))||'');
      showWakeSuiteToast?.(`POA generated for ${c.asin}.`,'success','POA ready');
      window.open(c.poaDriveUrl,'_blank','noopener');
      await window.loadSuppressionManagement?.();
    }catch(error){showWakeSuiteToast?.(error.message,'error','POA generation failed');}
  }

  function decorateSuppressionPoa(){
    const table=document.getElementById('suppressionManagementTable');
    if(!table)return;
    const source=window.v8VisibleSuppressionCases||window.v7SuppressionCases||[];
    const byId=new Map(source.map(r=>[String(r.id),r]));
    table.querySelectorAll('tbody tr[data-case-id]').forEach(tr=>{
      if(tr.querySelector('.v9311-poa-action'))return;
      const c=byId.get(tr.dataset.caseId); if(!c)return;
      const cells=tr.querySelectorAll('td'); if(cells.length<9)return;
      const cell=cells[8];
      const btn=document.createElement('button');
      btn.className='secondary-btn v9311-poa-action';
      btn.type='button';
      btn.textContent=c.poaDriveUrl?'Open POA':'Generate POA';
      btn.style.marginTop='6px';
      btn.addEventListener('click',()=>generateOrOpenPoa(c.id));
      cell.appendChild(document.createElement('br'));
      cell.appendChild(btn);
    });
  }

  if(typeof renderSuppressionManagement==='function'){
    const baseRenderSuppressionManagement=renderSuppressionManagement;
    renderSuppressionManagement=function(...args){const result=baseRenderSuppressionManagement.apply(this,args);queueMicrotask(decorateSuppressionPoa);return result;};
    window.renderSuppressionManagement=renderSuppressionManagement;
  }

  function createWb(sheetName,rows,columns){
    const wb=XLSX.utils.book_new();
    const data=(rows||[]).map(row=>{const o={};columns.forEach(([label,getter])=>o[label]=getter(row));return o;});
    const ws=XLSX.utils.json_to_sheet(data,{header:columns.map(c=>c[0])});
    ws['!cols']=columns.map(([label])=>({wch:Math.max(12,Math.min(32,label.length+8))}));
    XLSX.utils.book_append_sheet(wb,ws,sheetName);
    return {wb,ws,data};
  }

  function amazonLiveWorkbook(rows){
    return createWb('Temp_Export_Values_Only',rows,[
      ['Category',r=>r.category||''],['Seller sku',r=>r.azSku||r.marketSku||''],['ASIN',r=>rowId(r,'amazon')],['Price',r=>Number(r.finalLivePrice??r.marketplacePrice??0)||0]
    ]).wb;
  }
  function amazonSuppressionWorkbook(rows,{includeEscalatedOn=true}={}){
    const cols=[['Category',r=>r.category||''],['ASIN',r=>rowId(r,'amazon')],['Rev Impact',r=>r.revenueAvailable===false?'Revenue Data Unavailable':roundImpact(issueImpact(r))],['POA Link',r=>r.poaDriveUrl||'']];
    if(includeEscalatedOn)cols.push(['Escalated On',r=>r.escalatedOnText||'']);
    const built=createWb('ASIN Suppression',rows,cols);
    const linkIndex=cols.findIndex(c=>c[0]==='POA Link');
    if(linkIndex>=0){
      (rows||[]).forEach((r,i)=>{
        const url=r.poaDriveUrl||''; if(!url)return;
        const address=XLSX.utils.encode_cell({r:i+1,c:linkIndex});
        if(built.ws[address])built.ws[address].l={Target:url,Tooltip:`Open POA for ${rowId(r,'amazon')}`};
      });
    }
    return built.wb;
  }
  function amazonBuyBoxWorkbook(rows){
    return createWb('Buy Box Suppression',rows,[
      ['Category',r=>r.category||''],['ASIN',r=>rowId(r,'amazon')],['WF Item SKU',r=>r.wfSku||''],['WF Price',r=>Number(r.wfPrice??0)||0],['Rev Impact',r=>r.revenueAvailable===false?'Revenue Data Unavailable':roundImpact(issueImpact(r))]
    ]).wb;
  }
  function flipkartLiveWorkbook(rows){
    return createWb('Flipkart Live Price Disparity',rows,[
      ['Category',r=>r.category||''],['FSN',r=>rowId(r,'flipkart')],['WF Item SKU',r=>r.wfSku||''],['WF Price',r=>Number(r.wfPrice??0)||0],['FK Live Price',r=>Number(r.finalLivePrice??0)||0],['Diff',r=>Number(r.livePriceDiff??0)||0]
    ]).wb;
  }
  function wbAttachment(name,wb){return {name,bytes:XLSX.write(wb,{bookType:'xlsx',type:'array'})};}

  function suppressionInlineTable(rows){
    if(!rows?.length)return '';
    return `<table style="border-collapse:collapse;margin:14px 0;font-family:Arial,sans-serif;font-size:12px"><thead><tr>`+
      `<th style="${yellowTh()}">Category</th><th style="${yellowTh()}">ASIN</th><th style="${yellowTh()}">Rev Impact / Day</th><th style="${yellowTh()}">POA</th></tr></thead><tbody>`+
      rows.map(r=>`<tr><td style="${tdStyle()}">${esc(r.category||'')}</td><td style="${tdStyle()}">${esc(rowId(r,'amazon'))}</td><td style="${tdStyle()}">${r.revenueAvailable===false?'Revenue Data Unavailable':formatImpact(issueImpact(r))}</td><td style="${tdStyle()}">${r.poaDriveUrl?`<a href="${esc(r.poaDriveUrl)}" target="_blank">${esc(rowId(r,'amazon'))}</a>`:'POA Unavailable'}</td></tr>`).join('')+
      `</tbody></table>`;
  }

  function flipkartInlineTable(rows){
    if(!rows?.length)return '';
    return `<table style="border-collapse:collapse;margin:14px 0;font-family:Arial,sans-serif;font-size:12px"><thead><tr>`+
      ['Category','FSN','WF Item SKU','WF Price','FK Live Price','Diff'].map(h=>`<th style="${yellowTh()}">${h}</th>`).join('')+`</tr></thead><tbody>`+
      rows.map(r=>`<tr><td style="${tdStyle()}">${esc(r.category||'')}</td><td style="${tdStyle()}">${esc(rowId(r,'flipkart'))}</td><td style="${tdStyle()}">${esc(r.wfSku||'')}</td><td style="${tdStyle()}">${esc(plainNumber(r.wfPrice))}</td><td style="${tdStyle()}">${esc(plainNumber(r.finalLivePrice))}</td><td style="${tdStyle()}">${esc(plainNumber(r.livePriceDiff))}</td></tr>`).join('')+
      `</tbody></table>`;
  }

  function amazonCombinedSummary(rows){
    const types=ISSUE_TYPES.amazon;
    const totalUnique=uniqueCount(rows,'amazon');
    const totalImpact=types.reduce((s,t)=>s+issueGroupImpact(rows,t),0);
    return `<table style="border-collapse:collapse;margin:14px 0;font-family:Arial,sans-serif;font-size:12px"><thead><tr><th style="${yellowTh()}">Issue</th><th style="${yellowTh()};text-align:right">No. of ASINs</th><th style="${yellowTh()};text-align:right">Revenue Impact / Day</th></tr></thead><tbody>`+
      types.map(t=>{const rr=(rows||[]).filter(r=>r.issueType===t);return `<tr><td style="${tdStyle()}">${esc(t)}</td><td style="${tdStyle()};text-align:right">${uniqueCount(rr,'amazon').toLocaleString('en-IN')}</td><td style="${tdStyle()};text-align:right">${formatImpact(issueGroupImpact(rows,t))}</td></tr>`;}).join('')+
      `<tr><td style="${tdStyle()};font-weight:700">Total</td><td style="${tdStyle()};font-weight:700;text-align:right">${totalUnique.toLocaleString('en-IN')}</td><td style="${tdStyle()};font-weight:700;text-align:right">${formatImpact(totalImpact)}</td></tr></tbody></table>`;
  }

  function signatureHtml(){
    try{const s=loadEmailState?.().signature||'';return s?`<div style="margin-top:18px">${esc(s).replace(/\n/g,'<br>')}</div>`:'<p>Regards,<br>WakeSuite</p>';}
    catch(_e){return '<p>Regards,<br>WakeSuite</p>';}
  }

  function operationalGreeting(market){
    const cfg=market==='amazon'?v7OperationalControls?.amazonPoc:v7OperationalControls?.flipkartPoc;
    return `Hi${clean(cfg?.name)?` ${esc(cfg.name)}`:''},`;
  }

  async function aptAttachment(rows,state){
    const buy=(rows||[]).filter(r=>r.issueType==='Buy Box Suppression');
    if(!buy.length)return null;
    if(!window.WakeSuiteBuyBoxApt?.buildAptWorkbook)throw new Error('Buy Box APT generator is unavailable. Email was not sent.');
    const built=await window.WakeSuiteBuyBoxApt.buildAptWorkbook(buy,{snapshots:state?.snapshot?[state.snapshot]:(state?.snapshots||[])});
    return wbAttachment(`Amazon_Buy_Box_APT_${state?.date||todayIso()}.xlsx`,built.wb);
  }

  function mimeTypeFor(name){
    const n=String(name||'').toLowerCase();
    if(n.endsWith('.docx'))return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    if(n.endsWith('.xlsx'))return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    return 'application/octet-stream';
  }
  function buildMimeMulti({to,cc=[],bcc=[],subject,html,attachments=[]}){
    const boundary=`WakeSuite9311_${Date.now()}_${Math.random().toString(36).slice(2)}`;
    const headers=[`To: ${to.join(', ')}`,cc.length?`Cc: ${cc.join(', ')}`:'',bcc.length?`Bcc: ${bcc.join(', ')}`:'',`Subject: ${v4MimeSubject(subject)}`,'MIME-Version: 1.0',`Content-Type: multipart/mixed; boundary="${boundary}"`].filter(Boolean).join('\r\n');
    let body=`${headers}\r\n\r\n--${boundary}\r\nContent-Type: text/html; charset="UTF-8"\r\nContent-Transfer-Encoding: base64\r\n\r\n${v4Utf8Base64(html)}\r\n`;
    for(const a of attachments||[]){
      if(!a?.name||!a?.bytes)continue;
      body+=`--${boundary}\r\nContent-Type: ${mimeTypeFor(a.name)}; name="${a.name}"\r\nContent-Disposition: attachment; filename="${a.name}"\r\nContent-Transfer-Encoding: base64\r\n\r\n${v4BytesToBase64(a.bytes)}\r\n`;
    }
    body+=`--${boundary}--`;
    return v4Base64Url(v4Utf8Base64(body));
  }
  async function gmailDeliver({mode='send',to,cc=[],bcc=[],subject,html,attachments=[]}){
    const token=await v4GetGmailToken();
    const actual=window.WakeSuiteRelease.clock();
    subject=subject.replace(/ \| \d{2}:\d{2} (?:AM|PM)$/,'')+` | ${actual}`;
    attachments=attachments.map(a=>({...a,name:window.WakeSuiteRelease.stampedName(a.name.replace(/_\d{2}-\d{2}-(?:AM|PM)(?=\.[^.]+$)/,''),actual)}));
    const raw=buildMimeMulti({to,cc,bcc,subject,html,attachments});
    const endpoint=mode==='draft'?'https://gmail.googleapis.com/gmail/v1/users/me/drafts':'https://gmail.googleapis.com/gmail/v1/users/me/messages/send';
    const response=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(mode==='draft'?{message:{raw}}:{raw})});
    const data=await response.json().catch(()=>({}));
    if(!response.ok)throw new Error(data?.error?.message||`Gmail API error ${response.status}`);
    return {...data,wakeSuiteDelivery:{subject,time:actual,attachmentNames:attachments.map(a=>a.name)}};
  }

  async function preparePocRows(kind,market,issueType,state){
    let rows=issueRows(kind,market,issueType);
    if(market==='amazon'&&(issueType==='ASIN Suppression'||(!issueType&&rows.some(r=>r.issueType==='ASIN Suppression')))){
      const supp=await ensureSuppressionPoaLinks(rows.filter(r=>r.issueType==='ASIN Suppression'),state.date,{generate:true});
      const byAsin=new Map(supp.map(r=>[rowId(r,'amazon'),r]));
      rows=rows.map(r=>r.issueType==='ASIN Suppression'?{...r,...(byAsin.get(rowId(r,'amazon'))||{})}:r);
    }
    return rows;
  }

  async function buildPocEmail(kind,market,issueType,state,rows){
    const d=dateText(state.date),greeting=operationalGreeting(market);
    let subject='',html='',attachments=[];
    if(kind==='internal')return null;

    if(market==='amazon'&&!issueType){
      subject=`Action Required | Amazon Daily Escalations | ${d}`;
      const supp=rows.filter(r=>r.issueType==='ASIN Suppression').map(r=>({...r,escalatedOnText:dateText(state.date)}));
      html=`<div style="font-family:Arial,sans-serif;font-size:13px"><p>${greeting}</p><p>Please find below the consolidated Amazon escalation summary for <strong>${esc(d)}</strong>.</p>${amazonCombinedSummary(rows)}${supp.length?suppressionInlineTable(supp):''}<p>Please find the attached files and take necessary actions and let us know once done.</p><p>Regards,<br>WakeSuite</p></div>`;
      const live=rows.filter(r=>r.issueType==='Live Price Disparity');
      const buy=rows.filter(r=>r.issueType==='Buy Box Suppression');
      if(live.length)attachments.push(wbAttachment(`Action Required - Amazon Live Price Disparity ${d}.xlsx`,amazonLiveWorkbook(live)));
      if(supp.length)attachments.push(wbAttachment(`Action Required - Amazon ASIN Suppression ${d}.xlsx`,amazonSuppressionWorkbook(supp,{includeEscalatedOn:true})));
      if(buy.length)attachments.push(wbAttachment(`Action Required - Amazon Buy Box Suppression ${d}.xlsx`,amazonBuyBoxWorkbook(buy)));
      if(buy.length){const apt=await aptAttachment(rows,state);if(apt)attachments.push(apt);}
      return {subject,html,attachments};
    }

    if(market==='amazon'&&issueType==='Live Price Disparity'){
      subject=`Action Required : Amazon Live Price Disparity ${d}`;
      html=`<div style="font-family:Arial,sans-serif;font-size:13px"><p>${greeting}</p><p>We identified a critical price disparity affecting <strong>${uniqueCount(rows,'amazon')} ASINs</strong> where frontend prices do not match Wakefit's pricing. Please find the attached list and prioritize correcting these listings immediately.</p>${signatureHtml()}</div>`;
      attachments=[wbAttachment(`Action Required - Amazon Live Price Disparity ${d}.xlsx`,amazonLiveWorkbook(rows))];
      return {subject,html,attachments};
    }

    if(market==='amazon'&&issueType==='ASIN Suppression'){
      subject=`Action Required : Amazon Suppressed ASINs - ${d}`;
      html=`<div style="font-family:Arial,sans-serif;font-size:13px"><p>${greeting}</p><p>Please reinstate these ASINs at the earliest. Let us know once the tickets are raised.</p>${suppressionInlineTable(rows)}${signatureHtml()}</div>`;
      return {subject,html,attachments:[]};
    }

    if(market==='amazon'&&issueType==='Buy Box Suppression'){
      subject=`Action Required : Amazon Buy Box Suppression - ${d}`;
      html=`<div style="font-family:Arial,sans-serif;font-size:13px"><p>${greeting}</p><p>Please find the Buy Box suppressed ASINs requiring action. The report and APT are attached.</p><p><strong>No. of ASINs: ${uniqueCount(rows,'amazon')}</strong></p>${signatureHtml()}</div>`;
      attachments=[wbAttachment(`Action Required - Amazon Buy Box Suppression ${d}.xlsx`,amazonBuyBoxWorkbook(rows))];
      {const apt=await aptAttachment(rows,state);if(apt)attachments.push(apt);}
      return {subject,html,attachments};
    }

    if(market==='flipkart'){
      subject=`Action Required : Flipkart Price Disparity - ${d}${kind==='followup'?' Follow-Up':''}`;
      html=`<div style="font-family:Arial,sans-serif;font-size:13px"><p>${greeting}</p><p>Please update the prices for the FSNs showing a disparity on the front end.</p>${flipkartInlineTable(rows)}${signatureHtml()}</div>`;
      return {subject,html,attachments:[]};
    }

    return null;
  }

  const baseSendDailyCommunication=typeof sendDailyCommunication==='function'?sendDailyCommunication:null;
  async function sendDailyCommunication9311(kind,market,issueType=''){
    return window.WakeSuiteRelease.sendCommunication(kind,market,issueType);
    const state=v7CommunicationsState; if(!state)return;
    if(!v7HasAction('pocEscalation')){showWakeSuiteToast('POC Escalation permission is required.','warning');return;}
    if(!v7HasAction('email')){showWakeSuiteToast('Email permission is required.','warning');return;}
    let rows=[];
    try{rows=await preparePocRows(kind,market,issueType,state);}catch(error){showWakeSuiteToast(error.message,'error','POA preparation failed');return;}
    if(!rows.length){showWakeSuiteToast('No issues are ready for this communication.','info');return;}
    const cfg=market==='amazon'?v7OperationalControls.amazonPoc:v7OperationalControls.flipkartPoc;
    const to=v7Unique([cfg?.email,...v7SplitEmails(cfg?.additional)]);
    if(!to.length){showWakeSuiteToast('Recipients are not configured in Settings → System → Operational Controls.','warning');return;}
    try{
      const message=await buildPocEmail(kind,market,issueType,state,rows);
      if(!message)throw new Error('Communication format is unavailable.');
      await gmailDeliver({mode:'send',to,subject:message.subject,html:message.html,attachments:message.attachments});
      await window.recordPocEscalations(rows,state.date);
      const type=issueType?`${kind==='poc'?'POC Escalation':'POC Follow-Up'} · ${issueType}`:(kind==='poc'?'POC Escalation':'POC Follow-Up');
      await window.saveCommunicationLog({reportDate:state.date,communicationType:type,marketplace:market,recipients:to,status:'Sent',issueType:issueType||'',issueCount:rows.length,uniqueIdentifierCount:uniqueCount(rows,market)});
      showWakeSuiteToast(`${type} sent successfully.`,'success');
      await loadDailyCommunications();
    }catch(error){showWakeSuiteToast(error.message,'error','POC email failed');}
  }

  function downloadDailyCommunication9311(kind,market,issueType=''){
    const state=v7CommunicationsState;if(!state)return;
    if(!v7HasAction('download')){showWakeSuiteToast('Download permission is required.','warning');return;}
    const rows=kind==='internal'?[]:issueRows(kind,market,issueType);
    if(kind!=='internal'&&!rows.length){showWakeSuiteToast('No rows are available to download.','info');return;}
    if(kind==='internal')return window.WakeSuiteRelease.downloadInternal(state);
    const d=dateText(state.date);
    if(market==='amazon'&&issueType==='Live Price Disparity')return XLSX.writeFile(amazonLiveWorkbook(rows),`Action Required - Amazon Live Price Disparity ${d}.xlsx`);
    if(market==='amazon'&&issueType==='ASIN Suppression')return ensureSuppressionPoaLinks(rows,state.date,{generate:false}).then(rr=>XLSX.writeFile(amazonSuppressionWorkbook(rr.map(r=>({...r,escalatedOnText:d})),{includeEscalatedOn:true}),`Action Required - Amazon ASIN Suppression ${d}.xlsx`));
    if(market==='amazon'&&issueType==='Buy Box Suppression')return XLSX.writeFile(amazonBuyBoxWorkbook(rows),`Action Required - Amazon Buy Box Suppression ${d}.xlsx`);
    if(market==='flipkart')return XLSX.writeFile(flipkartLiveWorkbook(rows),`Flipkart Live Price Disparity - ${d}.xlsx`);
    const wb=v7CommunicationWorkbook(kind,market,rows,state);
    XLSX.writeFile(wb,`WakeSuite_${marketName(market)}_${kind}_${state.date}.xlsx`);
  }

  // Report-page download: preserve the reference report structures.
  if(typeof downloadHistoricalModule==='function'){
    const baseDownloadHistoricalModule=downloadHistoricalModule;
    downloadHistoricalModule=async function(){
      const report=currentHistoricalReport,viewKey=report?.viewKey||currentHistoricalViewKey;
      if(!report||!['amazon_live','amazon_suppression','amazon_buybox','flipkart_live'].includes(viewKey))return baseDownloadHistoricalModule.apply(this,arguments);
      if(!v7HasAction('download')){showWakeSuiteToast?.('Download permission is required.','warning');return;}
      return window.WakeSuiteRelease.downloadVisibleReport(report);
      let rows=(typeof v4EmailIssueRows==='function'?v4EmailIssueRows(report):(report.rows||[])).map(r=>normalizeRow(r,report.def.marketplace));
      if(!rows.length){showWakeSuiteToast?.('No rows are available to download.','info');return;}
      const d=v4FormatEmailDate(report.fromDate,report.toDate);
      if(viewKey==='amazon_live')return XLSX.writeFile(amazonLiveWorkbook(rows),`Amazon Live Price Disparity ${d}.xlsx`);
      if(viewKey==='amazon_suppression'){
        rows=await ensureSuppressionPoaLinks(rows,report.toDate||report.fromDate||todayIso(),{generate:false});
        rows=rows.map(r=>({...r,escalatedOnText:dateText(report.toDate||report.fromDate)}));
        return XLSX.writeFile(amazonSuppressionWorkbook(rows,{includeEscalatedOn:true}),`Amazon Suppressed ASINs List - ${d}.xlsx`);
      }
      if(viewKey==='amazon_buybox')return XLSX.writeFile(amazonBuyBoxWorkbook(rows),`Amazon Buy Box Suppression - ${d}.xlsx`);
      if(viewKey==='flipkart_live')return XLSX.writeFile(flipkartLiveWorkbook(rows),`Flipkart Live Price Disparity - ${d}.xlsx`);
    };
    window.downloadHistoricalModule=downloadHistoricalModule;
  }

  function individualSubject(viewKey,d){
    if(viewKey==='amazon_live')return `Action Required : Amazon Live Price Disparity ${d}`;
    if(viewKey==='amazon_suppression')return `Action Required : Amazon Suppressed ASINs - ${d}`;
    if(viewKey==='amazon_buybox')return `Action Required : Amazon Buy Box Suppression - ${d}`;
    if(viewKey==='flipkart_live')return `Action Required : Flipkart Price Disparity - ${d}`;
    return '';
  }
  async function prepareIndividualPackage(report,viewKey){
    let rows=(typeof v4EmailIssueRows==='function'?v4EmailIssueRows(report):(report.rows||[])).map(r=>normalizeRow(r,report.def.marketplace));
    if(!rows.length)throw new Error('No report rows match the selected period and filters.');
    const d=v4FormatEmailDate(report.fromDate,report.toDate),template={...(loadEmailState?.().templates?.[viewKey]||{})};
    let html='',attachments=[],messageText='';
    const greeting=clean(template.greeting)?`<div style="margin-bottom:12px">${esc(v4ReplaceEmailVars(template.greeting,v4EmailVariableContext(report)))}</div>`:'';
    const sig=signatureHtml();
    if(viewKey==='amazon_live'){
      messageText=`We identified a critical price disparity affecting ${uniqueCount(rows,'amazon')} ASINs where frontend prices do not match Wakefit's pricing. Please find the attached list and prioritize correcting these listings immediately.`;
      html=`<div style="font-family:Arial,sans-serif;font-size:13px">${greeting}<p>${esc(messageText)}</p>${sig}</div>`;
      attachments=[wbAttachment(`Amazon Live Price Disparity ${d}.xlsx`,amazonLiveWorkbook(rows))];
    }else if(viewKey==='amazon_suppression'){
      rows=await ensureSuppressionPoaLinks(rows,report.toDate||report.fromDate||todayIso(),{generate:true});
      messageText='Please reinstate these ASINs at the earliest. Let us know once the tickets are raised.';
      html=`<div style="font-family:Arial,sans-serif;font-size:13px">${greeting}<p>${esc(messageText)}</p>${suppressionInlineTable(rows)}${sig}</div>`;
    }else if(viewKey==='amazon_buybox'){
      messageText='Please find the Buy Box suppressed ASINs requiring action. The Buy Box report and APT are attached.';
      html=`<div style="font-family:Arial,sans-serif;font-size:13px">${greeting}<p>${esc(messageText)}</p><p><strong>No. of ASINs: ${uniqueCount(rows,'amazon')}</strong></p>${sig}</div>`;
      attachments=[wbAttachment(`Amazon Buy Box Suppression - ${d}.xlsx`,amazonBuyBoxWorkbook(rows))];
      if(!window.WakeSuiteBuyBoxApt?.buildAptWorkbook)throw new Error('Buy Box APT generator is unavailable.');
      const built=await window.WakeSuiteBuyBoxApt.buildAptWorkbook(rows,{snapshots:report.snapshots||[]});
      attachments.push(wbAttachment(`Amazon_Buy_Box_APT_${report.toDate||report.fromDate||todayIso()}.xlsx`,built.wb));
    }else if(viewKey==='flipkart_live'){
      messageText='Please update the prices for the FSNs showing a disparity on the front end.';
      html=`<div style="font-family:Arial,sans-serif;font-size:13px">${greeting}<p>${esc(messageText)}</p>${flipkartInlineTable(rows)}${sig}</div>`;
    }
    return {rows,template,subject:individualSubject(viewKey,d),html,attachments,messageText,greetingHtml:greeting,signatureHtml:sig,extraHtml:viewKey==='amazon_suppression'?suppressionInlineTable(rows):(viewKey==='flipkart_live'?flipkartInlineTable(rows):(viewKey==='amazon_buybox'?`<p><strong>No. of ASINs: ${uniqueCount(rows,'amazon')}</strong></p>`:''))};
  }

  if(typeof openShareEmailModal==='function'){
    const baseOpenShareEmailModal=openShareEmailModal;
    openShareEmailModal=async function(){
      if(!currentHistoricalReport)await loadHistoricalModule();
      const report=currentHistoricalReport,viewKey=report?.viewKey||currentHistoricalViewKey;
      if(!report||!['amazon_live','amazon_suppression','amazon_buybox','flipkart_live'].includes(viewKey))return baseOpenShareEmailModal.apply(this,arguments);
      try{
        const pkg=await window.WakeSuiteRelease.prepareReportPackage(report,viewKey);
        const template=pkg.template||{};
        currentShareEmailPackage={report,template,html:pkg.html,attachExcel:false,attachmentName:null,v9311:{attachments:pkg.attachments,html:pkg.html,viewKey,messageText:pkg.messageText,greetingHtml:pkg.greetingHtml,extraHtml:pkg.extraHtml,signatureHtml:pkg.signatureHtml}};
        const set=(id,v)=>{const el=document.getElementById(id);if(el)el.value=v||'';};
        set('shareEmailTo',template.to);set('shareEmailCc',template.cc);set('shareEmailBcc',template.bcc);set('shareEmailSubject',pkg.subject);set('shareEmailMessage',pkg.messageText);
        finalSetText('shareEmailAttachmentName',pkg.attachments.length?`Attachments · ${pkg.attachments.map(a=>a.name).join(' · ')}`:'No attachment · report is inline in the email');
        const preview=document.getElementById('shareEmailPreview');if(preview)preview.innerHTML=pkg.html;
        const modal=document.getElementById('emailShareModal');modal?.classList.add('open');if(modal)modal.setAttribute('aria-hidden','false');
      }catch(error){showWakeSuiteToast?.(error.message,'error','Unable to prepare email');}
    };
    window.openShareEmailModal=openShareEmailModal;
  }

  if(typeof sendCurrentReportEmail==='function'){
    const baseSendCurrentReportEmail=sendCurrentReportEmail;
    sendCurrentReportEmail=async function(mode='send'){
      const custom=currentShareEmailPackage?.v9311;
      if(!custom)return baseSendCurrentReportEmail.apply(this,arguments);
      const to=v4ResolveRecipientTokens(document.getElementById('shareEmailTo')?.value),cc=v4ResolveRecipientTokens(document.getElementById('shareEmailCc')?.value),bcc=v4ResolveRecipientTokens(document.getElementById('shareEmailBcc')?.value),subject=clean(document.getElementById('shareEmailSubject')?.value);
      if(!to.length){alert('Add at least one recipient.');return;}if(!subject){alert('Add an email subject.');return;}
      const button=document.getElementById(mode==='draft'?'createGmailDraftButton':'sendGmailButton');if(button)button.disabled=true;
      try{
        const editedMessage=document.getElementById('shareEmailMessage')?.value??custom.messageText??'';
        const editedHtml=`<div style="font-family:Arial,sans-serif;font-size:13px">${custom.greetingHtml||''}<p>${esc(editedMessage).replace(/\n/g,'<br>')}</p>${custom.extraHtml||''}${custom.signatureHtml||''}</div>`;
        const stamped=window.WakeSuiteRelease.stampMessage({subject,html:editedHtml,attachments:custom.attachments});
        const data=await gmailDeliver({mode,to,cc,bcc,...stamped});
        v4SaveEmailHistory?.({sentAt:new Date().toLocaleString(),report:currentShareEmailPackage.report.def.title,period:`${currentShareEmailPackage.report.fromDate} to ${currentShareEmailPackage.report.toDate}`,to:to.join(', '),subject,mode:mode==='draft'?'Gmail Draft':'Sent',status:'Success',gmailId:data.id||data.message?.id||''});
        alert(mode==='draft'?'Gmail draft created.':'Email sent.');closeShareEmailModal();
      }catch(error){alert(`Email sharing failed: ${error.message}`);}finally{if(button)button.disabled=false;}
    };
    window.sendCurrentReportEmail=sendCurrentReportEmail;
  }

  function renderDailyCommunications9311(){
    const state=v7CommunicationsState,cards=document.getElementById('communicationsCards'),history=document.getElementById('communicationsHistoryTable');if(!state||!cards)return;
    const canPoc=v7HasAction('pocEscalation')&&v7HasAction('email'),canDownload=v7HasAction('download'),canEmail=v7HasAction('email');
    const sent=(type,market)=>(state.logs||[]).find(l=>l.communicationType===type&&l.marketplace===market&&l.status==='Sent');
    function card({title,rows=[],meta,kind,market,issueType='',internal=false,showDownload=true}){
      const count=internal?Object.values(state.issues.internal).reduce((a,r)=>a+r.length,0):uniqueCount(rows,market),type=internal?'Daily Marketplace Report':(issueType?`${kind==='poc'?'POC Escalation':'POC Follow-Up'} · ${issueType}`:(kind==='poc'?'POC Escalation':'POC Follow-Up')),sentLog=sent(type,market),disabled=internal?!canEmail:(!canPoc||!rows.length);
      return `<div class="communication-card"><h3>${esc(title)}</h3><div class="communication-count">${formatNumber(count)}</div><div class="communication-meta">${esc(sentLog?`Sent ${sentLog.sentAtText||''} by ${sentLog.sentBy||''}`:`${meta} · ${count} ${internal?'issue rows':identifierLabel(market)}`)}</div><div class="communication-actions">${showDownload?`<button class="secondary-btn" onclick="downloadDailyCommunication('${kind}','${market}','${esc(issueType)}')" ${(!canDownload||(!internal&&!rows.length))?'disabled':''}>Download</button>`:''}<button class="primary-btn" onclick="sendDailyCommunication('${kind}','${market}','${esc(issueType)}')" ${disabled?'disabled':''}>${internal?'Send Internal Report':issueType?'Email Separately':kind==='poc'?'Send All to POC':'Send Follow-Up'}</button></div></div>`;
    }
    let html='';
    html+=card({title:'Amazon POC Escalation',rows:issueRows('poc','amazon'),meta:'Consolidated Live Disparity, ASIN Suppression and Buy Box escalation',kind:'poc',market:'amazon'});
    for(const type of ISSUE_TYPES.amazon)html+=card({title:`Amazon · ${type}`,rows:issueRows('poc','amazon',type),meta:'Individual Amazon POC escalation',kind:'poc',market:'amazon',issueType:type});
    html+=card({title:'Amazon POC Follow-Up',rows:state.amazon.follow,meta:'Previously escalated Amazon issues still unresolved',kind:'followup',market:'amazon'});
    html+=card({title:'Flipkart POC Escalation',rows:issueRows('poc','flipkart'),meta:'Category-specific Flipkart POC email and attachment',kind:'poc',market:'flipkart',showDownload:true});
    for(const type of ISSUE_TYPES.flipkart)html+=card({title:`Flipkart · ${type}`,rows:issueRows('poc','flipkart',type),meta:'Category-specific actionable Flipkart rows',kind:'poc',market:'flipkart',issueType:type,showDownload:true});
    html+=card({title:'Flipkart POC Follow-Up',rows:state.flipkart.follow,meta:'Previously escalated Flipkart issues still unresolved',kind:'followup',market:'flipkart',showDownload:true});
    html+=card({title:'Daily Marketplace Report',meta:'Internal Amazon + Flipkart actionable report',kind:'internal',market:'combined',internal:true});
    cards.innerHTML=html;
    const logs=state.logs||[];finalSetText('communicationsHistoryCount',String(logs.length));if(history)history.innerHTML=logs.length?'<thead><tr><th>Type</th><th>Marketplace</th><th>Escalation</th><th>Sent At</th><th>Sent By</th><th>Recipients</th><th>Status</th></tr></thead><tbody>'+logs.map(l=>`<tr><td>${esc(l.communicationType)}</td><td>${esc(l.marketplace)}</td><td>${l.escalationNumber||'—'}</td><td>${esc(l.sentAtText||'')}</td><td>${esc(l.sentBy||'')}</td><td>${esc((l.recipients||[]).join(', '))}</td><td>${v7HtmlStatus(l.status)}</td></tr>`).join('')+'</tbody>':'<tbody><tr><td class="empty-row">No communications sent for this date.</td></tr></tbody>';
  }

  sendDailyCommunication=sendDailyCommunication9311;
  renderDailyCommunications=renderDailyCommunications9311;
  window.sendDailyCommunication=sendDailyCommunication9311;
  window.renderDailyCommunications=renderDailyCommunications9311;
  window.downloadDailyCommunication=downloadDailyCommunication9311;
  window.generateOrOpenPoa=generateOrOpenPoa;
  window.WakeSuiteV9311={POA_CONFIG,roundImpact,formatImpact,issueRows,buildPocEmail,gmailDeliver,preparePocRows,wbAttachment,signatureHtml,createWb,ensureDriveFolders,replaceWordText,ensureSuppressionPoaLinks,buildPoaDocx,amazonLiveWorkbook,amazonSuppressionWorkbook,amazonBuyBoxWorkbook,flipkartLiveWorkbook,suppressionInlineTable,flipkartInlineTable,amazonCombinedSummary,buildMimeMulti};
})();
