/* WakeSuite V9.3.5 · Reporting, disparity value, suppression follow-up and FBA holding-risk extension */
(function(){
'use strict';
const VERSION='9.3.5';
const esc=v=>typeof escapeHtml==='function'?escapeHtml(v??''):String(v??'');
const n=v=>{const x=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:0;};
const round=v=>Math.round(n(v));
const money=v=>`₹${round(v).toLocaleString('en-IN')}`;
const uniq=a=>Array.from(new Set((a||[]).filter(Boolean)));
const shift=(iso,days)=>{const d=new Date(`${iso}T00:00:00`);d.setDate(d.getDate()+days);return typeof localIsoDate==='function'?localIsoDate(d):d.toISOString().slice(0,10);};
const today=()=>typeof todayIso==='function'?todayIso():new Date().toISOString().slice(0,10);
const daysBetween=(a,b)=>Math.max(0,Math.floor((new Date(`${b}T00:00:00`)-new Date(`${a}T00:00:00`))/86400000));
let periodicState=null;

function currentControls(){
  const base=typeof v7OperationalControls!=='undefined'?v7OperationalControls:{};
  return {...base,holdingRisk:{watchDays:7,slowDays:14,nonMovingDays:30,targetCover:30,...(base.holdingRisk||{})},poaDrive:{endpoint:'',folderId:'',...(base.poaDrive||{})}};
}
function latestDateText(){return document.getElementById('latestCompletedDateDisplay')?.textContent?.replace(/^As of\s+/,'').trim()||today();}
function canonicalAmazonPriceMap(){
  const map=new Map();
  try{const p=prepareAmazonMasterPricing?.();for(const [k,v] of p?.masterMap||[]){if(k)map.set(String(k),v);if(v?.asin)map.set(`asin:${v.asin}`,v);if(v?.wfSku)map.set(`wf:${v.wfSku}`,v);}}catch(_e){}
  try{for(const v of window.masterPricingAmazon?.rows||[]){if(v.azSku)map.set(String(v.azSku),v);if(v.asin)map.set(`asin:${v.asin}`,v);if(v.wfSku)map.set(`wf:${v.wfSku}`,v);}}catch(_e){}
  return map;
}
function fillBuyBoxPrice(row){
  if(row.issueType!=='Buy Box Suppression')return row;
  const map=canonicalAmazonPriceMap();const m=map.get(String(row.azSku||''))||map.get(`asin:${row.asin||row.productId||''}`)||map.get(`wf:${row.wfSku||''}`)||{};
  const p=n(m.wfPrice||m.price||row.wfPrice);return {...row,wfPrice:p>0?p:null};
}
function normalizeImpactRow(r){return {...fillBuyBoxPrice(r),revenueImpactPerDay:round(r.revenueImpactPerDay),liveDailyRevenueImpact:round(r.liveDailyRevenueImpact),buyBoxRevenueImpactPerDay:round(r.buyBoxRevenueImpactPerDay)};}

async function loadRange(from,to){return typeof v4LoadSnapshotsForRange==='function'?await v4LoadSnapshotsForRange(from,to):[];}
function snapshotRows(s,market){return market==='amazon'?(getSnapshotAmazonRows?.(s)||[]):(getSnapshotFlipkartRows?.(s)||[]);}
function livePrice(r){return n(r.finalLivePrice||r.livePrice||r.listingPrice);}
function parityState(r){
  const hasActionable=!!(r.listingPriceDisparity||r.livePriceDisparity||r.mrpDisparity);
  const hasException=!hasActionable&&!!(r.rawLivePriceDisparity||r.rawListingPriceDisparity||r.rawMrpDisparity||r.livePriceException||r.listingPriceException||r.mrpException);
  return hasException?'exception':hasActionable?'disparity':'parity';
}
function parityPct(rows){const p=rows.filter(r=>parityState(r)==='parity').length,d=rows.filter(r=>parityState(r)==='disparity').length;return p+d?p/(p+d)*100:0;}
async function orderRows(){return window.WakeSuiteV933?.loadOrders?await window.WakeSuiteV933.loadOrders():[];}
function orderIdentity(o){return o.marketplace==='amazon'?String(o.asin||o.azSku||o.wfSku):String(o.fsn||o.fkSku||o.wfSku);}

async function disparityImpact(from,to){
  const [snaps,orders]=await Promise.all([loadRange(from,to),orderRows()]);
  const active=new Map();
  for(const s of snaps){
    for(const market of ['amazon','flipkart'])for(const r of snapshotRows(s,market)){
      if(!r.rawLivePriceDisparity)continue;
      const id=market==='amazon'?(r.asin||r.azSku||r.wfSku):(r.fsn||r.fkSku||r.wfSku);if(!id)continue;
      const key=`${market}|${id}|${s.reportDate}`;
      active.set(key,{marketplace:market,date:s.reportDate,identifier:id,wfSku:r.wfSku||'',marketSku:market==='amazon'?(r.azSku||''):(r.fkSku||''),category:r.category||'Unmapped',actionable:!!r.livePriceDisparity,exceptionExcluded:!r.livePriceDisparity,impact:round(r.liveDailyRevenueImpact||r.dailyRevenueImpact),livePrice:livePrice(r)});
    }
  }
  const idx=new Map();for(const o of orders){if(o.date<from||o.date>to)continue;const k=`${o.marketplace}|${orderIdentity(o)}|${o.date}`;if(!idx.has(k))idx.set(k,[]);idx.get(k).push(o);}
  const grouped=new Map();
  for(const x of active.values()){
    const gk=`${x.marketplace}|${x.identifier}`;const g=grouped.get(gk)||{marketplace:x.marketplace,identifier:x.identifier,wfSku:x.wfSku,marketSku:x.marketSku,category:x.category,actionableDays:0,excludedDays:0,orders:new Set(),units:0,orderRevenue:0,orderValueAtLivePrice:0,revenueImpact:0};
    if(x.exceptionExcluded){g.excludedDays++;grouped.set(gk,g);continue;}
    g.actionableDays++;g.revenueImpact+=x.impact;
    for(const o of idx.get(`${x.marketplace}|${x.identifier}|${x.date}`)||[]){if(o.orderId)g.orders.add(o.orderId);g.units+=n(o.units);if(x.marketplace==='amazon')g.orderRevenue+=n(o.revenue);else g.orderValueAtLivePrice+=n(o.units)*x.livePrice;}
    grouped.set(gk,g);
  }
  return [...grouped.values()].map(g=>({...g,orders:g.orders.size,orderRevenue:round(g.orderRevenue),orderValueAtLivePrice:round(g.orderValueAtLivePrice),revenueImpact:round(g.revenueImpact)}));
}

async function fbaHoldingRisk(anchor=latestDateText()){
  const cfg=currentControls().holdingRisk;const from=shift(anchor,-59);const [snaps,orders]=await Promise.all([loadRange(anchor,anchor),orderRows()]);const s=snaps.find(x=>x.reportDate===anchor)||snaps.at(-1);if(!s)return[];
  const fbaOrders=orders.filter(o=>o.marketplace==='amazon'&&String(o.fulfillment||'').toUpperCase()==='FBA'&&o.date>=from&&o.date<=anchor);
  return snapshotRows(s,'amazon').filter(r=>n(r.inventory)>0).map(r=>{
    const id=String(r.asin||r.azSku||r.wfSku||'');const os=fbaOrders.filter(o=>orderIdentity(o)===id||(!o.asin&&o.azSku===r.azSku));
    const units=(d)=>os.filter(o=>o.date>=shift(anchor,-d+1)).reduce((a,o)=>a+n(o.units),0);const u7=units(7),u14=units(14),u30=units(30);const last=os.map(o=>o.date).sort().at(-1)||'';const since=last?daysBetween(last,anchor):60;const drr=u30/30;const inv=n(r.inventory);const cover=drr>0?inv/drr:null;const excess=Math.max(0,Math.round(inv-drr*n(cfg.targetCover||30)));
    let status='Active';if(u30===0&&since>=n(cfg.nonMovingDays||30))status='Non-Moving';else if(since>=n(cfg.slowDays||14)||(cover!=null&&cover>90))status='Slow Moving';else if(since>=n(cfg.watchDays||7)||(cover!=null&&cover>n(cfg.targetCover||30)*1.5))status='Watch';
    const related=[r.suppressionStatus&&/supp/i.test(String(r.suppressionStatus))?'Suppression':'',r.buyBoxStatus&&/supp|lost|no buy/i.test(String(r.buyBoxStatus))?'Buy Box':'',r.livePriceDisparity?'Live Price Disparity':'',r.livePriceException?'Pricing Exception':''].filter(Boolean);
    const attention=status==='Non-Moving'?'Review pricing / suppression / Buy Box before replenishment':status==='Slow Moving'?'Review replenishment and pricing':status==='Watch'?'Monitor movement':'Normal';
    return {marketplace:'Amazon',category:r.category||'Unmapped',asin:r.asin||'',wfSku:r.wfSku||'',azSku:r.azSku||'',fbaInventory:inv,units7:u7,units14:u14,units30:u30,drr30:drr,lastFbaSale:last||'No sale in observed period',daysSinceSale:since,daysCover:cover,excessFbaUnits:excess,status,relatedIssues:related.join(' / ')||'None',attention};
  });
}
function renderHoldingPanel(rows){
  const host=document.getElementById('businessInsightsContent');if(!host)return;let p=document.getElementById('ws935HoldingPanel');if(!p){p=document.createElement('div');p.id='ws935HoldingPanel';p.className='analytics-card ws935-holding-panel';host.appendChild(p);}const non=rows.filter(r=>r.status==='Non-Moving'),slow=rows.filter(r=>r.status==='Slow Moving'),watch=rows.filter(r=>r.status==='Watch');
  p.innerHTML=`<div class="analytics-card-head"><div><strong>Amazon FBA Holding Risk</strong><div class="v7-muted">Amazon FBA-only. Identifies stock sitting without sufficient recent FBA sales; storage-fee ₹ estimates are intentionally excluded.</div></div></div><div class="v93-kpi-grid"><div class="v93-kpi"><span>Non-Moving SKUs</span><strong>${non.length}</strong></div><div class="v93-kpi"><span>Slow-Moving SKUs</span><strong>${slow.length}</strong></div><div class="v93-kpi"><span>Watch SKUs</span><strong>${watch.length}</strong></div><div class="v93-kpi"><span>FBA Units at Risk</span><strong>${[...non,...slow].reduce((a,r)=>a+r.fbaInventory,0).toLocaleString('en-IN')}</strong></div><div class="v93-kpi"><span>Excess FBA Units</span><strong>${rows.reduce((a,r)=>a+r.excessFbaUnits,0).toLocaleString('en-IN')}</strong></div></div><div class="table-wrap"><table class="result-table"><thead><tr><th>Category</th><th>ASIN</th><th>WF SKU</th><th>FBA Inventory</th><th>7D Units</th><th>14D Units</th><th>30D Units</th><th>30D DRR</th><th>Last FBA Sale</th><th>Days Since Sale</th><th>Days Cover</th><th>Excess FBA Units</th><th>Holding Risk</th><th>Related Issues</th><th>Recommended Attention</th></tr></thead><tbody>${rows.sort((a,b)=>({"Non-Moving":3,"Slow Moving":2,"Watch":1,"Active":0}[b.status]-({"Non-Moving":3,"Slow Moving":2,"Watch":1,"Active":0}[a.status]))).slice(0,1500).map(r=>`<tr><td>${esc(r.category)}</td><td>${esc(r.asin)}</td><td>${esc(r.wfSku)}</td><td>${r.fbaInventory}</td><td>${r.units7}</td><td>${r.units14}</td><td>${r.units30}</td><td>${r.drr30.toFixed(2)}</td><td>${esc(r.lastFbaSale)}</td><td>${r.daysSinceSale}</td><td>${r.daysCover==null?'—':r.daysCover.toFixed(1)}</td><td>${r.excessFbaUnits}</td><td><span class="ws935-risk ${r.status.toLowerCase().replace(/\s+/g,'-')}">${esc(r.status)}</span></td><td>${esc(r.relatedIssues)}</td><td>${esc(r.attention)}</td></tr>`).join('')||'<tr><td colspan="15" class="empty-row">No FBA inventory holding-risk rows.</td></tr>'}</tbody></table></div>`;
}

function periodRange(){const c=document.getElementById('periodicReportCadence')?.value||'weekly';const anchor=document.getElementById('periodicReportAnchor')?.value||latestDateText();if(c==='monthly'){const d=new Date(`${anchor}T00:00:00`);const from=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;const end=new Date(d.getFullYear(),d.getMonth()+1,0);const to=typeof localIsoDate==='function'?localIsoDate(end):end.toISOString().slice(0,10);return[c,from,to,anchor];}return[c,shift(anchor,-6),anchor,anchor];}
async function buildPeriodic(){
  const [cadence,from,to,anchor]=periodRange();const [snaps,impact,holding,cases]=await Promise.all([loadRange(from,to),disparityImpact(from,to),fbaHoldingRisk(to),window.loadSuppressionCases?.().catch?.(()=>[])||[]]);
  const daily=[];for(const s of snaps){const ar=snapshotRows(s,'amazon'),fr=snapshotRows(s,'flipkart');daily.push({date:s.reportDate,amazonParity:parityPct(ar),flipkartParity:parityPct(fr),amazonDisparity:ar.filter(r=>r.livePriceDisparity).length,flipkartDisparity:fr.filter(r=>r.livePriceDisparity).length,amazonImpact:round(ar.reduce((a,r)=>a+n(r.livePriceDisparity?r.liveDailyRevenueImpact:0),0)),flipkartImpact:round(fr.reduce((a,r)=>a+n(r.livePriceDisparity?r.liveDailyRevenueImpact:0),0))});}
  const byMarket=m=>impact.filter(r=>r.marketplace===m);const sum=(arr,k)=>arr.reduce((a,r)=>a+n(r[k]),0);const az=byMarket('amazon'),fk=byMarket('flipkart');
  const latest=snaps.slice().sort((a,b)=>String(a.reportDate).localeCompare(String(b.reportDate))).at(-1);const azLatest=latest?snapshotRows(latest,'amazon'):[],fkLatest=latest?snapshotRows(latest,'flipkart'):[];
  const suppression=(cases||[]).filter(c=>String(c.firstDetected||'')<=to&&String(c.lastDetected||'')>=from);const buyBoxCount=(latest?getSnapshotAmazonIssueRows(latest,'amazonBuyBox')||[]:[]).length;
  periodicState={cadence,from,to,anchor,snaps,daily,impact,holding,cases,summary:{amazon:{priceParity:parityPct(azLatest),liveDisparity:az.length,revenueImpact:sum(az,'revenueImpact'),orders:sum(az,'orders'),units:sum(az,'units'),orderRevenue:sum(az,'orderRevenue'),suppression:suppression.length,buyBox:buyBoxCount,nonMoving:holding.filter(r=>r.status==='Non-Moving').length,slowMoving:holding.filter(r=>r.status==='Slow Moving').length,excessFba:sum(holding,'excessFbaUnits')},flipkart:{priceParity:parityPct(fkLatest),liveDisparity:fk.length,revenueImpact:sum(fk,'revenueImpact'),orders:sum(fk,'orders'),units:sum(fk,'units'),orderValueAtLivePrice:sum(fk,'orderValueAtLivePrice')}}};return periodicState;
}
function audienceSummary(aud){const s=periodicState.summary;if(aud==='amazon')return {Amazon:s.amazon};if(aud==='flipkart')return {Flipkart:s.flipkart};return {Amazon:s.amazon,Flipkart:s.flipkart};}
function renderPeriodic(){const st=periodicState;if(!st)return;const a=st.summary.amazon,f=st.summary.flipkart;document.getElementById('periodicReportInfo').textContent=`${st.cadence==='weekly'?'Weekly':'Monthly'} report · ${st.from} to ${st.to} · latest completed data ${st.snaps.at(-1)?.reportDate||'—'}`;const k=document.getElementById('periodicReportKpis');if(k)k.innerHTML=`<div class="v93-kpi"><span>Amazon Price Parity</span><strong>${a.priceParity.toFixed(1)}%</strong></div><div class="v93-kpi"><span>Flipkart Price Parity</span><strong>${f.priceParity.toFixed(1)}%</strong></div><div class="v93-kpi"><span>Live Disparity Rev Impact</span><strong>${money(a.revenueImpact+f.revenueImpact)}</strong></div><div class="v93-kpi"><span>Orders During Disparity</span><strong>${(a.orders+f.orders).toLocaleString('en-IN')}</strong></div><div class="v93-kpi"><span>Units During Disparity</span><strong>${(a.units+f.units).toLocaleString('en-IN')}</strong></div><div class="v93-kpi"><span>Non-Moving FBA SKUs</span><strong>${a.nonMoving}</strong></div>`;
  const t=document.getElementById('periodicReportTable');if(t)t.innerHTML=`<thead><tr><th>Metric</th><th>Amazon</th><th>Flipkart</th></tr></thead><tbody><tr><td>Latest Price Parity</td><td>${a.priceParity.toFixed(1)}%</td><td>${f.priceParity.toFixed(1)}%</td></tr><tr><td>Live Disparity Revenue Impact</td><td>${money(a.revenueImpact)}</td><td>${money(f.revenueImpact)}</td></tr><tr><td>Orders During Disparity</td><td>${a.orders}</td><td>${f.orders}</td></tr><tr><td>Units During Disparity</td><td>${a.units}</td><td>${f.units}</td></tr><tr><td>Order Monetary Value</td><td>${money(a.orderRevenue)} actual Amazon order revenue</td><td>${money(f.orderValueAtLivePrice)} at Live Price</td></tr><tr><td>Suppression Cases</td><td>${a.suppression}</td><td>—</td></tr><tr><td>Buy Box Cases</td><td>${a.buyBox}</td><td>—</td></tr><tr><td>Non-Moving FBA SKUs</td><td>${a.nonMoving}</td><td>—</td></tr><tr><td>Excess FBA Units</td><td>${a.excessFba}</td><td>—</td></tr></tbody>`;
}
async function openPeriodicReports(){wakeSuiteNavigate?.('periodicReportsSection');const d=document.getElementById('periodicReportAnchor');if(d&&!d.value)d.value=latestDateText();await loadPeriodicReports();}
async function loadPeriodicReports(){try{await buildPeriodic();renderPeriodic();}catch(e){showWakeSuiteToast?.(e.message,'error','Periodic report');}}
function periodicWorkbook(aud){const st=periodicState,wb=XLSX.utils.book_new();const add=(name,rows)=>{if(rows.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),String(name).slice(0,31));};const sm=audienceSummary(aud);add('Summary',Object.entries(sm).map(([m,x])=>({Marketplace:m,...x})));add('Daily Trend',st.daily.filter(()=>true).map(r=>aud==='amazon'?{Date:r.date,'Price Parity %':r.amazonParity,'Live Disparity':r.amazonDisparity,'Revenue Impact':r.amazonImpact}:aud==='flipkart'?{Date:r.date,'Price Parity %':r.flipkartParity,'Live Disparity':r.flipkartDisparity,'Revenue Impact':r.flipkartImpact}:r));const imp=st.impact.filter(r=>aud==='internal'||r.marketplace===aud).map(r=>({Marketplace:r.marketplace==='amazon'?'Amazon':'Flipkart',Category:r.category,'ASIN / FSN':r.identifier,'WF SKU':r.wfSku,'Actionable Disparity Days':r.actionableDays,'Exception-Excluded Days':r.excludedDays,Orders:r.orders,Units:r.units,'Amazon Order Revenue':r.marketplace==='amazon'?r.orderRevenue:'','Flipkart Order Value at Live Price':r.marketplace==='flipkart'?r.orderValueAtLivePrice:'','Revenue Impact':r.revenueImpact}));add('Live Disparity Impact',imp);if(aud!=='flipkart')add('FBA Holding Risk',st.holding.map(r=>({Category:r.category,ASIN:r.asin,'WF SKU':r.wfSku,'AZ SKU':r.azSku,'FBA Inventory':r.fbaInventory,'7D Units':r.units7,'14D Units':r.units14,'30D Units':r.units30,'30D DRR':Number(r.drr30.toFixed(2)),'Last FBA Sale':r.lastFbaSale,'Days Since Sale':r.daysSinceSale,'Days Cover':r.daysCover==null?'':Number(r.daysCover.toFixed(1)),'Excess FBA Units':r.excessFbaUnits,'Holding Risk':r.status,'Related Issues':r.relatedIssues,'Recommended Attention':r.attention})));return wb;}
function downloadPeriodicReport(aud){if(!periodicState)return showWakeSuiteToast?.('Build the report first.','warning');XLSX.writeFile(periodicWorkbook(aud),`WakeSuite_${periodicState.cadence}_${aud}_${periodicState.from}_to_${periodicState.to}.xlsx`);}
async function sendPeriodicReport(aud){if(!periodicState)await loadPeriodicReports();const cfg=currentControls();let to=[],name='Team';if(aud==='internal')to=typeof v7SplitEmails==='function'?v7SplitEmails(cfg.internalMarketplaceRecipients):String(cfg.internalMarketplaceRecipients||'').split(',').filter(Boolean);else{const c=aud==='amazon'?cfg.amazonPoc:cfg.flipkartPoc;to=uniq([c?.email,...(typeof v7SplitEmails==='function'?v7SplitEmails(c?.additional):[])]);name=c?.name||'Team';}if(!to.length)return showWakeSuiteToast?.('Recipients are not configured.','warning');const s=periodicState.summary,subject=`WakeSuite | ${periodicState.cadence==='weekly'?'Weekly':'Monthly'} ${aud==='internal'?'Marketplace Performance':aud==='amazon'?'Amazon Marketplace':'Flipkart Marketplace'} Report | ${periodicState.from} to ${periodicState.to}`;const body=aud==='internal'?`<p>Hi Team,</p><p>Please find the combined Amazon + Flipkart ${periodicState.cadence} marketplace report for <strong>${periodicState.from} to ${periodicState.to}</strong>.</p>`:`<p>Hi ${esc(name)},</p><p>Please find the ${aud==='amazon'?'Amazon':'Flipkart'} ${periodicState.cadence} marketplace report for <strong>${periodicState.from} to ${periodicState.to}</strong>.</p>`;const html=`<div style="font-family:Arial,sans-serif;font-size:13px">${body}<table style="border-collapse:collapse"><tr><th style="border:1px solid #ccc;padding:8px">Marketplace</th><th style="border:1px solid #ccc;padding:8px">Price Parity</th><th style="border:1px solid #ccc;padding:8px">Rev Impact</th><th style="border:1px solid #ccc;padding:8px">Orders During Disparity</th><th style="border:1px solid #ccc;padding:8px">Units</th></tr>${Object.entries(audienceSummary(aud)).map(([m,x])=>`<tr><td style="border:1px solid #ccc;padding:8px">${m}</td><td style="border:1px solid #ccc;padding:8px">${x.priceParity.toFixed(1)}%</td><td style="border:1px solid #ccc;padding:8px">${money(x.revenueImpact)}</td><td style="border:1px solid #ccc;padding:8px">${x.orders}</td><td style="border:1px solid #ccc;padding:8px">${x.units}</td></tr>`).join('')}</table><p>Regards,<br>WakeSuite</p></div>`;try{await v7SendGmail({to,subject,html,workbook:periodicWorkbook(aud),filename:`WakeSuite_${periodicState.cadence}_${aud}_${periodicState.from}_to_${periodicState.to}.xlsx`});await window.saveCommunicationLog?.({reportDate:periodicState.to,communicationType:`${periodicState.cadence==='weekly'?'Weekly':'Monthly'} Marketplace Report`,marketplace:aud==='internal'?'combined':aud,recipients:to,status:'Sent',periodFrom:periodicState.from,periodTo:periodicState.to});showWakeSuiteToast?.('Report sent successfully.','success');}catch(e){showWakeSuiteToast?.(e.message,'error','Report send failed');}}

async function augmentDailyState(){
  if(typeof v7CommunicationsState==='undefined'||!v7CommunicationsState)return;
  const state=v7CommunicationsState;state.amazon.newRows=(state.amazon.newRows||[]).map(normalizeImpactRow);state.flipkart.newRows=(state.flipkart.newRows||[]).map(normalizeImpactRow);
  try{const cases=await window.loadSuppressionCases?.()||[];const continuing=cases.filter(c=>['Escalated','Follow-up Pending','Required'].includes(String(c.pocEscalationStatus||''))&&String(c.pocEscalationStatus)!=='Closed').map(c=>normalizeImpactRow({marketplace:'amazon',issueType:'ASIN Suppression',issueKey:`amazon|ASIN Suppression|${c.asin}`,productId:c.asin,asin:c.asin,category:c.category||'Unmapped',wfSku:c.wfSku||'',azSku:c.azSku||'',revenueImpactPerDay:c.revenueImpactPerDay,revenueAvailable:c.revenueAvailable!==false,poaLink:c.poaLink||''}));const map=new Map(state.amazon.newRows.map(r=>[r.issueKey,r]));continuing.forEach(r=>map.set(r.issueKey,r));state.amazon.newRows=[...map.values()];}catch(_e){}
}
const baseLoadDaily=window.loadDailyCommunications;if(typeof baseLoadDaily==='function')window.loadDailyCommunications=async function(...args){const out=await baseLoadDaily(...args);await augmentDailyState();try{renderDailyCommunications?.();}catch(_e){}return out;};

function applySettingsUi(){const c=currentControls();const set=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v??'';};set('holdingRiskWatchDays',c.holdingRisk.watchDays);set('holdingRiskSlowDays',c.holdingRisk.slowDays);set('holdingRiskNonMovingDays',c.holdingRisk.nonMovingDays);set('holdingRiskTargetCover',c.holdingRisk.targetCover);set('poaDriveEndpoint',c.poaDrive.endpoint);set('poaDriveFolderId',c.poaDrive.folderId);}
const baseLoadControls=window.loadOperationalControls;if(typeof baseLoadControls==='function')window.loadOperationalControls=async function(...args){const r=await baseLoadControls(...args);applySettingsUi();return r;};
const baseSaveControls=window.saveOperationalControls;if(typeof baseSaveControls==='function')window.saveOperationalControls=async function(...args){await baseSaveControls(...args);const extra={holdingRisk:{watchDays:n(document.getElementById('holdingRiskWatchDays')?.value||7),slowDays:n(document.getElementById('holdingRiskSlowDays')?.value||14),nonMovingDays:n(document.getElementById('holdingRiskNonMovingDays')?.value||30),targetCover:n(document.getElementById('holdingRiskTargetCover')?.value||30)},poaDrive:{endpoint:String(document.getElementById('poaDriveEndpoint')?.value||'').trim(),folderId:String(document.getElementById('poaDriveFolderId')?.value||'').trim()}};await window.saveOperationalControlsData?.(extra);if(typeof v7OperationalControls!=='undefined')v7OperationalControls={...v7OperationalControls,...extra};applySettingsUi();};

const baseBusinessLoad=window.loadBusinessInsightsV93;if(typeof baseBusinessLoad==='function')window.loadBusinessInsightsV93=async function(...args){const r=await baseBusinessLoad(...args);if(document.querySelector('[data-business-tab="inventory"].active'))try{renderHoldingPanel(await fbaHoldingRisk(document.getElementById('businessToDate')?.value||latestDateText()));}catch(e){console.warn('Holding risk failed',e);}return r;};
const baseOpenBusiness=window.openBusinessInsights;if(typeof baseOpenBusiness==='function')window.openBusinessInsights=async function(type='pricing',ctx={}){const r=await baseOpenBusiness(type,ctx);if(type==='inventory')try{renderHoldingPanel(await fbaHoldingRisk(document.getElementById('businessToDate')?.value||latestDateText()));}catch(_e){}return r;};

const baseInvHistory=window.loadInventoryHistory;if(typeof baseInvHistory==='function')window.loadInventoryHistory=async function(...args){const r=await baseInvHistory(...args);try{const holding=await fbaHoldingRisk(document.getElementById('inventoryHistoryToDate')?.value||latestDateText());const map=new Map(holding.map(x=>[x.asin,x]));const t=document.getElementById('inventoryHistoryTable');if(t&&t.tHead&&![...t.tHead.rows[0].cells].some(c=>c.textContent==='FBA Holding Risk')){['FBA Holding Risk','Days Since FBA Sale','30D FBA Units','Excess FBA Units'].forEach(x=>t.tHead.rows[0].insertAdjacentHTML('beforeend',`<th>${x}</th>`));[...t.tBodies[0]?.rows||[]].forEach(tr=>{const asin=[...tr.cells].map(c=>c.textContent.trim()).find(v=>/^B0[A-Z0-9]+$/i.test(v));const h=map.get(asin);[h?.status||'—',h?.daysSinceSale??'—',h?.units30??'—',h?.excessFbaUnits??'—'].forEach(v=>tr.insertAdjacentHTML('beforeend',`<td>${esc(v)}</td>`));});}}catch(e){console.warn('Inventory history holding-risk enhancement failed',e);}return r;};

function patchVersion(){document.querySelectorAll('.footer').forEach(e=>e.textContent=e.textContent.replace(/V9\.3\.4/g,'V9.3.5'));}
Object.assign(window,{openPeriodicReports,loadPeriodicReports,sendPeriodicReport,downloadPeriodicReport,WakeSuiteV935:{version:VERSION,disparityImpact,fbaHoldingRisk,buildPeriodic}});
document.addEventListener('DOMContentLoaded',()=>{patchVersion();applySettingsUi();const a=document.getElementById('periodicReportAnchor');if(a&&!a.value)a.value=latestDateText();});
})();
