/* WakeSuite V9.3 · suppression lifecycle + bulk decisions */
(function(){
  const selected=new Set();let visible=[];
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v??''):String(v??'');
  const n=v=>Number(v)||0;
  const dateText=v=>v?.toDate?v.toDate().toISOString().slice(0,10):String(v||'');
  function age(r){const a=dateText(r.firstSeen||r.firstDetected),b=dateText(r.lastSeen||r.lastDetected)||todayIso();if(!a)return'—';const d=Math.max(1,Math.floor((new Date(`${b}T00:00:00`)-new Date(`${a}T00:00:00`))/86400000)+1);return `${d} day${d===1?'':'s'}`;}
  function lifecycleState(r){const raw=String(r.currentState||r.suppressionState||'').trim();if(raw)return raw;if(String(r.status||'')==='Reactivated')return'Reactivated';if(String(r.status||'')==='Closed')return'Closed';if(r.overrideActive||String(r.overrideStatus||'').toLowerCase()==='active')return'Overridden';return'Active';}
  function filtered(){const range=v4SetRangeControls('suppressionManagementPeriod','suppressionManagementFromDate','suppressionManagementToDate'),from=range[0],to=range[1],status=document.getElementById('suppressionManagementStatus')?.value||'all',state=document.getElementById('suppressionManagementState')?.value||'all',category=document.getElementById('suppressionManagementCategory')?.value||'all',poc=document.getElementById('suppressionManagementPoc')?.value||'all',source=document.getElementById('suppressionManagementSource')?.value||'all',owner=document.getElementById('suppressionManagementOwner')?.value||'all',poa=document.getElementById('suppressionManagementPoa')?.value||'all',qc=document.getElementById('suppressionManagementQc')?.value||'all',search=String(document.getElementById('suppressionManagementSearch')?.value||'').toLowerCase(),sort=document.getElementById('suppressionManagementSort')?.value||'latest',uid=window.wakeSuiteFirebase?.auth?.currentUser?.uid||'';let rows=(typeof v7SuppressionCases!=='undefined'?v7SuppressionCases:[]).filter(r=>{const d=dateText(r.lastSeen||r.lastDetected||r.firstSeen||r.firstDetected);if(d&&(d<from||d>to))return false;if(typeof v7CategoryAllowed==='function'&&!v7CategoryAllowed(r.category))return false;if(status!=='all'&&r.status!==status)return false;if(state!=='all'&&lifecycleState(r)!==state)return false;if(category!=='all'&&r.category!==category)return false;if(source!=='all'&&(r.source||'Audit')!==source)return false;if(poa!=='all'&&r.poaStatus!==poa)return false;if(qc!=='all'&&r.qcStatus!==qc)return false;if(poc!=='all'&&!((poc==='required'&&r.pocEscalationStatus==='Required')||(poc==='escalated'&&r.pocEscalationStatus==='Escalated')||(poc==='needs_review'&&r.pocEscalationStatus==='Needs Review')||(poc==='not_required'&&r.pocEscalationStatus==='Not Required')))return false;const ids=Array.isArray(r.assignees)?r.assignees:[];if(owner==='me'&&!ids.includes(uid))return false;if(owner==='my_team'&&!r.teamAssigned)return false;if(owner!=='all'&&!['me','my_team'].includes(owner)&&!ids.includes(owner))return false;if(search&&!`${r.asin||''} ${r.wfSku||''} ${r.azSku||''} ${r.caseId||''} ${r.owner||''}`.toLowerCase().includes(search))return false;return true;});rows.sort((a,b)=>sort==='impact_desc'?n(b.revenueImpactPerDay)-n(a.revenueImpactPerDay):sort==='asin'?String(a.asin).localeCompare(String(b.asin)):String(b.lastSeen||b.lastDetected||'').localeCompare(String(a.lastSeen||a.lastDetected||'')));return rows;}
  const cols=[['select','Select'],['category','Category'],['asin','ASIN'],['wfSku','WF SKU'],['azSku','AZ SKU'],['first','First Seen'],['last','Last Seen'],['age','Age'],['state','State'],['resolved','Resolved On'],['impact','Rev Impact / Day'],['caseId','Case ID'],['owner','Owner'],['status','Case Status'],['poc','POC'],['poa','POA'],['qc','QC'],['notes','Notes'],['action','Action']];
  function ownerNames(r){if(Array.isArray(r.assigneeNames)&&r.assigneeNames.length)return r.assigneeNames.join(', ');return r.owner||'';}
  function render(){const table=document.getElementById('suppressionManagementTable'),kpis=document.getElementById('suppressionManagementKpis');if(!table||!kpis)return;visible=filtered();window.v8VisibleSuppressionCases=visible;const open=visible.filter(r=>!['Reactivated','Closed'].includes(lifecycleState(r))).length,over=visible.filter(r=>lifecycleState(r)==='Overridden').length,pending=visible.filter(r=>!r.caseId&&!['Reactivated','Closed'].includes(lifecycleState(r))).length,exposure=visible.filter(r=>!['Reactivated','Closed','Overridden'].includes(lifecycleState(r))).reduce((a,r)=>a+n(r.revenueImpactPerDay),0);kpis.innerHTML=`<div class="v7-kpi"><span>Active Suppressions</span><strong>${open}</strong></div><div class="v7-kpi"><span>Overridden</span><strong>${over}</strong></div><div class="v7-kpi"><span>Pending Case IDs</span><strong>${pending}</strong></div><div class="v7-kpi"><span>Actionable Rev Exposure / Day</span><strong>${formatINR(exposure)}</strong></div>`;table.dataset.wsColumnTable='suppressionManagement';table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${c[1]}</th>`).join('')+'</tr></thead><tbody>'+(visible.length?visible.map(r=>{const canManage=typeof v7HasAction==='function'&&(v7HasAction('manageSuppressions')||v7HasAction('raiseCaseId')||window.currentWakeSuiteAccess?.role==='super_admin');const id=String(r.id||r.asin);return`<tr data-case-id="${esc(id)}"><td><input type="checkbox" data-suppression-select="${esc(id)}" ${selected.has(id)?'checked':''} onchange="toggleSuppressionSelection('${esc(id)}',this.checked)"></td><td>${esc(r.category||'')}</td><td><button class="v93-link-id" onclick='WakeSuiteProduct360.open(${JSON.stringify(r.asin||'')},{context:"suppressions"})'>${esc(r.asin||'')}</button></td><td>${esc(r.wfSku||'')}</td><td>${esc(r.azSku||'')}</td><td>${esc(dateText(r.firstSeen||r.firstDetected))}</td><td>${esc(dateText(r.lastSeen||r.lastDetected))}</td><td>${esc(age(r))}</td><td>${esc(lifecycleState(r))}</td><td>${esc(dateText(r.resolvedOn||r.closedOn))}</td><td>${r.revenueAvailable===false?'Revenue Data Refresh Required':formatINR(n(r.revenueImpactPerDay))}</td><td>${esc(r.caseId||'')}</td><td>${esc(ownerNames(r))}</td><td>${esc(r.status||'Detected')}</td><td>${esc(r.pocEscalationStatus||'Not Required')}</td><td>${esc(r.poaStatus||'Not Required')}</td><td>${esc(r.qcStatus||'Not Required')}</td><td>${esc(r.notes||'')}</td><td>${canManage?`<button class="secondary-btn" onclick='editSuppressionCaseV93(${JSON.stringify(id)})'>Edit</button>`:'View only'}</td></tr>`;}).join(''):`<tr><td colspan="${cols.length}" class="empty-row">No suppression cases match the selected filters.</td></tr>`)+'</tbody>';WakeSuiteColumns.register('suppressionManagement',cols.map(c=>({key:c[0],label:c[1]})),['select','category','asin','first','last','age','state','impact','caseId','owner','status','poc','poa','qc','action'],'suppressionManagementColumns');updateCount();}
  function updateCount(){const e=document.getElementById('suppressionSelectedCount');if(e)e.textContent=`${selected.size} selected`;const all=visible.length&&visible.every(r=>selected.has(String(r.id||r.asin)));const cb=document.getElementById('suppressionSelectVisible');if(cb)cb.checked=!!all;}
  function toggle(id,ch){if(ch)selected.add(id);else selected.delete(id);updateCount();}
  function selectVisible(ch=true){visible.forEach(r=>{const id=String(r.id||r.asin);if(ch)selected.add(id);else selected.delete(id);});render();}
  function selectAll(){visible.forEach(r=>selected.add(String(r.id||r.asin)));render();}
  function clear(){selected.clear();render();}
  async function bulkCase(){if(!selected.size){showWakeSuiteToast?.('Select at least one ASIN.','warning');return;}if(!(window.currentWakeSuiteAccess?.role==='super_admin'||v7HasAction?.('raiseCaseId'))){showWakeSuiteToast?.('Raise Case ID permission is required.','warning');return;}const caseId=String(document.getElementById('suppressionBulkCaseId')?.value||'').trim();if(!caseId){showWakeSuiteToast?.('Enter a Case ID.','warning');return;}if(!confirm(`Apply Case ID ${caseId} to ${selected.size} selected ASIN(s)?`))return;await bulkUpdate({caseId,caseIdRaisedOn:todayIso()},'Case ID');}
  async function bulkStatus(){if(!selected.size){showWakeSuiteToast?.('Select at least one ASIN.','warning');return;}if(!(window.currentWakeSuiteAccess?.role==='super_admin'||v7HasAction?.('manageSuppressions'))){showWakeSuiteToast?.('Manage Suppressions permission is required.','warning');return;}const status=document.getElementById('suppressionBulkStatus')?.value;if(!status)return;if(!confirm(`Apply status ${status} to ${selected.size} selected ASIN(s)?`))return;const extra=status==='Closed'?{closedOn:todayIso()}:status==='Reactivated'?{reactivatedOn:todayIso()}:{};await bulkUpdate({status,...extra},'Status');}
  async function bulkUpdate(patch,label){const chosen=(typeof v7SuppressionCases!=='undefined'?v7SuppressionCases:[]).filter(r=>selected.has(String(r.id||r.asin)));try{for(const r of chosen){await window.updateSuppressionCase?.(r.id,patch);await window.saveSuppressionCaseAudit?.({caseId:r.id,asin:r.asin,action:`Bulk ${label}`,changes:patch});}selected.clear();await loadSuppressionManagement();showWakeSuiteToast?.(`${label} applied to ${chosen.length} selected ASIN(s).`,'success');}catch(e){showWakeSuiteToast?.(e.message,'error',`Bulk ${label} failed`);}}
  async function edit(id){const r=(typeof v7SuppressionCases!=='undefined'?v7SuppressionCases:[]).find(x=>String(x.id||x.asin)===String(id));if(!r)return;const caseId=prompt('Case ID:',r.caseId||'');if(caseId===null)return;const notes=prompt('Notes:',r.notes||'');if(notes===null)return;try{await window.updateSuppressionCase?.(r.id,{caseId:String(caseId).trim(),notes:String(notes).trim(),caseIdRaisedOn:r.caseIdRaisedOn||((caseId&&!r.caseId)?todayIso():'')});await loadSuppressionManagement();}catch(e){showWakeSuiteToast?.(e.message,'error','Suppression update');}}
  function download(){if(!visible.length){showWakeSuiteToast?.('No suppression management rows to download.','warning');return;}const data=visible.map(r=>({Marketplace:'Amazon',Category:r.category,ASIN:r.asin,'WF SKU':r.wfSku||'','AZ SKU':r.azSku||'','First Seen':dateText(r.firstSeen||r.firstDetected),'Last Seen':dateText(r.lastSeen||r.lastDetected),Age:age(r),State:lifecycleState(r),'Resolved On':dateText(r.resolvedOn||r.closedOn),'Revenue Impact / Day':r.revenueImpactPerDay??'','Case ID':r.caseId||'',Owner:ownerNames(r),'Case Status':r.status||'',POC:r.pocEscalationStatus||'',POA:r.poaStatus||'',QC:r.qcStatus||'',Notes:r.notes||''}));writeExcelReport?.(`Amazon_Suppression_Management_${todayIso()}.xlsx`,{},data);}
  const baseLoad=window.loadSuppressionManagement;
  async function load(){try{if(typeof baseLoad==='function')await baseLoad();else if(typeof window.loadSuppressionCases==='function')v7SuppressionCases=await window.loadSuppressionCases();render();}catch(e){showWakeSuiteToast?.(e.message,'error','Unable to load suppression cases');}}
  window.renderSuppressionManagement=render;window.loadSuppressionManagement=load;window.toggleSuppressionSelection=toggle;window.toggleSuppressionSelectVisible=selectVisible;window.selectAllFilteredSuppressions=selectAll;window.clearSuppressionSelection=clear;window.applyBulkSuppressionCaseId=bulkCase;window.applyBulkSuppressionStatus=bulkStatus;window.editSuppressionCaseV93=edit;window.downloadSuppressionManagement=download;window.WakeSuiteSuppressionManagement={render,load,selected};
})();
