/* WakeSuite V9.3.4
 * Dedicated dashboard analysis + Order-Report-first Business Insights.
 * IMPORTANT: V9.3.4 intentionally does NOT implement a shared analytics filter bar.
 * Existing per-page filter/dropdown structures remain independent.
 */
(function(){
  'use strict';

  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v??''):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>{const x=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:0;};
  const nf=v=>Number(n(v)).toLocaleString('en-IN',{maximumFractionDigits:2});
  const money=v=>Number.isFinite(Number(v))?(typeof formatINR==='function'?formatINR(Number(v)):`₹${Number(v).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})}`):'—';
  const pct=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(1)}%`:'—';
  const today=()=>typeof todayIso==='function'?todayIso():new Date().toISOString().slice(0,10);
  const localIso=d=>typeof localIsoDate==='function'?localIsoDate(d):d.toISOString().slice(0,10);
  const shift=(iso,days)=>{const d=new Date(`${iso}T00:00:00`);d.setDate(d.getDate()+days);return localIso(d);};
  const dates=(from,to)=>{const out=[];for(let d=from;d&&d<=to;d=shift(d,1))out.push(d);return out;};
  const unique=a=>[...new Set(a.filter(v=>v!==''&&v!==null&&v!==undefined))];
  const latest=()=>{const x=document.getElementById('latestCompletedDateDisplay')?.textContent?.replace('As of ','').trim();return /^\d{4}-\d{2}-\d{2}$/.test(x||'')?x:today();};
  const rowId=(r,m)=>m==='amazon'?String(r.asin||r.azSku||r.wfSku||''):String(r.fsn||r.fkSku||r.wfSku||'');
  const marketSku=(r,m)=>m==='amazon'?String(r.azSku||''):String(r.fkSku||'');
  const bool=v=>v===true||v===1||String(v).toLowerCase()==='true';
  const safeCall=(fn,...args)=>{try{return typeof fn==='function'?fn(...args):undefined;}catch(e){console.warn('WakeSuite V9.3.4 safe call failed',e);return undefined;}};

  function normalizePeriod(v){return v==='last15'?'last14':v||'last7';}
  function resolveRange(period,from,to,anchor=latest()){
    let f=from||anchor,t=to||anchor;
    switch(normalizePeriod(period)){
      case 'today': f=t=anchor;break;
      case 'yesterday': f=t=shift(anchor,-1);break;
      case 'last7': f=shift(anchor,-6);t=anchor;break;
      case 'last14': f=shift(anchor,-13);t=anchor;break;
      case 'last30': f=shift(anchor,-29);t=anchor;break;
      case 'custom': if(!f)f=anchor;if(!t)t=anchor;break;
      default: f=t=anchor;
    }
    if(f>t)[f,t]=[t,f];return[f,t];
  }
  async function snapshots(from,to){return typeof v4LoadSnapshotsForRange==='function'?(await v4LoadSnapshotsForRange(from,to)||[]):[];}
  async function orders(){return window.WakeSuiteV933?.loadOrders?await WakeSuiteV933.loadOrders():[];}

  /* -----------------------------
     Source helpers
  ----------------------------- */
  const canon=v=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
  function pick(row,aliases){const keys=Object.keys(row||{}),map=new Map(keys.map(k=>[canon(k),k]));for(const a of aliases){const k=map.get(canon(a));if(k!==undefined&&row[k]!==''&&row[k]!==null&&row[k]!==undefined)return row[k];}return '';}
  async function rawVersions(configId){
    if(typeof openWakeSuiteDb!=='function'||!window.XLSX)return[];
    try{
      const db=await openWakeSuiteDb();
      return await new Promise((resolve,reject)=>{
        const tx=db.transaction(['report_versions','raw_files'],'readonly');
        const q=tx.objectStore('report_versions').getAll();
        q.onsuccess=()=>{
          const latestMap=new Map();
          (q.result||[]).filter(v=>v.configId===configId&&v.status==='successful').forEach(v=>{const k=v.dateConfig||`${v.reportDate}::${configId}`;const old=latestMap.get(k);if(!old||Number(v.createdAt)>Number(old.createdAt))latestMap.set(k,v);});
          const versions=[...latestMap.values()];if(!versions.length){resolve([]);return;}
          let left=versions.length;const out=[];
          versions.forEach(v=>{const r=tx.objectStore('raw_files').get(v.versionId);r.onsuccess=()=>{if(r.result)out.push({...v,raw:r.result});if(--left===0)resolve(out);};r.onerror=()=>{if(--left===0)resolve(out);};});
        };
        q.onerror=()=>reject(q.error);
      });
    }catch(e){console.warn('V9.3.4 raw source read failed',e);return[];}
  }
  function parseRaw(raw){try{const wb=XLSX.read(raw.bytes,{type:'array',cellDates:true});let out=[];wb.SheetNames.forEach(name=>{const a=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:false});if(a.length)out.push(...a);});return out;}catch(e){return[];}}
  let flipFulfillmentCache=null;
  async function flipCurrentFulfillment(){
    if(flipFulfillmentCache)return flipFulfillmentCache;
    const map=new Map(),versions=await rawVersions('flipkart_listing_file');versions.sort((a,b)=>String(b.reportDate||'').localeCompare(String(a.reportDate||'')));
    if(versions[0])for(const r of parseRaw(versions[0].raw)){const fsn=String(pick(r,['fsn','Flipkart Serial Number'])||'').trim(),sku=String(pick(r,['Seller SKU Id','seller sku id','sku'])||'').trim(),f=String(pick(r,['Fulfillment By','fulfillment by'])||'').trim();if(fsn&&f)map.set(`fsn:${fsn}`,f);if(sku&&f)map.set(`sku:${sku}`,f);}
    flipFulfillmentCache=map;return map;
  }
  function fulfillmentSummary(os){const m={};for(const o of os){const f=String(o.fulfillment||'Unknown');m[f]=(m[f]||0)+n(o.units);}return Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${k} ${nf(v)}`).join(' · ')||'No Order Data';}

  /* -----------------------------
     V9.3.4 dedicated dashboard analysis
  ----------------------------- */
  let analysisState={marketplace:'amazon',focus:'price_disparity',rows:[],liveRows:[],from:'',to:'',pendingCategory:''};
  function ensureDashboardAnalysisView(){
    if(document.getElementById('dashboardAnalysisSection'))return;
    const section=document.createElement('section');section.className='app-view';section.id='dashboardAnalysisSection';
    section.innerHTML=`<div class="panel v934-analysis-page">
      <div class="panel-title-row"><div class="v93-title-with-back"><button class="v93-back-btn" onclick="wakeSuiteBack()">← Back</button><div><h2 id="v934AnalysisTitle">Analysis</h2><div class="v7-muted" id="v934AnalysisSubtitle">Dashboard analysis</div></div></div><div class="module-actions"><button class="secondary-btn" onclick="downloadV934DashboardAnalysis(false)">Download Visible</button><button class="secondary-btn" onclick="downloadV934DashboardAnalysis(true)">Full Export</button></div></div>
      <div class="v934-analysis-filter-grid" id="v934AnalysisFilters">
        <select id="v934AnalysisPeriod"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="last7">Last 7 Days</option><option value="last14">Last 14 Days</option><option value="last30">Last 30 Days</option><option value="custom">Custom Range</option></select>
        <input id="v934AnalysisFrom" type="date"><input id="v934AnalysisTo" type="date"><select id="v934AnalysisCategory"><option value="all">All Categories</option></select>
        <select id="v934AnalysisIssue"><option value="all">All Issue Types</option><option value="listing">Listing Price</option><option value="live">Live Price</option><option value="mrp">MRP</option></select>
        <input id="v934AnalysisSearch" type="search" placeholder="ASIN / FSN / WF SKU / AZ SKU / FK SKU"><button class="primary-btn" onclick="loadV934DashboardAnalysis()">Apply</button><button class="secondary-btn" onclick="resetV934DashboardAnalysis()">Reset</button>
      </div>
      <div class="v8-view-switch" role="group"><button class="v8-view-btn active" data-v934-analysis-view="insights" onclick="setV934DashboardAnalysisView('insights',this)">Insights</button><button class="v8-view-btn" data-v934-analysis-view="detail" onclick="setV934DashboardAnalysisView('detail',this)">Detailed Data</button><button class="v8-view-btn" data-v934-analysis-view="history" onclick="openV934DashboardAnalysisHistory()">History</button></div>
      <div class="v93-kpi-grid" id="v934AnalysisKpis"></div>
      <div class="insights-chart-grid" id="v934AnalysisCharts"><div class="analytics-card"><div class="analytics-card-head"><strong id="v934TrendTitle">Trend</strong><span id="v934TrendMeta">Selected period</span></div><div id="v934AnalysisTrend" class="analytics-chart"></div></div><div class="analytics-card"><div class="analytics-card-head"><strong>Category Analysis</strong><span>Filtered scope</span></div><div id="v934AnalysisCategoryChart"></div></div></div>
      <div class="analytics-card" id="v934LiveImpactCard" hidden><div class="analytics-card-head"><div><strong>Live Price Disparity · Order Impact</strong><div class="v7-muted">Exact-date overlap. Exception-covered live-disparity dates remain visible but are excluded from actionable orders/units/revenue impact.</div></div><span id="v934LiveImpactMeta"></span></div><div class="v93-kpi-grid" id="v934LiveImpactKpis"></div><div class="v934-impact-split"><div><h4>Fulfilment</h4><div id="v934LiveFulfillment"></div></div><div><h4>Category Orders</h4><div id="v934LiveCategories"></div></div></div><div class="table-wrap"><table class="result-table" id="v934LiveImpactTable"></table></div></div>
      <div class="analytics-card" id="v934AnalysisTableCard"><div class="analytics-card-head"><strong id="v934TableTitle">Detailed Analysis</strong><div class="module-actions"><details class="column-picker"><summary>Columns</summary><div class="column-picker-panel"><div class="v8-column-actions"><button onclick="WakeSuiteColumns.selectAll('v934DashboardAnalysis')">Select All</button><button onclick="WakeSuiteColumns.clearAll('v934DashboardAnalysis')">Clear All</button><button onclick="WakeSuiteColumns.setDefault('v934DashboardAnalysis')">Set as Default</button><button onclick="WakeSuiteColumns.restoreDefault('v934DashboardAnalysis')">Restore Default</button></div><div id="v934AnalysisColumns"></div></div></details><span id="v934AnalysisRowInfo">0 rows</span></div></div><div class="table-wrap"><table class="result-table" id="v934AnalysisTable"></table></div></div>
    </div>`;
    const ref=document.getElementById('revenueImpactSection')||document.querySelector('main .app-view:last-of-type');ref?.insertAdjacentElement('afterend',section);
  }
  function dashboardContext(){
    const raw=document.getElementById('dashboardPeriod')?.value||'today';return{period:normalizePeriod(raw),from:document.getElementById('dashboardFromDate')?.value||'',to:document.getElementById('dashboardToDate')?.value||'',category:document.getElementById('dashboardCategory')?.value||'all'};
  }
  function setAnalysisCtx(ctx={}){const p=document.getElementById('v934AnalysisPeriod');if(p)p.value=normalizePeriod(ctx.period||'last7');if(ctx.from)document.getElementById('v934AnalysisFrom').value=ctx.from;if(ctx.to)document.getElementById('v934AnalysisTo').value=ctx.to;const c=document.getElementById('v934AnalysisCategory');if(c&&ctx.category)c.value=ctx.category;}
  function rawComponent(r,key){const cap=key[0].toUpperCase()+key.slice(1);return bool(r[`raw${cap}PriceDisparity`])||bool(r[`raw${cap}Disparity`])||bool(r[`${key}PriceDisparity`]);}
  function actionableComponent(r,key){return bool(r[`${key}PriceDisparity`]);}
  function exceptionComponent(r,key){return bool(r[`${key}PriceException`])||bool(r[`${key}Exception`])||(rawComponent(r,key)&&!actionableComponent(r,key));}
  function priceImpact(r){return Math.max(0,n(r.dailyRevenueImpact),n(r.liveDailyRevenueImpact),n(r.listingDailyRevenueImpact),n(r.revenueImpactPerDay));}
  function priceRows(snaps,market){
    const out=[];for(const s of snaps){const src=market==='amazon'?getSnapshotAmazonRows(s):getSnapshotFlipkartRows(s);for(const r of src||[]){const listing=actionableComponent(r,'listing'),live=actionableComponent(r,'live'),mrp=actionableComponent(r,'mrp'),rawListing=rawComponent(r,'listing'),rawLive=rawComponent(r,'live'),rawMrp=rawComponent(r,'mrp'),exListing=exceptionComponent(r,'listing'),exLive=exceptionComponent(r,'live'),exMrp=exceptionComponent(r,'mrp');if(!(rawListing||rawLive||rawMrp))continue;out.push({date:s.reportDate,marketplace:market,category:r.category||'Uncategorized',wfSku:r.wfSku||'',marketSku:marketSku(r,market),identifier:rowId(r,market),listing,live,mrp,rawListing,rawLive,rawMrp,exListing,exLive,exMrp,actionable:listing||live||mrp,exceptionExcluded:exListing||exLive||exMrp,impact:market==='amazon'?priceImpact(r):null,raw:r});}}
    return out;
  }
  function issueRows(snaps,focus){
    const group=focus==='amazon_buybox'?'amazonBuyBox':'amazonSuppressions',out=[];for(const s of snaps){for(const r of getSnapshotAmazonIssueRows(s,group)||[])out.push({date:s.reportDate,marketplace:'amazon',category:r.category||'Uncategorized',wfSku:r.wfSku||'',marketSku:r.azSku||'',identifier:r.asin||'',impact:n(r.revenueImpactPerDay),state:focus==='amazon_buybox'?'Buy Box Suppressed':'Suppressed'});}return out;
  }
  function revenueRows(snaps,market){
    const out=[];const add=(date,m,r,issue,impact,actionable=true)=>{const id=rowId(r,m);if(!id)return;out.push({date,marketplace:m,category:r.category||'Uncategorized',wfSku:r.wfSku||'',marketSku:marketSku(r,m),identifier:id,issue,impact:m==='amazon'&&actionable?n(impact):null,actionable});};
    for(const s of snaps){if(market==='combined'||market==='amazon'){
      for(const r of getSnapshotAmazonRows(s)||[]){if(r.listingPriceDisparity)add(s.reportDate,'amazon',r,'Listing Price',r.listingDailyRevenueImpact||r.dailyRevenueImpact);if(r.livePriceDisparity)add(s.reportDate,'amazon',r,'Live Price',r.liveDailyRevenueImpact||r.dailyRevenueImpact);}
      for(const r of getSnapshotAmazonIssueRows(s,'amazonSuppressions')||[])add(s.reportDate,'amazon',r,'ASIN Suppression',r.revenueImpactPerDay);
      for(const r of getSnapshotAmazonIssueRows(s,'amazonBuyBox')||[])add(s.reportDate,'amazon',r,'Buy Box Suppression',r.revenueImpactPerDay);
    }
    if(market==='combined'||market==='flipkart')for(const r of getSnapshotFlipkartRows(s)||[]){if(r.listingPriceDisparity)add(s.reportDate,'flipkart',r,'Listing Price',null);if(r.livePriceDisparity)add(s.reportDate,'flipkart',r,'Live Price',null);if(r.mrpDisparity)add(s.reportDate,'flipkart',r,'MRP',null);}
    }
    return out;
  }
  function analysisFilter(rows,focus){const cat=document.getElementById('v934AnalysisCategory')?.value||'all',issue=document.getElementById('v934AnalysisIssue')?.value||'all',q=String(document.getElementById('v934AnalysisSearch')?.value||'').trim().toLowerCase();return rows.filter(r=>(cat==='all'||r.category===cat)&&(!q||`${r.identifier} ${r.marketSku} ${r.wfSku}`.toLowerCase().includes(q))&&(focus!=='price_disparity'||issue==='all'||(issue==='listing'&&(r.rawListing||r.listing))||(issue==='live'&&(r.rawLive||r.live))||(issue==='mrp'&&(r.rawMrp||r.mrp))));}
  function populateAnalysisCats(rows){const e=document.getElementById('v934AnalysisCategory');if(!e)return;const desired=analysisState.pendingCategory||e.value||'all',cats=unique(rows.map(r=>r.category)).sort();e.innerHTML='<option value="all">All Categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');e.value=cats.includes(desired)?desired:'all';analysisState.pendingCategory='';}
  function barHtml(map,format=v=>nf(v)){const entries=Object.entries(map).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>Math.abs(x[1])));return `<div class="v93-bar-chart">${entries.slice(0,20).map(([k,v])=>`<div class="v93-bar-row"><span>${esc(k)}</span><div class="v93-bar-track"><div class="v93-bar-fill" style="width:${Math.min(100,Math.abs(v)/max*100)}%"></div></div><strong>${esc(format(v))}</strong></div>`).join('')||'<div class="utility-empty">No data.</div>'}</div>`;}
  function renderAnalysisTable(rows,focus){
    let cols=[];
    if(focus==='price_disparity')cols=[['date','Date'],['category','Category'],['wfSku','WF SKU'],['marketSku',analysisState.marketplace==='amazon'?'AZ SKU':'FK SKU'],['identifier',analysisState.marketplace==='amazon'?'ASIN':'FSN'],['listing','Listing Actionable'],['live','Live Actionable'],['mrp','MRP Actionable'],['exceptionExcluded','Exception Excluded'],['impact','Known Revenue Impact / Day']];
    else if(focus==='total_impact')cols=[['date','Date'],['marketplace','Marketplace'],['category','Category'],['wfSku','WF SKU'],['marketSku','Marketplace SKU'],['identifier','ASIN / FSN'],['issue','Primary Issue'],['impact','Known Revenue Impact / Day']];
    else cols=[['date','Date'],['category','Category'],['wfSku','WF SKU'],['marketSku','AZ SKU'],['identifier','ASIN'],['state','State'],['impact','Revenue Impact / Day']];
    const table=document.getElementById('v934AnalysisTable');table.dataset.wsColumnTable='v934DashboardAnalysis';table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c[1])}</th>`).join('')+'</tr></thead><tbody>'+(rows.length?rows.slice(0,4000).map(r=>'<tr>'+cols.map(([k])=>{let v=r[k];if(k==='impact')v=r.marketplace==='flipkart'||v===null?'Unavailable':money(v);if(typeof v==='boolean')v=v?'Yes':'No';if(k==='marketplace')v=r.marketplace==='amazon'?'Amazon':'Flipkart';if(['wfSku','marketSku','identifier'].includes(k)&&v)return`<td><button class="v93-link-id" onclick='WakeSuiteProduct360.open(${JSON.stringify(String(v))},{context:"global",date:${JSON.stringify(r.date)}})'>${esc(v)}</button></td>`;return`<td>${esc(v??'—')}</td>`;}).join('')+'</tr>').join(''):`<tr><td colspan="${cols.length}" class="empty-row">No analysis rows match the selected controls.</td></tr>`)+'</tbody>';
    document.getElementById('v934AnalysisRowInfo').textContent=`${nf(rows.length)} rows`;safeCall(window.WakeSuiteColumns?.register,'v934DashboardAnalysis',cols.map(([key,label])=>({key,label})),cols.map(x=>x[0]),'v934AnalysisColumns');
  }
  function renderPriceAnalysis(rows){
    const products=new Set(rows.map(r=>r.identifier)),actionable=new Set(rows.filter(r=>r.actionable).map(r=>r.identifier)),excluded=new Set(rows.filter(r=>r.exceptionExcluded).map(r=>r.identifier)),listing=new Set(rows.filter(r=>r.listing).map(r=>r.identifier)),live=new Set(rows.filter(r=>r.live).map(r=>r.identifier)),mrp=new Set(rows.filter(r=>r.mrp).map(r=>r.identifier));
    const knownImpact=analysisState.marketplace==='amazon'?rows.filter(r=>r.actionable).reduce((s,r)=>s+n(r.impact),0):null;
    document.getElementById('v934AnalysisKpis').innerHTML=`<div class="v93-kpi"><span>Disparity Products</span><strong>${nf(products.size)}</strong></div><div class="v93-kpi"><span>Actionable Disparities</span><strong>${nf(actionable.size)}</strong></div><div class="v93-kpi"><span>Exceptions Excluded</span><strong>${nf(excluded.size)}</strong></div><div class="v93-kpi"><span>Listing Disparity</span><strong>${nf(listing.size)}</strong></div><div class="v93-kpi"><span>Live Disparity</span><strong>${nf(live.size)}</strong></div><div class="v93-kpi"><span>MRP Disparity</span><strong>${nf(mrp.size)}</strong></div><div class="v93-kpi"><span>Known Revenue Impact</span><strong>${knownImpact===null?'Unavailable':money(knownImpact)}</strong><small>${analysisState.marketplace==='flipkart'?'Flipkart Order Report has no revenue field':'Actionable product-day impact'}</small></div>`;
    const daily={};rows.forEach(r=>daily[r.date]=(daily[r.date]||0)+(r.actionable?1:0));document.getElementById('v934AnalysisTrend').innerHTML=barHtml(daily);const cat={};rows.forEach(r=>cat[r.category]=(cat[r.category]||0)+(r.actionable?1:0));document.getElementById('v934AnalysisCategoryChart').innerHTML=barHtml(cat);
    renderAnalysisTable(rows,'price_disparity');
  }
  function renderIssueAnalysis(rows,focus){
    const products=new Set(rows.map(r=>r.identifier)),days=new Set(rows.map(r=>r.date)),impact=rows.reduce((s,r)=>s+n(r.impact),0),label=focus==='amazon_buybox'?'Buy Box Suppressed':'Suppressed';
    document.getElementById('v934AnalysisKpis').innerHTML=`<div class="v93-kpi"><span>${label} ASINs</span><strong>${nf(products.size)}</strong></div><div class="v93-kpi"><span>Observed Issue Days</span><strong>${nf(days.size)}</strong></div><div class="v93-kpi"><span>Issue Observations</span><strong>${nf(rows.length)}</strong></div><div class="v93-kpi"><span>Revenue Impact / Day Observations</span><strong>${money(impact)}</strong></div>`;
    const daily={};rows.forEach(r=>daily[r.date]=(daily[r.date]||0)+1);document.getElementById('v934AnalysisTrend').innerHTML=barHtml(daily);const cat={};rows.forEach(r=>cat[r.category]=(cat[r.category]||0)+1);document.getElementById('v934AnalysisCategoryChart').innerHTML=barHtml(cat);renderAnalysisTable(rows,focus);
  }
  function renderRevenueAnalysis(rows){
    const dedup=new Map();rows.forEach(r=>{const k=`${r.date}|${r.marketplace}|${r.identifier}`;const old=dedup.get(k);if(!old||(n(r.impact)>n(old.impact)))dedup.set(k,r);});const d=[...dedup.values()],known=d.filter(r=>r.marketplace==='amazon'),flip=d.filter(r=>r.marketplace==='flipkart'),impact=known.reduce((s,r)=>s+n(r.impact),0),products=new Set(d.map(r=>`${r.marketplace}|${r.identifier}`));
    document.getElementById('v934AnalysisKpis').innerHTML=`<div class="v93-kpi"><span>Known Monetary Impact</span><strong>${money(impact)}</strong><small>Amazon only</small></div><div class="v93-kpi"><span>Affected Products</span><strong>${nf(products.size)}</strong></div><div class="v93-kpi"><span>Amazon Impact Rows</span><strong>${nf(known.length)}</strong></div><div class="v93-kpi"><span>Flipkart Impact Rows</span><strong>${nf(flip.length)}</strong><small>Revenue unavailable — not estimated</small></div>`;
    const daily={};known.forEach(r=>daily[r.date]=(daily[r.date]||0)+n(r.impact));document.getElementById('v934AnalysisTrend').innerHTML=barHtml(daily,money);const cat={};known.forEach(r=>cat[r.category]=(cat[r.category]||0)+n(r.impact));document.getElementById('v934AnalysisCategoryChart').innerHTML=barHtml(cat,money);analysisState.rows=d;renderAnalysisTable(d,'total_impact');
  }
  async function buildLiveImpact(snaps,market,from,to){
    const orderRows=(await orders()).filter(o=>o.marketplace===market&&o.date>=from&&o.date<=to),currentFulfillment=market==='flipkart'?await flipCurrentFulfillment():new Map(),dayState=new Map(),meta=new Map();
    for(const s of snaps){const src=market==='amazon'?getSnapshotAmazonRows(s):getSnapshotFlipkartRows(s);for(const r of src||[]){if(!rawComponent(r,'live'))continue;const id=rowId(r,market);if(!id)continue;const key=`${id}|${s.reportDate}`;dayState.set(key,actionableComponent(r,'live')?'actionable':'excluded');if(!meta.has(id))meta.set(id,{identifier:id,wfSku:r.wfSku||'',marketSku:marketSku(r,market),category:r.category||'Uncategorized'});}}
    const allOrders=new Set(orderRows.map(o=>o.orderId||`${o.date}|${rowId(o,market)}|${o.azSku||o.fkSku||''}`)),actionableOrders=new Set(),excludedOrders=new Set(),per=new Map();
    for(const o of orderRows){const id=rowId(o,market),st=dayState.get(`${id}|${o.date}`);if(!st)continue;const m=meta.get(id)||{identifier:id,wfSku:o.wfSku||'',marketSku:market==='amazon'?o.azSku:o.fkSku,category:o.category||'Uncategorized'},x=per.get(id)||{...m,actionableOrders:new Set(),excludedOrders:new Set(),actionableUnits:0,excludedUnits:0,amazonRevenue:0,fulfillment:{}};const oid=o.orderId||`${o.date}|${id}|${o.azSku||o.fkSku||''}`;if(st==='actionable'){x.actionableOrders.add(oid);actionableOrders.add(oid);x.actionableUnits+=n(o.units);if(market==='amazon')x.amazonRevenue+=n(o.revenue);let f=o.fulfillment||'Unknown';if(market==='flipkart')f=currentFulfillment.get(`fsn:${o.fsn}`)||currentFulfillment.get(`sku:${o.fkSku}`)||f;x.fulfillment[f]=(x.fulfillment[f]||0)+n(o.units);}else{x.excludedOrders.add(oid);excludedOrders.add(oid);x.excludedUnits+=n(o.units);}per.set(id,x);}
    const rows=[...per.values()].map(x=>({...x,actionableOrderCount:x.actionableOrders.size,excludedOrderCount:x.excludedOrders.size,fulfillmentText:Object.entries(x.fulfillment).map(([k,v])=>`${k}: ${nf(v)}`).join(' · ')||'—'}));
    return{rows,totalOrders:allOrders.size,actionableOrders:actionableOrders.size,excludedOrders:excludedOrders.size,actionableUnits:rows.reduce((s,r)=>s+r.actionableUnits,0),excludedUnits:rows.reduce((s,r)=>s+r.excludedUnits,0),amazonRevenue:rows.reduce((s,r)=>s+r.amazonRevenue,0)};
  }
  function renderLiveImpact(data,market){
    const card=document.getElementById('v934LiveImpactCard');card.hidden=false;const cat=document.getElementById('v934AnalysisCategory')?.value||'all',q=String(document.getElementById('v934AnalysisSearch')?.value||'').toLowerCase();const scoped=data.rows.filter(r=>(cat==='all'||r.category===cat)&&(!q||`${r.identifier} ${r.marketSku} ${r.wfSku}`.toLowerCase().includes(q)));const ao=new Set(),eo=new Set();let actionableUnits=0,excludedUnits=0,amazonRevenue=0;scoped.forEach(r=>{r.actionableOrders?.forEach?.(x=>ao.add(x));r.excludedOrders?.forEach?.(x=>eo.add(x));actionableUnits+=n(r.actionableUnits);excludedUnits+=n(r.excludedUnits);amazonRevenue+=n(r.amazonRevenue);});const orderPct=data.totalOrders?ao.size/data.totalOrders*100:0;document.getElementById('v934LiveImpactKpis').innerHTML=`<div class="v93-kpi"><span>Orders During Actionable Disparity</span><strong>${nf(ao.size)}</strong></div><div class="v93-kpi"><span>Units During Actionable Disparity</span><strong>${nf(actionableUnits)}</strong></div><div class="v93-kpi"><span>Orders During Disparity %</span><strong>${pct(orderPct)}</strong></div><div class="v93-kpi"><span>${market==='amazon'?'Order Revenue During Disparity':'Order Revenue'}</span><strong>${market==='amazon'?money(amazonRevenue):'Unavailable'}</strong><small>${market==='flipkart'?'Flipkart Order Report has no monetary field':''}</small></div><div class="v93-kpi"><span>Exception-Excluded Orders</span><strong>${nf(eo.size)}</strong></div><div class="v93-kpi"><span>Exception-Excluded Units</span><strong>${nf(excludedUnits)}</strong></div>`;
    document.getElementById('v934LiveImpactMeta').textContent=`${analysisState.from} to ${analysisState.to}`;const fm={},cm={};scoped.forEach(r=>{Object.entries(r.fulfillment).forEach(([k,v])=>fm[k]=(fm[k]||0)+v);cm[r.category]=(cm[r.category]||0)+r.actionableOrderCount;});document.getElementById('v934LiveFulfillment').innerHTML=barHtml(fm);document.getElementById('v934LiveCategories').innerHTML=barHtml(cm);
    const cols=[['identifier',market==='amazon'?'ASIN':'FSN'],['wfSku','WF SKU'],['marketSku',market==='amazon'?'AZ SKU':'FK SKU'],['category','Category'],['actionableOrderCount','Actionable Orders'],['actionableUnits','Actionable Units'],['excludedOrderCount','Exception-Excluded Orders'],['excludedUnits','Exception-Excluded Units'],['amazonRevenue',market==='amazon'?'Amazon Order Revenue':'Revenue'],['fulfillmentText','Fulfilment']];const t=document.getElementById('v934LiveImpactTable');t.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c[1])}</th>`).join('')+'</tr></thead><tbody>'+(scoped.length?scoped.map(r=>'<tr>'+cols.map(([k])=>{let v=r[k];if(k==='amazonRevenue')v=market==='amazon'?money(v):'Unavailable';if(['identifier','wfSku','marketSku'].includes(k)&&v)return`<td><button class="v93-link-id" onclick='WakeSuiteProduct360.open(${JSON.stringify(String(v))},{context:"global"})'>${esc(v)}</button></td>`;return`<td>${esc(v??'—')}</td>`;}).join('')+'</tr>').join(''):`<tr><td colspan="${cols.length}" class="empty-row">No order overlap.</td></tr>`)+'</tbody>';
    analysisState.liveRows=scoped;
  }
  async function loadDashboardAnalysis(){
    ensureDashboardAnalysisView();const p=document.getElementById('v934AnalysisPeriod')?.value||'last7',anchor=document.getElementById('v934AnalysisTo')?.value||latest(),[from,to]=resolveRange(p,document.getElementById('v934AnalysisFrom')?.value,document.getElementById('v934AnalysisTo')?.value,anchor);analysisState.from=from;analysisState.to=to;document.getElementById('v934AnalysisFrom').value=from;document.getElementById('v934AnalysisTo').value=to;const snaps=await snapshots(from,to);let base=[];
    document.getElementById('v934LiveImpactCard').hidden=true;
    if(analysisState.focus==='price_disparity')base=priceRows(snaps,analysisState.marketplace);else if(['amazon_suppression','amazon_buybox'].includes(analysisState.focus))base=issueRows(snaps,analysisState.focus);else base=revenueRows(snaps,analysisState.marketplace);
    populateAnalysisCats(base);const rows=analysisFilter(base,analysisState.focus);analysisState.rows=rows;
    if(analysisState.focus==='price_disparity'){renderPriceAnalysis(rows);try{renderLiveImpact(await buildLiveImpact(snaps,analysisState.marketplace,from,to),analysisState.marketplace);}catch(e){console.warn('V9.3.4 live impact failed',e);}}
    else if(analysisState.focus==='total_impact')renderRevenueAnalysis(rows);else renderIssueAnalysis(rows,analysisState.focus);
  }
  function analysisLabels(m,focus){if(focus==='price_disparity')return[`${m==='amazon'?'Amazon':'Flipkart'} · Price Disparity Analysis`,'Actionable vs exception-excluded pricing issues, trends, category contribution and exact-date Live Price Disparity order impact.'];if(focus==='amazon_suppression')return['Amazon · ASIN Suppression Analysis','Suppression trend, affected ASINs, category contribution and revenue exposure. Operational actions remain in Suppression Management.'];if(focus==='amazon_buybox')return['Amazon · Buy Box Analysis','Buy Box suppression trend, affected ASINs, category contribution and revenue exposure.'];return[`${m==='combined'?'Combined':m==='amazon'?'Amazon':'Flipkart'} · Revenue Impact Analysis`,m==='flipkart'?'Flipkart order/sales volume is available, but monetary revenue impact is unavailable from the supplied Order Report and is not estimated.':'Known actionable monetary exposure, deduplicated at product/day level. Flipkart monetary impact is not estimated.'];}
  async function openDashboardAnalysis(market,focus,ctx={}){ensureDashboardAnalysisView();analysisState.marketplace=market;analysisState.focus=focus;analysisState.pendingCategory=ctx.category&&ctx.category!=='all'?ctx.category:'';wakeSuiteNavigate?.('dashboardAnalysisSection');const [title,sub]=analysisLabels(market,focus);document.getElementById('v934AnalysisTitle').textContent=title;document.getElementById('v934AnalysisSubtitle').textContent=sub;const pt=document.getElementById('pageTitle');if(pt)pt.textContent=title;document.getElementById('v934AnalysisIssue').hidden=focus!=='price_disparity';document.getElementById('v934TrendTitle').textContent=focus==='price_disparity'?'Actionable Disparity Trend':focus==='total_impact'?'Known Revenue Impact Trend':focus==='amazon_buybox'?'Buy Box Suppression Trend':'ASIN Suppression Trend';setAnalysisCtx(ctx);await loadDashboardAnalysis();}
  function resetDashboardAnalysis(){document.getElementById('v934AnalysisPeriod').value='last7';document.getElementById('v934AnalysisCategory').value='all';document.getElementById('v934AnalysisIssue').value='all';document.getElementById('v934AnalysisSearch').value='';loadDashboardAnalysis();}
  function setDashboardAnalysisView(view,btn){document.querySelectorAll('[data-v934-analysis-view]').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');const charts=document.getElementById('v934AnalysisCharts'),live=document.getElementById('v934LiveImpactCard');if(charts)charts.style.display=view==='detail'?'none':'';if(live&&!live.hidden)live.style.display=view==='detail'?'none':'';}
  function analysisHistory(){if(analysisState.focus==='price_disparity')return openHistoryHub?.('pricing');if(analysisState.focus==='amazon_suppression')return openHistoryHub?.('suppression');if(analysisState.focus==='amazon_buybox')return openHistoryHub?.('buybox');return openHistoryHub?.('pricing');}
  function downloadDashboardAnalysis(){if(!analysisState.rows.length){showWakeSuiteToast?.('No analysis rows to download.','warning');return;}writeExcelReport?.(`WakeSuite_V9_3_4_${analysisState.focus}_${analysisState.marketplace}_${today()}.xlsx`,{},analysisState.rows.map(r=>({...r,raw:undefined})));}

  /* -----------------------------
     Business Insights V9.3.4
  ----------------------------- */
  let biState={type:'pricing',rows:[],from:'',to:'',compare:7,pendingCategory:''};
  function biControls(type){const p=type==='pricing';return `<div class="panel v934-business-panel"><div class="panel-title-row"><div class="v93-title-with-back"><button class="v93-back-btn" onclick="wakeSuiteBack()">← Back</button><div><h2>${p?'Pricing':'Inventory'} Insights</h2><div class="v7-muted">${p?'What happened after price changed? Order Reports drive units/orders; Amazon Order Report supplies order revenue. Observed response is not causal attribution.':'What inventory do we have, how fast is it moving, and where is the risk? Order Reports drive units/DRR; inventory snapshots drive stock position.'}</div></div></div><div class="module-actions"><button class="secondary-btn" onclick="downloadV934BusinessInsights(false)">Download Visible</button><button class="secondary-btn" onclick="downloadV934BusinessInsights(true)">Full Export</button></div></div>
    <div class="v934-business-filter-grid"><select id="v934BiMarketplace"><option value="all">All Marketplaces</option><option value="amazon">Amazon</option><option value="flipkart">Flipkart</option></select><select id="v934BiCategory"><option value="all">All Categories</option></select><select id="v934BiPeriod"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="last7" selected>Last 7 Days</option><option value="last14">Last 14 Days</option><option value="last30">Last 30 Days</option><option value="custom">Custom Range</option></select><input id="v934BiFrom" type="date"><input id="v934BiTo" type="date"><input id="v934BiSearch" type="search" placeholder="ASIN / FSN / WF SKU / AZ SKU / FK SKU">
    ${p?`<select id="v934BiCompare"><option value="7">7-day Before / After</option><option value="14">14-day Before / After</option><option value="30">30-day Before / After</option></select><select id="v934BiDirection"><option value="all">All Price Direction</option><option value="increase">Price Increased</option><option value="decrease">Price Decreased</option></select><select id="v934BiSignal"><option value="all">All Decision Signals</option><option value="positive">Positive Response</option><option value="review">Negative / Review Required</option><option value="dilution">Revenue Dilution</option><option value="inventory">Inventory-Constrained</option><option value="marketplace">Marketplace Interference</option><option value="inconclusive">Inconclusive</option></select><select id="v934BiFulfillment"><option value="all">All Fulfilment</option><option value="FBA">Amazon FBA</option><option value="FBM">Amazon FBM</option></select><select id="v934BiException"><option value="all">Any Exception Status</option><option value="active">Exception Active on Change Date</option><option value="none">No Active Exception</option></select>`:`<select id="v934BiInventoryState"><option value="all">All Inventory States</option><option value="OOS">OOS</option><option value="Critical">Critical &lt;3 days</option><option value="At Risk">At Risk 3–7 days</option><option value="Watch">Watch 7–14 days</option><option value="Healthy">Healthy &gt;14 days</option></select><select id="v934BiFulfillment"><option value="all">All Fulfilment</option><option value="FBA">Amazon FBA</option><option value="FBM">Amazon FBM</option></select><select id="v934BiGroup"><option value="category">Group By Category</option><option value="marketplace">Group By Marketplace</option><option value="fulfillment">Group By Fulfilment</option><option value="product">Group By Product</option></select>`}
    <button class="primary-btn" onclick="loadV934BusinessInsights()">Apply</button><button class="secondary-btn" onclick="resetV934BusinessInsights()">Reset</button><details class="column-picker"><summary>Columns</summary><div class="column-picker-panel"><div class="v8-column-actions"><button onclick="WakeSuiteColumns.selectAll('v934BusinessInsights')">Select All</button><button onclick="WakeSuiteColumns.clearAll('v934BusinessInsights')">Clear All</button><button onclick="WakeSuiteColumns.setDefault('v934BusinessInsights')">Set as Default</button><button onclick="WakeSuiteColumns.restoreDefault('v934BusinessInsights')">Restore Default</button></div><div id="v934BiColumns"></div></div></details></div>
    <div class="v8-view-switch" role="group"><button class="v8-view-btn active" data-v934-bi-view="insights" onclick="setV934BusinessInsightsView('insights',this)">Insights</button><button class="v8-view-btn" data-v934-bi-view="detail" onclick="setV934BusinessInsightsView('detail',this)">Detailed Data</button><button class="v8-view-btn" data-v934-bi-view="history" onclick="openV934BusinessHistory()">History</button></div>
    <div class="v93-kpi-grid v934-bi-kpis" id="v934BiKpis"></div><div class="insights-chart-grid" id="v934BiCharts"><div class="analytics-card"><div class="analytics-card-head"><strong id="v934BiChartTitle">Analysis</strong><span>Selected scope</span></div><div id="v934BiChart"></div></div><div class="analytics-card"><div class="analytics-card-head"><strong id="v934BiCategoryTitle">Category Analysis</strong><span>Selected scope</span></div><div id="v934BiCategoryChart"></div></div></div><div class="analytics-card"><div class="analytics-card-head"><strong id="v934BiTableTitle">Detailed Analysis</strong><span id="v934BiRowInfo">0 rows</span></div><div class="table-wrap"><table class="result-table" id="v934BiTable"></table></div></div></div>`;}
  function normalizeSnapshotRows(snaps,marketFilter='all'){
    const out=[];for(const s of snaps){if(marketFilter==='all'||marketFilter==='amazon')for(const r of getSnapshotAmazonRows(s)||[]){out.push({date:s.reportDate,marketplace:'amazon',category:r.category||'Uncategorized',wfSku:r.wfSku||'',marketSku:r.azSku||'',identifier:r.asin||'',wfPrice:n(r.wfPrice),inventory:r.inventory===null||r.inventory===undefined?null:n(r.inventory),listingStatus:r.status||r.listingStatus||'',raw:r});}if(marketFilter==='all'||marketFilter==='flipkart')for(const r of getSnapshotFlipkartRows(s)||[]){out.push({date:s.reportDate,marketplace:'flipkart',category:r.category||'Uncategorized',wfSku:r.wfSku||'',marketSku:r.fkSku||'',identifier:r.fsn||'',wfPrice:n(r.wfPrice),inventory:r.inventory===null||r.inventory===undefined?null:n(r.inventory),listingStatus:r.status||r.listingStatus||'',raw:r});}}return out;
  }
  function productKey(r){return `${r.marketplace}|${r.marketSku}|${r.identifier}|${r.wfSku}`;}
  function orderMatchesProduct(o,r){if(o.marketplace!==r.marketplace)return false;if(r.marketplace==='amazon')return (r.marketSku&&String(o.azSku)===String(r.marketSku))||(!r.marketSku&&r.identifier&&String(o.asin)===String(r.identifier));return (r.identifier&&String(o.fsn)===String(r.identifier))||(r.marketSku&&String(o.fkSku)===String(r.marketSku));}
  function aggregateOrders(os,from,to,market){const x=os.filter(o=>o.date>=from&&o.date<=to),orderSet=new Set(x.map(o=>o.orderId).filter(Boolean)),units=x.reduce((s,o)=>s+n(o.units),0),revenue=market==='amazon'?x.reduce((s,o)=>s+n(o.revenue),0):null,days=new Set(x.map(o=>o.date)).size;return{orders:orderSet.size||x.length,units,revenue,orderDays:days,fulfillment:fulfillmentSummary(x),rows:x};}
  async function activeExceptions(){try{await v7EnsurePricingExceptionsLoaded?.(true);return typeof v7PricingExceptions!=='undefined'?(v7PricingExceptions||[]):[];}catch(_){return[];}}
  function exMatches(ex,r,date){if(String(ex.status||'active').toLowerCase()==='removed')return false;if(ex.effectiveFrom&&ex.effectiveFrom>date)return false;if(ex.effectiveTo&&ex.effectiveTo<date)return false;const m=String(ex.marketplace||'').toLowerCase();if(m&&m!=='all'&&m!==r.marketplace)return false;return [ex.wfSku&&r.wfSku&&String(ex.wfSku)===String(r.wfSku),ex.azSku&&r.marketSku&&r.marketplace==='amazon'&&String(ex.azSku)===String(r.marketSku),ex.asin&&r.identifier&&r.marketplace==='amazon'&&String(ex.asin)===String(r.identifier),ex.fkSku&&r.marketSku&&r.marketplace==='flipkart'&&String(ex.fkSku)===String(r.marketSku),ex.fsn&&r.identifier&&r.marketplace==='flipkart'&&String(ex.fsn)===String(r.identifier)].some(Boolean);}
  function issueContext(snaps,r,from,to){let oos=false,supp=false,buy=false;for(const s of snaps){if(s.reportDate<from||s.reportDate>to)continue;const src=r.marketplace==='amazon'?getSnapshotAmazonRows(s):getSnapshotFlipkartRows(s);const pr=(src||[]).find(x=>(r.marketSku&&marketSku(x,r.marketplace)===r.marketSku)||(r.identifier&&rowId(x,r.marketplace)===r.identifier));if(pr&&pr.inventory!==null&&pr.inventory!==undefined&&n(pr.inventory)<=0)oos=true;if(r.marketplace==='amazon'&&r.identifier){supp=supp||(getSnapshotAmazonIssueRows(s,'amazonSuppressions')||[]).some(x=>String(x.asin||'')===String(r.identifier));buy=buy||(getSnapshotAmazonIssueRows(s,'amazonBuyBox')||[]).some(x=>String(x.asin||'')===String(r.identifier));}}
    return{oos,supp,buy};
  }
  function changePct(a,b){if(a===null||b===null||!Number.isFinite(Number(a))||!Number.isFinite(Number(b)))return null;if(Number(a)===0)return Number(b)===0?0:null;return(Number(b)-Number(a))/Math.abs(Number(a))*100;}
  function pricingSignal(row){
    const {pricePct,unitsPct,revenuePct,oos,supp,buy,marketplace,beforeUnits,afterUnits}=row;
    if(oos)return'Inventory Constraint';if(marketplace==='amazon'&&(supp||buy))return'Marketplace Interference';if(beforeUnits===0&&afterUnits===0)return'Inconclusive';
    if(marketplace==='amazon'){
      if(revenuePct===null)return'Inconclusive';
      if(pricePct>0&&revenuePct<0)return'Review Price Increase';
      if(pricePct>0&&revenuePct>=0)return'Positive Price Response';
      if(pricePct<0&&unitsPct!==null&&unitsPct>0&&revenuePct>=0)return'Positive Price Response';
      if(pricePct<0&&unitsPct!==null&&unitsPct>0&&revenuePct<0)return'Revenue Dilution';
      if(pricePct<0&&revenuePct<0)return'Review Required';
      return Math.abs(revenuePct)<=5?'Inconclusive':'Review Required';
    }
    if(unitsPct===null)return'Inconclusive';if(pricePct<0&&unitsPct>5)return'Positive Price Response';if(pricePct>0&&unitsPct<-5)return'Review Price Increase';return'Inconclusive';
  }
  async function pricingRows934(from,to,compare,marketFilter){
    const extFrom=shift(from,-compare),extTo=shift(to,compare),snaps=await snapshots(extFrom,extTo),raw=normalizeSnapshotRows(snaps,marketFilter),os=await orders(),exceptions=await activeExceptions(),groups=new Map();raw.sort((a,b)=>a.date.localeCompare(b.date)).forEach(r=>{const k=productKey(r);(groups.get(k)||groups.set(k,[]).get(k)).push(r);});const out=[];
    for(const hist of groups.values()){for(let i=1;i<hist.length;i++){const prev=hist[i-1],chg=hist[i];if(chg.date<from||chg.date>to||chg.wfPrice===prev.wfPrice)continue;const beforeFrom=shift(chg.date,-compare),beforeTo=shift(chg.date,-1),afterFrom=shift(chg.date,1),afterTo=shift(chg.date,compare),productOrders=os.filter(o=>orderMatchesProduct(o,chg)),before=aggregateOrders(productOrders,beforeFrom,beforeTo,chg.marketplace),after=aggregateOrders(productOrders,afterFrom,afterTo,chg.marketplace),ctx=issueContext(snaps,chg,afterFrom,afterTo),pricePct=changePct(prev.wfPrice,chg.wfPrice),unitsPct=changePct(before.units,after.units),revenuePct=chg.marketplace==='amazon'?changePct(before.revenue,after.revenue):null,exceptionActive=exceptions.some(ex=>exMatches(ex,chg,chg.date)),ff=after.fulfillment||before.fulfillment;let currentFulfillment='';if(chg.marketplace==='flipkart'){const fm=await flipCurrentFulfillment();currentFulfillment=fm.get(`fsn:${chg.identifier}`)||fm.get(`sku:${chg.marketSku}`)||'';}const row={...chg,changeDate:chg.date,oldPrice:prev.wfPrice,newPrice:chg.wfPrice,pricePct,beforeOrders:before.orders,afterOrders:after.orders,beforeUnits:before.units,afterUnits:after.units,unitsPct,beforeRevenue:before.revenue,afterRevenue:after.revenue,revenuePct,fulfillment:ff,currentFulfillment,oos:ctx.oos,supp:ctx.supp,buy:ctx.buy,exceptionActive,compareDays:compare};row.signal=pricingSignal(row);out.push(row);}}
    return out;
  }
  function sellingDays(hist,from,to){const x=hist.filter(r=>r.date>=from&&r.date<=to);const inStock=x.filter(r=>r.inventory!==null&&r.inventory>0).length;return inStock;}
  async function inventoryRows934(from,to,marketFilter){
    const loadFrom=(from<shift(to,-29)?from:shift(to,-29)),snaps=await snapshots(loadFrom,to),raw=normalizeSnapshotRows(snaps,marketFilter),os=await orders(),ff=await flipCurrentFulfillment(),groups=new Map();raw.sort((a,b)=>a.date.localeCompare(b.date)).forEach(r=>{const k=productKey(r);(groups.get(k)||groups.set(k,[]).get(k)).push(r);});const out=[];
    for(const hist of groups.values()){const r=hist.at(-1);if(!r||r.date>to)continue;const selectedHist=hist.filter(x=>x.date>=from&&x.date<=to);if(!selectedHist.length)continue;const productOrders=os.filter(o=>orderMatchesProduct(o,r)),selectedOrders=aggregateOrders(productOrders,from,to,r.marketplace),opening=selectedHist[0].inventory,closing=selectedHist.at(-1).inventory,sd=sellingDays(hist,from,to)||selectedOrders.orderDays,dr=sd?selectedOrders.units/sd:0;const drrWindow=(daysN)=>{const f=shift(to,-daysN+1),o=aggregateOrders(productOrders,f,to,r.marketplace),s=sellingDays(hist,f,to)||o.orderDays;return s?o.units/s:0;};const drr7=drrWindow(7),drr14=drrWindow(14),drr30=drrWindow(30),doc=closing!==null&&dr>0?closing/dr:null;let state=closing!==null&&closing<=0?'OOS':doc===null?'No Velocity':doc<3?'Critical':doc<=7?'At Risk':doc<=14?'Watch':'Healthy';const observed=selectedHist.filter(x=>x.inventory!==null).length,oosDays=selectedHist.filter(x=>x.inventory!==null&&x.inventory<=0).length,oosPct=observed?oosDays/observed*100:null;let movement='No Change',restocked=false;if(selectedHist.length>1){const a=selectedHist[0].inventory,b=selectedHist.at(-1).inventory;if(a!==null&&b!==null){if(a<=0&&b>0){movement='Restocked';restocked=true;}else if(a>0&&b<=0)movement='Became OOS';else if(b>a)movement='Stock Increased';else if(b<a)movement='Stock Decreased';}}for(let i=1;i<selectedHist.length;i++)if(n(selectedHist[i-1].inventory)<=0&&n(selectedHist[i].inventory)>0)restocked=true;const depletion=!restocked&&opening>0?selectedOrders.units/opening*100:null;const trailingOrders=aggregateOrders(productOrders,loadFrom,to,r.marketplace),trailingSellingDays=sellingDays(hist,loadFrom,to)||trailingOrders.orderDays,revenuePerDay=r.marketplace==='amazon'&&trailingSellingDays?trailingOrders.revenue/trailingSellingDays:null,potentialLoss=state==='OOS'&&r.marketplace==='amazon'?revenuePerDay:null,orderFulfillment=selectedOrders.fulfillment,currentFulfillment=r.marketplace==='flipkart'?(ff.get(`fsn:${r.identifier}`)||ff.get(`sku:${r.marketSku}`)||'Unknown'):'',possibleOverstock=doc!==null&&doc>30&&n(closing)>20;const why=state==='OOS'?`OOS ${oosDays}/${observed||0} observed days`:['Critical','At Risk'].includes(state)?`Low days of cover (${doc===null?'—':doc.toFixed(1)})`:possibleOverstock?`High cover (${doc.toFixed(1)} days)`:'No immediate inventory risk';out.push({...r,openingInventory:opening,closingInventory:closing,unitsSold:selectedOrders.units,sellingDays:sd,drr:dr,drr7,drr14,drr30,daysCover:doc,state,oosDays,oosPct,stockMovement:movement,inventoryDepletionPct:depletion,sellThrough:'Unavailable — receipts/inbound source not provided',revenuePerDay,potentialOosRevenueLoss:potentialLoss,possibleOverstock,orderFulfillment,currentFulfillment,why});}
    return out;
  }
  function populateBiCats(rows){const e=document.getElementById('v934BiCategory');if(!e)return;const desired=biState.pendingCategory||e.value||'all',cats=unique(rows.map(r=>r.category)).sort();e.innerHTML='<option value="all">All Categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');e.value=cats.includes(desired)?desired:'all';biState.pendingCategory='';}
  function biCommon(rows){const cat=document.getElementById('v934BiCategory')?.value||'all',q=String(document.getElementById('v934BiSearch')?.value||'').toLowerCase(),ful=document.getElementById('v934BiFulfillment')?.value||'all';return rows.filter(r=>(cat==='all'||r.category===cat)&&(!q||`${r.identifier} ${r.marketSku} ${r.wfSku}`.toLowerCase().includes(q))&&(ful==='all'||String(r.fulfillment||r.orderFulfillment||'').includes(ful)));}
  function pricingFilter934(rows){const dir=document.getElementById('v934BiDirection')?.value||'all',sig=document.getElementById('v934BiSignal')?.value||'all',ex=document.getElementById('v934BiException')?.value||'all';return rows.filter(r=>(dir==='all'||(dir==='increase'&&r.pricePct>0)||(dir==='decrease'&&r.pricePct<0))&&(ex==='all'||(ex==='active'&&r.exceptionActive)||(ex==='none'&&!r.exceptionActive))&&(sig==='all'||(sig==='positive'&&/Positive/.test(r.signal))||(sig==='review'&&/Review/.test(r.signal))||(sig==='dilution'&&/Dilution/.test(r.signal))||(sig==='inventory'&&/Inventory Constraint/.test(r.signal))||(sig==='marketplace'&&/Marketplace Interference/.test(r.signal))||(sig==='inconclusive'&&/Inconclusive/.test(r.signal))));}
  function inventoryFilter934(rows){const st=document.getElementById('v934BiInventoryState')?.value||'all';return rows.filter(r=>st==='all'||r.state===st);}
  function renderPricingBi(rows){
    const count=s=>rows.filter(r=>r.signal===s).length;document.getElementById('v934BiKpis').innerHTML=`<div class="v93-kpi"><span>Products with Price Changes</span><strong>${nf(rows.length)}</strong></div><div class="v93-kpi"><span>Price Increased</span><strong>${nf(rows.filter(r=>r.pricePct>0).length)}</strong></div><div class="v93-kpi"><span>Price Decreased</span><strong>${nf(rows.filter(r=>r.pricePct<0).length)}</strong></div><div class="v93-kpi"><span>Positive Response</span><strong>${nf(rows.filter(r=>/Positive/.test(r.signal)).length)}</strong></div><div class="v93-kpi"><span>Negative / Review Required</span><strong>${nf(rows.filter(r=>/Review/.test(r.signal)).length)}</strong></div><div class="v93-kpi"><span>Revenue Dilution</span><strong>${nf(count('Revenue Dilution'))}</strong></div><div class="v93-kpi"><span>Inventory-Constrained</span><strong>${nf(count('Inventory Constraint'))}</strong></div><div class="v93-kpi"><span>Marketplace Interference</span><strong>${nf(count('Marketplace Interference'))}</strong></div><div class="v93-kpi"><span>Inconclusive</span><strong>${nf(count('Inconclusive'))}</strong></div>`;
    const sig={};rows.forEach(r=>sig[r.signal]=(sig[r.signal]||0)+1);document.getElementById('v934BiChartTitle').textContent='Decision Signal Mix';document.getElementById('v934BiChart').innerHTML=barHtml(sig);const cat={};rows.forEach(r=>cat[r.category]=(cat[r.category]||0)+1);document.getElementById('v934BiCategoryChart').innerHTML=barHtml(cat);renderBiTable(rows,'pricing');
  }
  function renderInventoryBi(rows){
    const oos=rows.filter(r=>r.state==='OOS'),high=oos.filter(r=>r.marketplace==='amazon'&&n(r.revenuePerDay)>=10000),loss=rows.filter(r=>r.marketplace==='amazon').reduce((s,r)=>s+n(r.potentialOosRevenueLoss),0);document.getElementById('v934BiKpis').innerHTML=`<div class="v93-kpi"><span>Current OOS</span><strong>${nf(oos.length)}</strong></div><div class="v93-kpi"><span>High-Revenue OOS</span><strong>${nf(high.length)}</strong></div><div class="v93-kpi"><span>Critical</span><strong>${nf(rows.filter(r=>r.state==='Critical').length)}</strong></div><div class="v93-kpi"><span>At Risk</span><strong>${nf(rows.filter(r=>r.state==='At Risk').length)}</strong></div><div class="v93-kpi"><span>Watch</span><strong>${nf(rows.filter(r=>r.state==='Watch').length)}</strong></div><div class="v93-kpi"><span>Healthy</span><strong>${nf(rows.filter(r=>r.state==='Healthy').length)}</strong></div><div class="v93-kpi"><span>Potential OOS Revenue Loss</span><strong>${money(loss)}</strong><small>Amazon monetary source only</small></div><div class="v93-kpi"><span>Possible Overstock</span><strong>${nf(rows.filter(r=>r.possibleOverstock).length)}</strong></div>`;
    const group=document.getElementById('v934BiGroup')?.value||'category',map={};rows.forEach(r=>{const k=group==='marketplace'?(r.marketplace==='amazon'?'Amazon':'Flipkart'):group==='fulfillment'?(r.currentFulfillment||r.orderFulfillment||'Unknown'):group==='product'?(r.wfSku||r.identifier):r.category;map[k]=(map[k]||0)+(r.state==='OOS'||r.state==='Critical'||r.state==='At Risk'?1:0);});document.getElementById('v934BiChartTitle').textContent='Inventory Risk by '+(group==='product'?'Product':group[0].toUpperCase()+group.slice(1));document.getElementById('v934BiChart').innerHTML=barHtml(map);const cat={};rows.forEach(r=>cat[r.category]=(cat[r.category]||0)+n(r.unitsSold));document.getElementById('v934BiCategoryTitle').textContent='Units Sold by Category';document.getElementById('v934BiCategoryChart').innerHTML=barHtml(cat);renderBiTable(rows,'inventory');
  }
  function renderBiTable(rows,type){
    const cols=type==='pricing'?[['marketplace','Marketplace'],['category','Category'],['wfSku','WF SKU'],['marketSku','Marketplace SKU'],['identifier','ASIN / FSN'],['changeDate','Change Date'],['compareDays','Before / After Days'],['oldPrice','Old Price'],['newPrice','New Price'],['pricePct','Price Change %'],['beforeOrders','Orders Before'],['afterOrders','Orders After'],['beforeUnits','Units Before'],['afterUnits','Units After'],['unitsPct','Observed Units Change %'],['beforeRevenue','Revenue Before'],['afterRevenue','Revenue After'],['revenuePct','Observed Revenue Change %'],['fulfillment','Order Fulfilment'],['currentFulfillment','Flipkart Current Fulfillment By'],['oos','Inventory Interference'],['supp','Suppression Interference'],['buy','Buy Box Interference'],['exceptionActive','Exception Active'],['signal','Decision Signal']]:[['marketplace','Marketplace'],['category','Category'],['wfSku','WF SKU'],['marketSku','Marketplace SKU'],['identifier','ASIN / FSN'],['date','As Of'],['openingInventory','Opening Stock'],['closingInventory','Closing Stock'],['unitsSold','Units Sold'],['sellingDays','Selling Days'],['drr','DRR'],['drr7','7-Day DRR'],['drr14','14-Day DRR'],['drr30','30-Day DRR'],['daysCover','Days of Cover'],['state','Inventory State'],['stockMovement','Stock Movement'],['oosDays','OOS Days'],['oosPct','OOS %'],['inventoryDepletionPct','Inventory Depletion %'],['sellThrough','True Sell-Through'],['revenuePerDay','Revenue / Day'],['potentialOosRevenueLoss','Potential OOS Revenue Loss'],['possibleOverstock','Possible Overstock'],['orderFulfillment','Actual Order Fulfilment'],['currentFulfillment','Flipkart Current Fulfillment By'],['why','Why?']];
    const table=document.getElementById('v934BiTable');table.dataset.wsColumnTable='v934BusinessInsights';table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c[1])}</th>`).join('')+'</tr></thead><tbody>'+(rows.length?rows.slice(0,4000).map(r=>'<tr>'+cols.map(([k])=>{let v=r[k];if(['oldPrice','newPrice','beforeRevenue','afterRevenue','revenuePerDay','potentialOosRevenueLoss'].includes(k))v=(r.marketplace==='flipkart'&&['beforeRevenue','afterRevenue','revenuePerDay','potentialOosRevenueLoss'].includes(k))?'Unavailable':money(v);if(['pricePct','unitsPct','revenuePct','oosPct','inventoryDepletionPct'].includes(k))v=v===null?'—':pct(v);if(['drr','drr7','drr14','drr30','daysCover'].includes(k))v=v===null?'—':Number(v).toFixed(2);if(typeof v==='boolean')v=v?'Yes':'No';if(k==='marketplace')v=r.marketplace==='amazon'?'Amazon':'Flipkart';if(['wfSku','marketSku','identifier'].includes(k)&&v)return`<td><button class="v93-link-id" onclick='WakeSuiteProduct360.open(${JSON.stringify(String(v))},{context:${JSON.stringify(type+'Insights')},date:${JSON.stringify(r.date||r.changeDate)}})'>${esc(v)}</button></td>`;return`<td>${esc(v??'—')}</td>`;}).join('')+'</tr>').join(''):`<tr><td colspan="${cols.length}" class="empty-row">No Business Insights rows match the selected controls.</td></tr>`)+'</tbody>';document.getElementById('v934BiRowInfo').textContent=`${nf(rows.length)} rows`;safeCall(window.WakeSuiteColumns?.register,'v934BusinessInsights',cols.map(([key,label])=>({key,label})),cols.map(x=>x[0]),'v934BiColumns');
  }
  async function loadBusinessInsights934(){
    const period=document.getElementById('v934BiPeriod')?.value||'last7',anchor=document.getElementById('v934BiTo')?.value||latest(),[from,to]=resolveRange(period,document.getElementById('v934BiFrom')?.value,document.getElementById('v934BiTo')?.value,anchor);biState.from=from;biState.to=to;document.getElementById('v934BiFrom').value=from;document.getElementById('v934BiTo').value=to;const market=document.getElementById('v934BiMarketplace')?.value||'all';let base=[];
    if(biState.type==='pricing'){const compare=Number(document.getElementById('v934BiCompare')?.value||7);biState.compare=compare;base=await pricingRows934(from,to,compare,market);}else base=await inventoryRows934(from,to,market);populateBiCats(base);base=biCommon(base);base=biState.type==='pricing'?pricingFilter934(base):inventoryFilter934(base);biState.rows=base;if(biState.type==='pricing')renderPricingBi(base);else renderInventoryBi(base);
  }
  async function openBusinessInsights934(type='pricing',ctx={}){biState.type=type==='inventory'?'inventory':'pricing';biState.pendingCategory=ctx.category&&ctx.category!=='all'?ctx.category:'';window.WakeSuiteBusinessInsightsType=biState.type;wakeSuiteNavigate?.('businessInsightsSection');document.querySelectorAll('[data-business-tab]').forEach(b=>b.classList.toggle('active',b.dataset.businessTab===biState.type));document.getElementById('businessInsightsContent').innerHTML=biControls(biState.type);const pt=document.getElementById('pageTitle');if(pt)pt.textContent=`${biState.type==='pricing'?'Pricing':'Inventory'} Insights`;if(ctx.marketplace&&ctx.marketplace!=='all')document.getElementById('v934BiMarketplace').value=ctx.marketplace;if(ctx.category)document.getElementById('v934BiCategory').value=ctx.category;if(ctx.period)document.getElementById('v934BiPeriod').value=normalizePeriod(ctx.period);if(ctx.from)document.getElementById('v934BiFrom').value=ctx.from;if(ctx.to)document.getElementById('v934BiTo').value=ctx.to;await loadBusinessInsights934();}
  function resetBusinessInsights934(){document.getElementById('v934BiMarketplace').value='all';document.getElementById('v934BiCategory').value='all';document.getElementById('v934BiPeriod').value='last7';document.getElementById('v934BiSearch').value='';openBusinessInsights934(biState.type,{period:'last7'});}
  function setBiView(view,btn){document.querySelectorAll('[data-v934-bi-view]').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');const charts=document.getElementById('v934BiCharts');if(charts)charts.style.display=view==='detail'?'none':'';document.getElementById('v934BiTableTitle').textContent=view==='detail'?'Detailed Data':biState.type==='pricing'?'Pricing Decision Detail':'Inventory Decision Detail';}
  function biHistory(){return biState.type==='pricing'?openPricingHistory?.():openInventoryHistory?.();}
  function downloadBi(){if(!biState.rows.length){showWakeSuiteToast?.('No Business Insights rows to download.','warning');return;}writeExcelReport?.(`WakeSuite_V9_3_4_${biState.type}_Insights_${today()}.xlsx`,{},biState.rows.map(r=>({...r,raw:undefined})));}

  /* -----------------------------
     Routing + dashboard monetary guardrails
  ----------------------------- */
  const baseDashboardRoute=window.openDashboardDestination;
  function routeDashboard(m,focus,extra={}){const c={...dashboardContext(),...extra};if(focus==='parity')return openPriceParityReport?.(m,c);if(focus==='price_disparity')return openDashboardAnalysis(m,'price_disparity',c);if(focus==='amazon_suppression')return openDashboardAnalysis('amazon','amazon_suppression',c);if(focus==='amazon_buybox')return openDashboardAnalysis('amazon','amazon_buybox',c);if(focus==='pricing_insights')return openBusinessInsights934('pricing',{...c,marketplace:m});if(focus==='inventory')return openBusinessInsights934('inventory',{...c,marketplace:m});if(focus==='total_impact')return openDashboardAnalysis(m,'total_impact',c);return baseDashboardRoute?.(m,focus,extra);}
  function routeDashboardCategory(m,focus,category){return routeDashboard(m,focus,{category});}
  function patchDashboardMoney(){
    const ids=['flipkartPriceImpact','flipkartTotalImpact','flipkartTotalImpactBottom'];ids.forEach(id=>{const e=document.getElementById(id);if(e){e.textContent='Unavailable';e.title='Flipkart Order Report contains no monetary revenue field; WakeSuite does not estimate revenue.';}});const l=document.getElementById('flipkartPriceImpactLabel');if(l)l.textContent='Revenue unavailable';const tl=document.getElementById('flipkartTotalImpactLabel');if(tl)tl.textContent='No approved revenue source';const ex=document.getElementById('flipkartTotalExclusionDetail');if(ex)ex.textContent='Orders / units available · monetary impact unavailable';const combined=document.getElementById('marketplaceTotalImpact'),am=document.getElementById('amazonTotalImpactBottom');if(combined&&am&&am.textContent&&am.textContent!=='—')combined.textContent=am.textContent;const label=combined?.parentElement?.querySelector('span');if(label)label.textContent='Known Marketplace Rev Impact · Amazon Only';
  }
  const baseDashLoad=window.loadDashboardOverview;if(typeof baseDashLoad==='function')window.loadDashboardOverview=async function(){const r=await baseDashLoad.apply(this,arguments);patchDashboardMoney();return r;};

  /* -----------------------------
     Data Center source naming correction only.
     UI/dropdown layout is intentionally untouched.
  ----------------------------- */
  function patchSourceLabels(){
    if(window.WakeSuiteUploadSources?.amazon_order_report)WakeSuiteUploadSources.amazon_order_report.label='Amazon Order Report';
    if(window.WakeSuiteUploadSources?.flipkart_order_report)WakeSuiteUploadSources.flipkart_order_report.label='Flipkart Order Report';
  }

  /* Export V9.3.4 public functions */
  Object.assign(window,{
    openDashboardDestination:routeDashboard,openDashboardCategoryDestination:routeDashboardCategory,
    openV934DashboardAnalysis:openDashboardAnalysis,loadV934DashboardAnalysis:loadDashboardAnalysis,resetV934DashboardAnalysis:resetDashboardAnalysis,setV934DashboardAnalysisView:setDashboardAnalysisView,openV934DashboardAnalysisHistory:analysisHistory,downloadV934DashboardAnalysis:downloadDashboardAnalysis,
    openBusinessInsights:openBusinessInsights934,loadV934BusinessInsights:loadBusinessInsights934,loadBusinessInsightsV93:loadBusinessInsights934,resetV934BusinessInsights:resetBusinessInsights934,resetBusinessInsightsV93:resetBusinessInsights934,setV934BusinessInsightsView:setBiView,setBusinessInsightsView:setBiView,openV934BusinessHistory:biHistory,openBusinessHistory:biHistory,downloadV934BusinessInsights:downloadBi,downloadBusinessInsights:downloadBi
  });
  window.WakeSuiteV934={openDashboardAnalysis,loadDashboardAnalysis,openBusinessInsights:openBusinessInsights934,loadBusinessInsights:loadBusinessInsights934,patchDashboardMoney};
  window.WakeSuiteModules?.register('v934DashboardAnalysis',{open:openDashboardAnalysis,load:loadDashboardAnalysis});
  window.WakeSuiteModules?.register('businessInsightsV934',{open:openBusinessInsights934,load:loadBusinessInsights934});

  ensureDashboardAnalysisView();patchSourceLabels();patchDashboardMoney();
  document.addEventListener('DOMContentLoaded',()=>{ensureDashboardAnalysisView();patchSourceLabels();patchDashboardMoney();});
})();
