/* WakeSuite V9.3 · Dashboard native report routing + Revenue Impact */
(function(){
  let impactMarket='combined',impactRows=[];
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v??''):String(v??'');
  const money=v=>typeof formatINR==='function'?formatINR(Number(v)||0):String(Number(v)||0);
  const nf=v=>typeof formatNumber==='function'?formatNumber(Number(v)||0):String(Number(v)||0);
  function ctx(){const p=document.getElementById('dashboardPeriod')?.value||'today';return{period:p==='last15'?'last14':p,rawPeriod:p,from:document.getElementById('dashboardFromDate')?.value||'',to:document.getElementById('dashboardToDate')?.value||'',date:document.getElementById('dashboardDate')?.value||document.getElementById('dashboardToDate')?.value||'',category:document.getElementById('dashboardCategory')?.value||'all',marketplace:document.getElementById('dashboardMarketplace')?.value||'all'};}
  function historicalPeriod(p){return({today:'today',yesterday:'yesterday',last7:'last7',last14:'last15',last15:'last15',last30:'last30',custom:'custom'}[p]||'today');}
  async function openHistorical(key,c){window.WakeSuiteNavigation?.stack.push(window.WakeSuiteNavigation.capture());openHistoricalModule(key);const pp=document.getElementById('reportPeriod');if(pp)pp.value=historicalPeriod(c.rawPeriod||c.period);const f=document.getElementById('reportFromDate'),t=document.getElementById('reportToDate'),cat=document.getElementById('reportCategory');if(f&&c.from)f.value=c.from;if(t&&c.to)t.value=c.to;if(cat&&c.category)cat.value=c.category;await loadHistoricalModule?.();}
  function openPriceDisparity(m,c){window.WakeSuiteNavigation?.stack.push(window.WakeSuiteNavigation.capture());openDashboardPriceView(m);setTimeout(()=>{const cat=document.getElementById('reportCategory');if(cat&&c.category)cat.value=c.category;},0);}
  function openExceptions(m,c){openPricingExceptions?.('manager',{marketplace:m,category:c.category,from:c.from,to:c.to,status:'active'});}
  async function openSuppressionManagementOverride(c){window.WakeSuiteNavigation?.stack.push(window.WakeSuiteNavigation.capture());showView('suppressionManagementSection');const status=document.getElementById('suppressionManagementStatus');if(status){const opt=[...status.options].find(o=>/overrid/i.test(o.value)||/overrid/i.test(o.text));if(opt)status.value=opt.value;}const cat=document.getElementById('suppressionManagementCategory');if(cat&&c.category)cat.value=c.category;const p=document.getElementById('suppressionManagementPeriod');if(p)p.value=historicalPeriod(c.rawPeriod);const f=document.getElementById('suppressionManagementFromDate'),t=document.getElementById('suppressionManagementToDate');if(f&&c.from)f.value=c.from;if(t&&c.to)t.value=c.to;await loadSuppressionManagement?.();}
  function route(m,focus,extra={}){const c={...ctx(),...extra};if(focus==='parity')return openPriceParityReport(m,c);if(focus==='price_disparity')return openPriceDisparity(m,c);if(focus==='amazon_suppression')return openHistorical('amazon_suppression',c);if(focus==='amazon_buybox')return openHistorical('amazon_buybox',c);if(focus==='inventory')return openBusinessInsights?.('inventory',{...c,source:'dashboard'});if(focus==='total_impact')return openRevenueImpactReport(m,c);if(focus==='exceptions')return openExceptions(m,c);if(focus==='overridden')return openSuppressionManagementOverride(c);}
  function categoryRoute(m,focus,category){route(m,focus,{category});}
  function range(){const p=document.getElementById('revenueImpactPeriod')?.value||'today';const end=document.getElementById('revenueImpactToDate')?.value||document.getElementById('latestCompletedDateDisplay')?.textContent?.replace('As of ','')||todayIso();let from=end,to=end;const d=n=>{const x=new Date(`${end}T00:00:00`);x.setDate(x.getDate()+n);return localIsoDate(x)};if(p==='yesterday')from=to=d(-1);else if(p==='last7')from=d(-6);else if(p==='last14')from=d(-13);else if(p==='last30')from=d(-29);else if(p==='custom'){from=document.getElementById('revenueImpactFromDate')?.value||end;to=document.getElementById('revenueImpactToDate')?.value||end;}document.getElementById('revenueImpactFromDate').value=from;document.getElementById('revenueImpactToDate').value=to;return[from,to];}
  function impactLine(snapshot,m){const out=[];const add=(r,type,impact)=>{const id=m==='amazon'?r.asin:r.fsn;if(!id||!Number(impact))return;out.push({date:snapshot.reportDate,marketplace:m,category:r.category||'',wfSku:r.wfSku||'',marketSku:m==='amazon'?(r.azSku||''):(r.fkSku||''),identifier:id,issue:type,impact:Number(impact)||0});};const prices=v4PriceObservations(snapshot,m,'all')||[];prices.filter(r=>r.parityStatus==='Disparity').forEach(r=>add(r,String(r.priceSignal||'Price').toLowerCase()==='live'?'Live Price':'Listing Price',r.priceImpact));if(m==='amazon'){getSnapshotAmazonIssueRows(snapshot,'amazonSuppressions').forEach(r=>add(r,'ASIN Suppression',r.revenueImpactPerDay));getSnapshotAmazonIssueRows(snapshot,'amazonBuyBox').forEach(r=>add(r,'Buy Box Suppression',r.revenueImpactPerDay));}return out;}
  async function loadImpact(){const [from,to]=range();const snaps=await v4LoadSnapshotsForRange(from,to);let raw=[];for(const s of snaps){if(impactMarket==='combined'||impactMarket==='amazon')raw.push(...impactLine(s,'amazon'));if(impactMarket==='combined'||impactMarket==='flipkart')raw.push(...impactLine(s,'flipkart'));}const category=document.getElementById('revenueImpactCategory')?.value||'all',issue=document.getElementById('revenueImpactIssue')?.value||'all',q=String(document.getElementById('revenueImpactSearch')?.value||'').toLowerCase();const cats=[...new Set(raw.map(x=>x.category).filter(Boolean))].sort();const cs=document.getElementById('revenueImpactCategory');if(cs){const old=cs.value;cs.innerHTML='<option value="all">All Categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');cs.value=cats.includes(old)?old:'all';}
    const issueMatch=x=>issue==='all'||(issue==='listing'&&x.issue==='Listing Price')||(issue==='live'&&x.issue==='Live Price')||(issue==='suppression'&&x.issue==='ASIN Suppression')||(issue==='buybox'&&x.issue==='Buy Box Suppression');raw=raw.filter(x=>(category==='all'||x.category===category)&&issueMatch(x)&&(!q||`${x.identifier} ${x.marketSku} ${x.wfSku}`.toLowerCase().includes(q)));
    // Deduplicate total exposure by marketplace + date + product, taking the maximum concurrent issue impact.
    const dedup=new Map();raw.forEach(x=>{const k=`${x.date}|${x.marketplace}|${x.identifier}`;const old=dedup.get(k);if(!old||x.impact>old.impact)dedup.set(k,x);});impactRows=[...dedup.values()];renderImpact(raw,impactRows,from,to);
  }
  function renderImpact(raw,dedup,from,to){const total=dedup.reduce((a,x)=>a+x.impact,0),products=new Set(dedup.map(x=>`${x.marketplace}|${x.identifier}`)).size,days=new Set(dedup.map(x=>x.date)).size,avg=days?total/days:0;document.getElementById('revenueImpactKpis').innerHTML=`<div class="v93-kpi"><span>Deduplicated Exposure</span><strong>${money(total)}</strong></div><div class="v93-kpi"><span>Affected Products</span><strong>${nf(products)}</strong></div><div class="v93-kpi"><span>Observed Days</span><strong>${nf(days)}</strong></div><div class="v93-kpi"><span>Average Exposure / Day</span><strong>${money(avg)}</strong></div>`;
    const daily={};dedup.forEach(x=>daily[x.date]=(daily[x.date]||0)+x.impact);const max=Math.max(1,...Object.values(daily));document.getElementById('revenueImpactTrend').innerHTML=`<div class="v93-bar-chart">${Object.entries(daily).sort().map(([d,v])=>`<div class="v93-bar-row"><span>${esc(d.slice(5))}</span><div class="v93-bar-track"><div class="v93-bar-fill" style="width:${v/max*100}%"></div></div><strong>${money(v)}</strong></div>`).join('')||'<div class="utility-empty">No impact data.</div>'}</div>`;const cat={};dedup.forEach(x=>cat[x.category]=(cat[x.category]||0)+x.impact);const cmax=Math.max(1,...Object.values(cat));document.getElementById('revenueImpactCategoryChart').innerHTML=`<div class="v93-bar-chart">${Object.entries(cat).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="v93-bar-row"><span>${esc(c)}</span><div class="v93-bar-track"><div class="v93-bar-fill" style="width:${v/cmax*100}%"></div></div><strong>${money(v)}</strong></div>`).join('')}</div>`;
    const cols=[['date','Date'],['marketplace','Marketplace'],['category','Category'],['wfSku','WF SKU'],['marketSku','Marketplace SKU'],['identifier','ASIN / FSN'],['issue','Primary Issue'],['impact','Revenue Impact']];const table=document.getElementById('revenueImpactTable');table.dataset.wsColumnTable='revenueImpact';table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${c[1]}</th>`).join('')+'</tr></thead><tbody>'+(dedup.length?dedup.sort((a,b)=>b.impact-a.impact).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.marketplace==='amazon'?'Amazon':'Flipkart')}</td><td>${esc(r.category)}</td><td><button class="v93-link-id" onclick='WakeSuiteProduct360.open(${JSON.stringify(r.wfSku||r.identifier)},{context:"global",date:${JSON.stringify(r.date)}})'>${esc(r.wfSku||'—')}</button></td><td>${esc(r.marketSku)}</td><td><button class="v93-link-id" onclick='WakeSuiteProduct360.open(${JSON.stringify(r.identifier)},{context:"global",date:${JSON.stringify(r.date)}})'>${esc(r.identifier)}</button></td><td>${esc(r.issue)}</td><td>${money(r.impact)}</td></tr>`).join(''):`<tr><td colspan="8" class="empty-row">No actionable revenue impact for ${esc(from)} to ${esc(to)}.</td></tr>`)+'</tbody>';document.getElementById('revenueImpactRowCount').textContent=`${nf(dedup.length)} rows`;WakeSuiteColumns.register('revenueImpact',cols.map(([key,label])=>({key,label})),cols.map(x=>x[0]),'revenueImpactColumns');}
  function openImpact(m,c={}){impactMarket=['amazon','flipkart'].includes(m)?m:'combined';wakeSuiteNavigate?.('revenueImpactSection');document.getElementById('revenueImpactTitle').textContent=`${impactMarket==='combined'?'Combined':impactMarket==='amazon'?'Amazon':'Flipkart'} · Revenue Impact`;if(c.period)document.getElementById('revenueImpactPeriod').value=c.period==='last15'?'last14':c.period;if(c.from)document.getElementById('revenueImpactFromDate').value=c.from;if(c.to)document.getElementById('revenueImpactToDate').value=c.to;if(c.category)document.getElementById('revenueImpactCategory').value=c.category;loadImpact();}
  function exportImpact(full=false){if(!impactRows.length){showWakeSuiteToast?.('No revenue impact data to download.','warning');return;}writeExcelReport?.(`WakeSuite_Revenue_Impact_${impactMarket}_${todayIso()}.xlsx`,{},impactRows.map(r=>({Date:r.date,Marketplace:r.marketplace,Category:r.category,'WF SKU':r.wfSku,'Marketplace SKU':r.marketSku,'ASIN / FSN':r.identifier,'Primary Issue':r.issue,'Revenue Impact':r.impact})));}
  window.openDashboardDestination=route;window.openDashboardCategoryDestination=categoryRoute;window.openDashboardExceptionsNative=(m)=>openExceptions(m,ctx());window.openDashboardOverriddenNative=()=>openSuppressionManagementOverride(ctx());window.openRevenueImpactReport=openImpact;window.loadRevenueImpactReport=loadImpact;window.downloadRevenueImpactReport=exportImpact;
})();
