/* WakeSuite V9.3 · standalone Amazon / Flipkart Price Parity reports */
(function(){
  let market='amazon',rows=[],allRows=[];
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v??''):String(v??'');
  const money=v=>Number.isFinite(Number(v))?formatINR(Number(v)):'—';
  const num=v=>typeof formatNumber==='function'?formatNumber(Number(v)||0):String(Number(v)||0);
  const iso=d=>{const x=d instanceof Date?new Date(d):new Date(`${d}T00:00:00`);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;};
  const shift=(date,n)=>{const d=new Date(`${date}T00:00:00`);d.setDate(d.getDate()+n);return iso(d);};
  function today(){return typeof todayIso==='function'?todayIso():iso(new Date());}
  function latestKnown(){const t=document.getElementById('latestCompletedDateDisplay')?.textContent?.replace('As of ','').trim();return /^\d{4}-\d{2}-\d{2}$/.test(t||'')?t:today();}
  function range(){const p=document.getElementById('priceParityPeriod')?.value||'today',a=latestKnown();let from=a,to=a;if(p==='yesterday')from=to=shift(a,-1);else if(p==='last7')from=shift(a,-6);else if(p==='last14')from=shift(a,-13);else if(p==='last30')from=shift(a,-29);else if(p==='selected'){from=to=document.getElementById('priceParitySelectedDate')?.value||a;}else if(p==='custom'){from=document.getElementById('priceParityFromDate')?.value||a;to=document.getElementById('priceParityToDate')?.value||a;if(from>to)[from,to]=[to,from];}setValue('priceParityFromDate',from);setValue('priceParityToDate',to);return[from,to];}
  function setValue(id,v){const e=document.getElementById(id);if(e)e.value=v;}
  function state(row,component){
    const st=(issue,ex,eligible=true)=>!eligible?'Not Eligible':ex?'Approved Exception':issue?'Actionable Disparity':'Parity';
    if(component==='listing')return st(row.listingPriceDisparity,row.listingPriceException||row.listingException);
    if(component==='live'){
      const liveValid=Number(row.finalLivePrice)>0||Number(row.livePrice)>0;
      if(!liveValid)return'Not Eligible';
      return st(row.livePriceDisparity,row.livePriceException||row.liveException,liveValid);
    }
    if(component==='mrp')return st(row.mrpDisparity,row.mrpException);
    const pieces=['listing','live','mrp'].map(x=>state(row,x)).filter(x=>x!=='Not Eligible');
    if(pieces.includes('Actionable Disparity'))return'Actionable Disparity';
    if(pieces.includes('Approved Exception'))return'Approved Exception';
    return pieces.length?'Parity':'Not Eligible';
  }
  function normalize(snapshot,m){
    const base=m==='amazon'?getSnapshotAmazonRows(snapshot):getSnapshotFlipkartRows(snapshot);
    return (base||[]).map(r=>({
      reportDate:snapshot.reportDate,marketplace:m,category:r.category||'Uncategorized',wfSku:r.wfSku||'',marketSku:m==='amazon'?(r.azSku||''):(r.fkSku||''),identifier:m==='amazon'?(r.asin||''):(r.fsn||''),azSku:r.azSku||'',asin:r.asin||'',fkSku:r.fkSku||'',fsn:r.fsn||'',skuType:r.azSkuType||r.skuType||'',wfPrice:Number(r.wfPrice)||0,listingPrice:Number(r.listingPrice)||0,livePrice:Number(r.finalLivePrice??r.livePrice)||0,wfMrp:Number(r.wfMrp)||0,marketMrp:Number(m==='amazon'?r.azMrp:r.fkMrp)||0,inventory:r.inventory??null,revenuePerDay:Number(r.revenueImpactPerDay||r.avgRevenuePerDay||0)||0,revenue:Number(m==='amazon'?r.asinRevenue:r.calculatedRevenue)||0,raw:r
    }));
  }
  async function loadSnapshots(from,to){if(typeof v4LoadSnapshotsForRange==='function')return v4LoadSnapshotsForRange(from,to);if(typeof listDailySnapshotMetas!=='function')return[];const metas=(await listDailySnapshotMetas()).filter(x=>x.reportDate>=from&&x.reportDate<=to);const out=[];for(const x of metas){const s=await loadSnapshotCached(x.reportDate);if(s)out.push(s);}return out;}
  function populateCategory(source){const e=document.getElementById('priceParityCategory');if(!e)return;const cur=e.value||'all';const cats=[...new Set(source.map(x=>x.category).filter(Boolean))].sort();e.innerHTML='<option value="all">All Categories</option>'+cats.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');e.value=cats.includes(cur)?cur:'all';}
  function stateKey(s){return s==='Parity'?'parity':s==='Approved Exception'?'exception':s==='Actionable Disparity'?'disparity':'na';}
  function rowStatus(r,component){return state(r.raw,component);}
  function clickable(r,label,value){const id=value||'';if(!id)return'—';return `<button class="v93-link-id" onclick='WakeSuiteProduct360.open(${JSON.stringify(id)},{context:"priceParity",marketplace:${JSON.stringify(r.marketplace)},date:${JSON.stringify(r.reportDate)}})'>${esc(label||id)}</button>`;}
  function renderKpis(filtered,component){const actionable=filtered.filter(r=>rowStatus(r,component)==='Actionable Disparity').length,parity=filtered.filter(r=>rowStatus(r,component)==='Parity').length,exceptions=filtered.filter(r=>rowStatus(r,component)==='Approved Exception').length,eligible=parity+actionable,pct=eligible?parity/eligible*100:0;const cats={};filtered.forEach(r=>{const s=rowStatus(r,component);if(!cats[r.category])cats[r.category]={p:0,d:0};if(s==='Parity')cats[r.category].p++;if(s==='Actionable Disparity')cats[r.category].d++;});const ranked=Object.entries(cats).map(([c,x])=>[c,(x.p+x.d)?x.p/(x.p+x.d)*100:0]).sort((a,b)=>b[1]-a[1]);document.getElementById('priceParityKpis').innerHTML=[['Parity %',`${pct.toFixed(1)}%`],['Parity Products / Checks',num(parity)],['Actionable Disparities',num(actionable)],['Exceptions Excluded',num(exceptions)],['Total Eligible',num(eligible)],['Highest Category',ranked[0]?`${esc(ranked[0][0])} · ${ranked[0][1].toFixed(1)}%`:'—'],['Lowest Category',ranked.at(-1)?`${esc(ranked.at(-1)[0])} · ${ranked.at(-1)[1].toFixed(1)}%`:'—']].map(([l,v])=>`<div class="v93-kpi"><span>${l}</span><strong>${v}</strong></div>`).join('');
  }
  function renderDaily(filtered,component){const map=new Map();filtered.forEach(r=>{const d=map.get(r.reportDate)||{date:r.reportDate,p:0,d:0,e:0};const s=rowStatus(r,component);if(s==='Parity')d.p++;else if(s==='Actionable Disparity')d.d++;else if(s==='Approved Exception')d.e++;map.set(r.reportDate,d);});const daily=[...map.values()].sort((a,b)=>a.date.localeCompare(b.date));const table=document.getElementById('priceParityDailyTable');table.innerHTML='<thead><tr><th>Date</th><th>Eligible</th><th>Parity</th><th>Actionable Disparity</th><th>Exceptions Excluded</th><th>Parity %</th></tr></thead><tbody>'+daily.map(x=>{const den=x.p+x.d,pct=den?x.p/den*100:0;return`<tr><td>${esc(x.date)}</td><td>${num(den)}</td><td>${num(x.p)}</td><td>${num(x.d)}</td><td>${num(x.e)}</td><td>${pct.toFixed(1)}%</td></tr>`;}).join('')+'</tbody>';document.getElementById('priceParitySummaryMeta').textContent=`${daily.length} observed day${daily.length===1?'':'s'}`;const max=100;document.getElementById('priceParityTrend').innerHTML=`<div class="v93-bar-chart">${daily.map(x=>{const den=x.p+x.d,pct=den?x.p/den*100:0;return`<div class="v93-bar-row"><span>${esc(x.date.slice(5))}</span><div class="v93-bar-track"><div class="v93-bar-fill" style="width:${Math.min(max,pct)}%"></div></div><strong>${pct.toFixed(1)}%</strong></div>`;}).join('')||'<div class="utility-empty">No daily parity observations.</div>'}</div>`;
  }
  function renderCategories(filtered,component){const map=new Map();filtered.forEach(r=>{const x=map.get(r.category)||{p:0,d:0,e:0};const s=rowStatus(r,component);if(s==='Parity')x.p++;else if(s==='Actionable Disparity')x.d++;else if(s==='Approved Exception')x.e++;map.set(r.category,x);});document.getElementById('priceParityCategoryChart').innerHTML=`<div class="v93-bar-chart">${[...map.entries()].sort().map(([c,x])=>{const den=x.p+x.d,pct=den?x.p/den*100:0;return`<div class="v93-bar-row"><span>${esc(c)}</span><div class="v93-bar-track"><div class="v93-bar-fill" style="width:${pct}%"></div></div><strong>${pct.toFixed(1)}%</strong></div>`;}).join('')||'<div class="utility-empty">No category data.</div>'}</div>`;}
  const columns=[
    {key:'date',label:'Date',get:r=>r.reportDate},{key:'category',label:'Category',get:r=>r.category},{key:'wfSku',label:'WF SKU',html:r=>clickable(r,r.wfSku,r.wfSku)},{key:'marketSku',label:()=>market==='amazon'?'AZ SKU':'FK SKU',html:r=>clickable(r,r.marketSku,r.marketSku)},{key:'identifier',label:()=>market==='amazon'?'ASIN':'FSN',html:r=>clickable(r,r.identifier,r.identifier)},{key:'skuType',label:'AZ SKU Type',get:r=>market==='amazon'?(r.skuType||'—'):'—'},{key:'wfPrice',label:'WF Price',get:r=>money(r.wfPrice)},{key:'listing',label:'Listing Price',get:r=>money(r.listingPrice)},{key:'listingStatus',label:'Listing Status',html:r=>statusHtml(rowStatus(r,'listing'))},{key:'live',label:'Live Price',get:r=>money(r.livePrice)},{key:'liveStatus',label:'Live Status',html:r=>statusHtml(rowStatus(r,'live'))},{key:'wfMrp',label:'WF MRP',get:r=>money(r.wfMrp)},{key:'marketMrp',label:'Marketplace MRP',get:r=>money(r.marketMrp)},{key:'mrpStatus',label:'MRP Status',html:r=>statusHtml(rowStatus(r,'mrp'))},{key:'overall',label:'Overall Parity Status',html:r=>statusHtml(rowStatus(r,'overall'))},{key:'inventory',label:'Inventory',get:r=>r.inventory??'No Data'},{key:'revenue',label:'Revenue / Day',get:r=>r.revenuePerDay?money(r.revenuePerDay):'—'}
  ];
  function label(c){return typeof c.label==='function'?c.label():c.label;}
  function statusHtml(s){return `<span class="v93-state ${stateKey(s)}">${esc(s)}</span>`;}
  function renderTable(filtered,component){const status=document.getElementById('priceParityStatus')?.value||'all',q=String(document.getElementById('priceParitySearch')?.value||'').trim().toLowerCase();rows=filtered.filter(r=>{const st=rowStatus(r,component);if(status!=='all'&&stateKey(st)!==status)return false;if(q&&!`${r.wfSku} ${r.marketSku} ${r.identifier}`.toLowerCase().includes(q))return false;return true;});const table=document.getElementById('priceParityTable');table.dataset.wsColumnTable='priceParity';table.innerHTML='<thead><tr>'+columns.map(c=>`<th>${esc(label(c))}</th>`).join('')+'</tr></thead><tbody>'+(rows.length?rows.slice(0,3000).map(r=>'<tr>'+columns.map(c=>`<td>${c.html?c.html(r):esc(c.get(r))}</td>`).join('')+'</tr>').join(''):`<tr><td colspan="${columns.length}" class="empty-row">No products match the selected parity filters.</td></tr>`)+'</tbody>';document.getElementById('priceParityRowCount').textContent=`${num(rows.length)} rows`;WakeSuiteColumns.register('priceParity',columns.map(c=>({key:c.key,label:label(c)})),['date','category','wfSku','marketSku','identifier','wfPrice','listing','listingStatus','live','liveStatus','wfMrp','marketMrp','mrpStatus','overall'],'priceParityColumns');}
  async function load(){const [from,to]=range();document.getElementById('priceParitySubtitle').textContent=`${market==='amazon'?'Amazon':'Flipkart'} · ${from} to ${to}`;document.getElementById('priceParityKpis').innerHTML='<div class="v93-kpi"><span>Loading</span><strong>…</strong></div>';try{const snaps=await loadSnapshots(from,to);allRows=snaps.flatMap(s=>normalize(s,market));populateCategory(allRows);const cat=document.getElementById('priceParityCategory')?.value||'all',component=document.getElementById('priceParityComponent')?.value||'overall';const base=allRows.filter(r=>(cat==='all'||r.category===cat)&&(typeof v7CategoryAllowed!=='function'||v7CategoryAllowed(r.category)));renderKpis(base,component);renderDaily(base,component);renderCategories(base,component);renderTable(base,component);}catch(error){console.error(error);document.getElementById('priceParityKpis').innerHTML=`<div class="v93-kpi"><span>Unable to load</span><strong>${esc(error.message)}</strong></div>`;showWakeSuiteToast?.(error.message,'error','Price Parity');}}
  function open(m,ctx={}){market=m==='flipkart'?'flipkart':'amazon';wakeSuiteNavigate?.('priceParitySection');document.getElementById('priceParityTitle').textContent=`${market==='amazon'?'Amazon':'Flipkart'} · Price Parity`;if(ctx.period)setValue('priceParityPeriod',ctx.period);if(ctx.from)setValue('priceParityFromDate',ctx.from);if(ctx.to)setValue('priceParityToDate',ctx.to);if(ctx.date)setValue('priceParitySelectedDate',ctx.date);if(ctx.category)setValue('priceParityCategory',ctx.category);load();}
  function reset(){setValue('priceParityPeriod','today');setValue('priceParityCategory','all');setValue('priceParityComponent','overall');setValue('priceParityStatus','all');setValue('priceParitySearch','');load();}
  function exportReport(full=false){if(!rows.length){showWakeSuiteToast?.('No parity rows to download.','warning');return;}const visible=full?columns.map(c=>c.key):WakeSuiteColumns.visible('priceParity');const data=rows.map(r=>Object.fromEntries(columns.filter(c=>visible.includes(c.key)).map(c=>[label(c),c.get?c.get(r):rowStatus(r,c.key==='overall'?'overall':c.key.replace('Status','').toLowerCase())])));if(typeof writeExcelReport==='function')writeExcelReport(`WakeSuite_${market==='amazon'?'Amazon':'Flipkart'}_Price_Parity_${today()}.xlsx`,{},data);}
  ['priceParityPeriod','priceParitySelectedDate','priceParityFromDate','priceParityToDate','priceParityCategory','priceParityComponent','priceParityStatus'].forEach(id=>document.addEventListener('change',e=>{if(e.target?.id===id&&document.getElementById('priceParitySection')?.classList.contains('active'))load();}));
  window.openPriceParityReport=open;window.loadPriceParityReport=load;window.resetPriceParityReport=reset;window.downloadPriceParityReport=exportReport;window.WakeSuitePriceParity={open,load,get rows(){return rows;},get allRows(){return allRows;}};window.WakeSuiteModules?.register('priceParity',window.WakeSuitePriceParity);
})();
