/* WakeSuite V9.3 · permission-aware context-specific Product 360 */
(function(){
  let current=null,context='global',activeTab='Overview',enrichment={cases:[],exceptions:[],updates:[]};
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v??''):String(v??'');
  const money=v=>Number.isFinite(Number(v))?formatINR(Number(v)):'—';
  const n=v=>Number(v)||0;
  function contextFromView(){const id=document.querySelector('.app-view.active')?.id||'';if(id==='suppressionManagementSection'||id==='reportModuleSection')return'suppressions';if(id==='marketplaceDataSection')return'marketplaceData';if(id==='priceUpdatesSection')return'priceUpdates';if(id==='priceParitySection')return'priceParity';if(id==='businessInsightsSection')return window.WakeSuiteBusinessInsightsType||'businessInsights';if(id==='marketplaceInsightsSection')return'marketplaceInsights';return'global';}
  function status(r,type){if(type==='listing')return r.listingPriceException?'Approved Exception':r.listingPriceDisparity?'Actionable Disparity':'Parity';if(type==='live')return r.livePriceException?'Approved Exception':r.livePriceDisparity?'Actionable Disparity':'Parity';if(type==='mrp')return r.mrpException?'Approved Exception':r.mrpDisparity?'Actionable Disparity':'Parity';return'—';}
  function statePill(s){const c=/parity/i.test(s)?'parity':/exception/i.test(s)?'exception':/disparity|suppressed|active/i.test(s)?'disparity':'';return`<span class="v93-state ${c}">${esc(s)}</span>`;}
  async function enrich(data){const asin=new Set(data.amazon.map(r=>String(r.asin||'')).filter(Boolean)),ids=new Set([...data.amazon,...data.flipkart].flatMap(r=>[r.wfSku,r.azSku,r.asin,r.fkSku,r.fsn].map(String)));const out={cases:[],exceptions:[],updates:[]};try{out.cases=(await window.loadSuppressionCases?.()||[]).filter(r=>asin.has(String(r.asin||'')));}catch(_){}try{if(typeof v7EnsurePricingExceptionsLoaded==='function')await v7EnsurePricingExceptionsLoaded(true);out.exceptions=(typeof v7PricingExceptions!=='undefined'?v7PricingExceptions:[]).filter(r=>[r.wfSku,r.azSku,r.asin,r.fkSku,r.fsn,r.identifier].some(x=>x&&ids.has(String(x))));}catch(_){}try{const b=await window.loadMarketplaceUpdateBatches?.()||[];out.updates=b.flatMap(x=>(x.rows||[]).filter(r=>[r.wfSku,r.azSku,r.asin,r.fkSku,r.fsn,r.identifier].some(v=>v&&ids.has(String(v)))).map(r=>({...r,batchId:x.id,batchStatus:x.status,batchDate:x.reportDate,marketplace:x.marketplace})));}catch(_){}return out;}
  function identityRows(data){return [...data.amazon.map(r=>({Marketplace:'Amazon',Category:r.category,'WF SKU':r.wfSku,'ASIN / FSN':r.asin,'Marketplace SKU':r.azSku,'SKU Type':r.azSkuType||r.skuType||''})),...data.flipkart.map(r=>({Marketplace:'Flipkart',Category:r.category,'WF SKU':r.wfSku,'ASIN / FSN':r.fsn,'Marketplace SKU':r.fkSku,'SKU Type':''}))];}
  function currentRows(data){return [...data.amazon.map(r=>({...r,_market:'amazon'})),...data.flipkart.map(r=>({...r,_market:'flipkart'}))];}
  function summary(data){const all=currentRows(data),issues=all.reduce((s,r)=>s+(r.listingPriceDisparity?1:0)+(r.livePriceDisparity?1:0)+(r.mrpDisparity?1:0),0),inv=all.reduce((s,r)=>s+n(r.inventory),0),cases=enrichment.cases.filter(c=>!['Closed','Reactivated'].includes(c.status)).length,exceptions=enrichment.exceptions.filter(e=>String(e.status||'active').toLowerCase()!=='removed').length;return `<div class="product-360-summary"><div class="product-detail"><span>Mappings</span><strong>${all.length}</strong></div><div class="product-detail"><span>Pricing Issues</span><strong>${issues}</strong></div><div class="product-detail"><span>Total Known Inventory</span><strong>${inv}</strong></div><div class="product-detail"><span>Open Suppressions</span><strong>${cases}</strong></div><div class="product-detail"><span>Pricing Exceptions</span><strong>${exceptions}</strong></div></div>`;}
  function table(data,columns){if(!data.length)return'<div class="utility-empty">No data available.</div>';return `<div class="table-wrap"><table class="result-table"><thead><tr>${columns.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${columns.map(c=>`<td>${c[2]?c[2](r):esc(c[1](r)??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  function globalTab(name){const data=current,all=currentRows(data);if(name==='Overview')return summary(data)+`<div class="product-360-section"><h3>Current Marketplace Position</h3>${table(all,[['Marketplace',r=>r._market==='amazon'?'Amazon':'Flipkart'],['Category',r=>r.category],['WF SKU',r=>r.wfSku],['Marketplace SKU',r=>r._market==='amazon'?r.azSku:r.fkSku],['ASIN / FSN',r=>r._market==='amazon'?r.asin:r.fsn],['Inventory',r=>r.inventory??'No Data'],['WF Price',r=>money(r.wfPrice)],['Listing Price',r=>money(r.listingPrice)],['Live Price',r=>money(r.finalLivePrice)],['WF MRP',r=>money(r.wfMrp)]])}</div>`;
    if(name==='Pricing')return table(all,[['Marketplace',r=>r._market==='amazon'?'Amazon':'Flipkart'],['WF SKU',r=>r.wfSku],['Marketplace SKU',r=>r._market==='amazon'?r.azSku:r.fkSku],['ASIN / FSN',r=>r._market==='amazon'?r.asin:r.fsn],['WF Price',r=>money(r.wfPrice)],['Listing Price',r=>money(r.listingPrice)],['Listing Status',r=>status(r,'listing'),r=>statePill(status(r,'listing'))],['Live Price',r=>money(r.finalLivePrice)],['Live Status',r=>status(r,'live'),r=>statePill(status(r,'live'))],['WF MRP',r=>money(r.wfMrp)],['Marketplace MRP',r=>money(r._market==='amazon'?r.azMrp:r.fkMrp)],['MRP Status',r=>status(r,'mrp'),r=>statePill(status(r,'mrp'))],['Min SAP',r=>r.minimumAllowedPrice??r.minAllowedPrice??'—'],['Max SAP',r=>r.maximumAllowedPrice??r.maxAllowedPrice??'—']]);
    if(name==='Inventory')return table(all,[['Marketplace',r=>r._market==='amazon'?'Amazon':'Flipkart'],['Category',r=>r.category],['WF SKU',r=>r.wfSku],['Marketplace SKU',r=>r._market==='amazon'?r.azSku:r.fkSku],['ASIN / FSN',r=>r._market==='amazon'?r.asin:r.fsn],['Inventory',r=>r.inventory??'No Data'],['Status',r=>Number(r.inventory)===0?'OOS':r.inventory==null?'No Data':'In Stock']]);
    if(name==='Revenue')return table(all,[['Marketplace',r=>r._market==='amazon'?'Amazon':'Flipkart'],['WF SKU',r=>r.wfSku],['ASIN / FSN',r=>r._market==='amazon'?r.asin:r.fsn],['Revenue',r=>money(r._market==='amazon'?r.asinRevenue:r.calculatedRevenue)],['Price Impact / Day',r=>money(r.dailyRevenueImpact||r.liveDailyRevenueImpact||r.listingDailyRevenueImpact)]]);
    if(name==='Issues')return table(all.flatMap(r=>[['Listing Price',status(r,'listing')],['Live Price',status(r,'live')],['MRP',status(r,'mrp')]].map(([type,s])=>({Marketplace:r._market==='amazon'?'Amazon':'Flipkart',Identifier:r._market==='amazon'?r.asin:r.fsn,Type:type,Status:s}))),[['Marketplace',r=>r.Marketplace],['Identifier',r=>r.Identifier],['Issue / Component',r=>r.Type],['Status',r=>r.Status,r=>statePill(r.Status)]]);
    if(name==='Suppressions')return suppressionMarkup();
    if(name==='Exceptions')return table(enrichment.exceptions,[['Marketplace',r=>r.marketplace],['Category',r=>r.category],['WF SKU',r=>r.wfSku],['AZ SKU',r=>r.azSku],['ASIN',r=>r.asin],['FK SKU',r=>r.fkSku],['FSN',r=>r.fsn],['Target',r=>r.target],['Type',r=>r.exceptionType],['From',r=>r.effectiveFrom],['To',r=>r.effectiveTo||'No Expiry'],['Status',r=>r.status||'active']]);
    if(name==='Mappings')return table(identityRows(data),Object.keys(identityRows(data)[0]||{}).map(k=>[k,r=>r[k]]));
    if(name==='Update Activity')return table(enrichment.updates,[['Date',r=>r.batchDate],['Marketplace',r=>r.marketplace],['Batch',r=>r.batchId],['Status',r=>r.batchStatus],['WF SKU',r=>r.wfSku],['Marketplace SKU',r=>r.azSku||r.fkSku],['Target Price',r=>r.targetPrice||r.wfPrice],['Target MRP',r=>r.targetMrp||r.wfMrp]]);
    if(name==='History')return `<div class="v93-workspace-note">Open the centralized read-only history hub for complete pricing, inventory, mapping and operational history.</div><div class="module-actions"><button class="primary-btn" onclick="openHistoryHub('pricing')">Pricing History</button><button class="secondary-btn" onclick="openHistoryHub('inventory')">Inventory History</button><button class="secondary-btn" onclick="openHistoryHub('mapping')">Mapping History</button></div>`;return'';}
  function suppressionMarkup(){const cs=enrichment.cases;return `<div class="v93-workspace-note">Amazon suppression lifecycle only. Pricing, inventory and Flipkart data are intentionally excluded in this module context.</div>${table(cs,[['ASIN',r=>r.asin],['Category',r=>r.category],['WF SKU',r=>r.wfSku],['AZ SKU',r=>r.azSku],['First Seen',r=>r.firstSeen||r.firstDetected],['Last Seen',r=>r.lastSeen||r.lastDetected],['State',r=>r.currentState||r.suppressionState||r.status],['Resolved On',r=>r.resolvedOn||r.closedOn],['Revenue Impact / Day',r=>money(r.revenueImpactPerDay)],['Case ID',r=>r.caseId],['Owner',r=>r.owner],['POC',r=>r.pocEscalationStatus],['POA',r=>r.poaStatus],['QC',r=>r.qcStatus],['Notes',r=>r.notes]])}`;}
  function parityMarkup(){const all=currentRows(current);return table(all,[['Marketplace',r=>r._market==='amazon'?'Amazon':'Flipkart'],['WF SKU',r=>r.wfSku],['Marketplace SKU',r=>r._market==='amazon'?r.azSku:r.fkSku],['ASIN / FSN',r=>r._market==='amazon'?r.asin:r.fsn],['Listing',r=>status(r,'listing'),r=>statePill(status(r,'listing'))],['Live',r=>status(r,'live'),r=>statePill(status(r,'live'))],['MRP',r=>status(r,'mrp'),r=>statePill(status(r,'mrp'))]]);}
  function render(){const title=document.getElementById('productDrawerTitle'),market=document.getElementById('productDrawerMarket'),ctx=document.getElementById('productDrawerContext'),body=document.getElementById('productDrawerBody'),tabs=document.getElementById('productDrawerTabs'),full=document.getElementById('productDrawerFullButton');if(!current||!body)return;title.textContent=current.query;ctx.textContent=context==='global'?'Product 360':({'suppressions':'Amazon Suppression Detail','marketplaceData':'Marketplace Data Detail','priceUpdates':'Price Update Detail','pricingInsights':'Pricing Insight Detail','inventoryInsights':'Inventory Insight Detail','priceParity':'Price Parity Detail','marketplaceInsights':'Marketplace Insight Detail'}[context]||'Product Detail');const names=[current.amazon.length?'Amazon':'',current.flipkart.length?'Flipkart':''].filter(Boolean);market.textContent=context==='suppressions'?'Amazon':names.join(' + ')||'No permitted marketplace match';full.style.display=context==='global'?'none':'';document.getElementById('productDrawerBackdrop')?.classList.toggle('v93-product-drawer-suppression',context==='suppressions');if(context==='global'){const names=['Overview','Pricing','Inventory','Revenue','Issues','Suppressions','Exceptions','Mappings','Update Activity','History'];tabs.innerHTML=`<div class="v93-product-tabs">${names.map(x=>`<button class="v93-tab ${x===activeTab?'active':''}" onclick='setProduct360Tab(${JSON.stringify(x)})'>${x}</button>`).join('')}</div>`;body.innerHTML=globalTab(activeTab);}else{tabs.innerHTML='';if(context==='suppressions')body.innerHTML=suppressionMarkup();else if(context==='priceParity')body.innerHTML=parityMarkup();else if(context==='marketplaceData')body.innerHTML=`<div class="v93-workspace-note">Current normalized marketplace mappings. Use Full Product 360 for broader permitted product data.</div>${table(identityRows(current),Object.keys(identityRows(current)[0]||{}).map(k=>[k,r=>r[k]]))}`;else if(context==='inventoryInsights')body.innerHTML=globalTab('Inventory');else if(context==='pricingInsights'||context==='priceUpdates')body.innerHTML=globalTab('Pricing');else body.innerHTML=globalTab('Issues');}}
  async function open(identifier,opts={}){context=opts.context||contextFromView();activeTab='Overview';const data=await window.WakeSuiteProductResolver?.resolve(identifier,{date:opts.date});current=data||{query:identifier,date:opts.date,amazon:[],flipkart:[]};enrichment=await enrich(current);document.getElementById('productDrawerBackdrop')?.classList.add('open');render();}
  function setTab(t){activeTab=t;render();}
  function openFull(){if(!current)return;context='global';activeTab='Overview';render();}
  function exportRows(){if(context==='suppressions')return enrichment.cases.map(r=>({Marketplace:'Amazon',ASIN:r.asin,Category:r.category,'WF SKU':r.wfSku,'AZ SKU':r.azSku,'First Seen':r.firstSeen||r.firstDetected,'Last Seen':r.lastSeen||r.lastDetected,State:r.currentState||r.status,'Resolved On':r.resolvedOn||r.closedOn,'Revenue Impact / Day':r.revenueImpactPerDay,'Case ID':r.caseId,Owner:r.owner,POC:r.pocEscalationStatus,POA:r.poaStatus,QC:r.qcStatus,Notes:r.notes}));return identityRows(current).map((r,i)=>({...r,Inventory:currentRows(current)[i]?.inventory,'WF Price':currentRows(current)[i]?.wfPrice,'Listing Price':currentRows(current)[i]?.listingPrice,'Live Price':currentRows(current)[i]?.finalLivePrice,'WF MRP':currentRows(current)[i]?.wfMrp}));}
  function download(){const data=exportRows();if(!data.length){showWakeSuiteToast?.('No product data is available to download.','warning');return;}if(window.XLSX){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),context==='suppressions'?'Suppression':'Overview');if(context==='global'){if(enrichment.exceptions.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(enrichment.exceptions),'Exceptions');if(enrichment.cases.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(enrichment.cases),'Suppressions');if(enrichment.updates.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(enrichment.updates),'Update Activity');}XLSX.writeFile(wb,`WakeSuite_${context==='global'?'Product_360':'Product_'+context}_${String(current.query).replace(/[^A-Za-z0-9_-]/g,'_')}.xlsx`);}}
  window.openProductDrawer=(marketplace,identifier)=>open(identifier,{context:contextFromView(),marketplace});window.openFullProduct360=openFull;window.downloadCurrentProductData=download;window.setProduct360Tab=setTab;window.WakeSuiteProduct360={open,openFull,download,setTab};window.WakeSuiteModules?.register('product360',window.WakeSuiteProduct360);
})();
