/* WakeSuite V9.2 context-aware Product 360 */
(function(){
  let current=null,currentContext='global';
  const esc=s=>typeof window.escapeHtml==='function'?window.escapeHtml(s??''):String(s??'');
  const money=n=>typeof window.formatINR==='function'?window.formatINR(n):String(n??'—');
  function contextFromView(){const active=document.querySelector('.app-view.active')?.id||'';if(active==='marketplaceInsightsSection')return'marketplaceInsights';if(active==='businessInsightsSection')return'businessInsights';if(active==='suppressionManagementSection'||active==='reportModuleSection')return'suppressions';if(active==='marketplaceDataSection')return'marketplaceData';if(active==='priceUpdatesSection')return'priceUpdates';return'global';}
  function rowCard(r,m){return `<div class="product-detail-grid"><div class="product-detail"><span>Marketplace</span><strong>${m==='amazon'?'Amazon':'Flipkart'}</strong></div><div class="product-detail"><span>Category</span><strong>${esc(r.category||'—')}</strong></div><div class="product-detail"><span>WF SKU</span><strong>${esc(r.wfSku||'—')}</strong></div><div class="product-detail"><span>${m==='amazon'?'ASIN':'FSN'}</span><strong>${esc(m==='amazon'?r.asin:r.fsn)}</strong></div><div class="product-detail"><span>${m==='amazon'?'AZ SKU':'FK SKU'}</span><strong>${esc(m==='amazon'?r.azSku:r.fkSku)}</strong></div><div class="product-detail"><span>Inventory</span><strong>${esc(r.inventory??'—')}</strong></div><div class="product-detail"><span>WF Price</span><strong>${money(r.wfPrice)}</strong></div><div class="product-detail"><span>Listing Price</span><strong>${money(r.listingPrice)}</strong></div><div class="product-detail"><span>Live Price</span><strong>${money(r.finalLivePrice)}</strong></div><div class="product-detail"><span>WF MRP</span><strong>${money(r.wfMrp)}</strong></div></div>`;}
  function render(data,context){
    const title=document.getElementById('productDrawerTitle'),market=document.getElementById('productDrawerMarket'),ctx=document.getElementById('productDrawerContext'),body=document.getElementById('productDrawerBody'),tabs=document.getElementById('productDrawerTabs');if(!body)return;
    if(title)title.textContent=data.query;if(ctx)ctx.textContent=context==='global'?'Product 360':context;const markets=[data.amazon.length?'Amazon':'',data.flipkart.length?'Flipkart':''].filter(Boolean).join(' + ');if(market)market.textContent=markets||'No permitted marketplace match';
    if(tabs)tabs.innerHTML=context==='global'?['Overview','Pricing','Inventory','Issues','Mappings','History'].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join(''):'';
    if(!data.amazon.length&&!data.flipkart.length){body.innerHTML='<div class="utility-empty">No permitted product data matched this identifier in the selected snapshot.</div>';return;}
    const rows=[...data.amazon.map(r=>[r,'amazon']),...data.flipkart.map(r=>[r,'flipkart'])];
    if(context==='suppressions')body.innerHTML='<div class="v7-security-note">Suppression context: pricing/inventory information is intentionally limited. Use Open Full Product 360 if your permissions allow broader access.</div>'+rows.filter(([,m])=>m==='amazon').map(([r,m])=>rowCard(r,m)).join('');
    else if(context==='priceUpdates')body.innerHTML='<div class="v7-security-note">Price Updates context: current and target pricing identifiers for this product.</div>'+rows.map(([r,m])=>rowCard(r,m)).join('');
    else if(context==='marketplaceData')body.innerHTML='<div class="v7-security-note">Marketplace Data context: canonical identifiers and current mappings. Historical mapping-change records are shown when available in stored history.</div>'+rows.map(([r,m])=>rowCard(r,m)).join('');
    else body.innerHTML=rows.map(([r,m])=>rowCard(r,m)).join('');
  }
  async function open(identifier,opts={}){currentContext=opts.context||contextFromView();const data=await window.WakeSuiteProductResolver?.resolve(identifier,{date:opts.date});current=data;document.getElementById('productDrawerBackdrop')?.classList.add('open');render(data||{query:identifier,amazon:[],flipkart:[]},currentContext);}
  async function openFull(){if(!current)return;currentContext='global';render(current,'global');}
  function exportRows(){if(!current)return[];return [...current.amazon.map(r=>({Marketplace:'Amazon',Category:r.category,'WF SKU':r.wfSku,'ASIN':r.asin,'AZ SKU':r.azSku,Inventory:r.inventory,'WF Price':r.wfPrice,'Listing Price':r.listingPrice,'Live Price':r.finalLivePrice,'WF MRP':r.wfMrp})),...current.flipkart.map(r=>({Marketplace:'Flipkart',Category:r.category,'WF SKU':r.wfSku,'FSN':r.fsn,'FK SKU':r.fkSku,Inventory:r.inventory,'WF Price':r.wfPrice,'Listing Price':r.listingPrice,'Live Price':r.finalLivePrice,'WF MRP':r.wfMrp}))];}
  function download(){const rows=exportRows();if(!rows.length){window.showWakeSuiteToast?.('No product data is available to download.','warning');return;}if(window.XLSX){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Product Data');XLSX.writeFile(wb,`WakeSuite_Product_${String(current.query).replace(/[^A-Za-z0-9_-]/g,'_')}.xlsx`);}}
  // Upgrade the V9.1 ASIN/FSN drawer to the canonical resolver while preserving the same public function.
  window.openProductDrawer=function(marketplace,identifier){return open(identifier,{context:contextFromView(),marketplace});};
  window.openFullProduct360=openFull;window.downloadCurrentProductData=download;window.WakeSuiteProduct360={open,openFull,download};window.WakeSuiteModules?.register('product360',window.WakeSuiteProduct360);
})();
